components/app/explore/DatasetList.js
components/app/explore/DatasetWidget.js
components/modal/SubscribeToAlertsModal.js
css/components/app/pages/explore_detail.scss
pages/app/Explore.js
pages/app/ExploreDetail.js
services/DatasetService.js

Feature/share and subscribe buttons, similar datasets section

---

components/admin/dataset/form/DatasetForm.js
components/admin/dataset/form/constants.js
components/admin/dataset/form/steps/Step1.js
components/admin/dataset/table/td/NameTD.js
components/admin/metadata/form/steps/Step1.js
components/form/Field.js
components/form/File.js
components/form/FormElement.js
components/form/Navigation.js
components/form/SelectInput.js
css/_foundation_settings.scss
css/components/form/field-container.scss
css/components/form/field.scss
css/components/form/file.scss
css/components/form/form.scss
css/components/form/select.scss
css/components/ui/button.scss
css/components/ui/spinner.scss
css/components/ui/title.scss
css/index.scss
package.json
utils/request.js
yarn.lock

This PR adds:
- New dataset creation
- New dataset edit
- Possibility of uploading files
Still missing
- **Provider grouped by connector**: React select doesn't have support for groups but we could do it by a custom render or by getting another library named react-select-plus. We need to check it
Of course, we need to check it all the possibilities of uploading files because I only tested csv

Dataset creation

---

css/components/app/pages/explore_detail.scss
pages/app/ExploreDetail.js

add most of the fields that were missing from the metadata

---

components/app/explore/DatasetList.js
components/app/explore/DatasetListHeader.js
components/app/explore/DatasetWidget.js
css/components/app/explore/dataset_list.scss
css/components/app/explore/dataset_list_header.scss
css/components/app/layout/page.scss
css/components/app/pages/explore.scss

This PR adds several CSS fixes

Explore: several fixes

---

components/widgets/ColumnBox.js
css/components/widgets/columnbox.scss
css/components/widgets/dimensions_container.scss

Truncate name if long and add ellipsis. Add separator.

---

css/components/admin/widget/layer_chart.scss

make layer charts bigger so that they coincide with widgets

---

components/widgets/VegaChartTooltip.js
css/components/app/pages/embed/embed_widget.scss
pages/app/embed/EmbedDataset.js
pages/app/embed/EmbedWidget.js
utils/widgets/theme.js

This PR should fix all the styles and layout issues of the embedded widgets.

Fix the styles and layout of the embedded widgets

---

css/components/admin/widget/widget_chart.scss

This PR should fix all the remaining issues with the charts displayed in the My RW section.
Let me know if charts are broken somewhere else. I've made sure the explore pages are not broken.

Fix the styles of the charts in the My RW section

---

components/widgets/WidgetEditor.js
utils/widgets/WidgetHelper.js
utils/widgets/bar.js

This PR fixes an issue where a bar chart with a temporal x axis wouldn't be rendered at all. It also improves the feedback given to the user while the chart configuration is being computed.
[Pivotal task](https://www.pivotaltracker.com/story/show/149171617)

Bar chart rendering issue & user feedback improvements

---

components/modal/ShareModalExplore.js
css/components/modal/share_modal_explore.scss

improve styles of Share modal

---

components/app/myrw/widgets/MyRWWidgetsMy.js
components/app/myrw/widgets/MyRWWidgetsStarred.js
components/widgets/WidgetList.js
css/components/app/pages/myrw/myrw_widgets_my.scss

MyRW -> My Widgets list and grid mode

---

components/app/myrw/widgets/MyRWWidgetsMy.js
services/WidgetService.js

My Widgets: Sort by last modified

---

components/app/myrw/widgets/MyRWWidgetsEdit.js
components/modal/SaveWidgetModal.js
components/widgets/ChartEditor.js
components/widgets/WidgetEditor.js
css/components/app/pages/myrw/myrw_widgets_edit.scss
pages/app/MyRW.js

Missing fields and logic added to Edit Widget page

Complete My RW --> Edit widget page

---

components/widgets/ColumnBox.js
components/widgets/WidgetEditor.js
services/DatasetService.js
utils/widgets/WidgetHelper.js

Do not display the Widget Editor when a dataset only has cartodb_id and geometry columns

Fix: Widget Editor

---

components/vis/Map.js
css/components/app/pages/embed/embed_layer.scss
css/components/vis/map.scss
pages/app/embed/EmbedLayer.js

I need to put `requestAnimationFrame`before rendering the map. If you don't do that, the map won't take the correct height

Embed: layer layout and little insane fix

---

components/app/myrw/widgets/MyRWWidgetsMy.js
components/app/myrw/widgets/MyRWWidgetsStarred.js
components/widgets/WidgetActionsTooltip.js
components/widgets/WidgetCard.js
components/widgets/WidgetList.js
css/components/widgets/widget_actions_tooltip.scss
css/components/widgets/widget_card.scss
css/index.scss

Feature/update my widgets style (new actions added)

---

components/modal/HowToWidgetEditorModal.js
components/widgets/ChartEditor.js
components/widgets/FieldsContainer.js
components/widgets/WidgetEditor.js
css/components/widgets/chart_editor.scss
css/components/widgets/fields_container.scss
css/components/widgets/widget_editor.scss
static/images/components/widgets/Arrow.svg

Update styles widget editor

---

components/app/myrw/profile/MyRWProfileEdit.js
css/components/app/pages/myrw/myrw_edit_profile.scss

MyRW -> Edit profile: Fix styles and logic

---

components/app/myrw/widgets/MyRWWidgetsMy.js
css/components/app/pages/myrw/myrw_widgets_my.scss

fix position of new widget button

---

components/app/myrw/widgets/pages/edit.js
components/modal/SaveWidgetModal.js
components/widgets/ChartEditor.js
components/widgets/RasterChartEditor.js
components/widgets/WidgetEditor.js
css/components/widgets/raster_chart_editor.scss
css/index.scss
redactions/widgetEditor.js
services/RasterService.js
utils/getQueryByFilters.js
utils/widgets/WidgetHelper.js

This PR lets the user create bar charts with raster datasets. For now, the user won't be able to save the chart in My RW. This will come in a different PR.
I don't think the changes would break anything but if you guys know specific cases that I might have forgotten, please test it. The pages that might be affected are all the ones that deal with the editor or the Vega charts: Explore, Explore Details, My RW, Admin.

Create bar charts with raster datasets

---

utils/widgets/WidgetHelper.js

Type 'text' was missing in the ALLOWED_FIELDS array

Add text as an elastic allowed field type

---

css/_mixins.scss
css/_settings.scss
css/components/ui/tree_selector.scss
css/index.scss
pages/app/Explore.js

Due to the markup generated by the library, there is some stuff needs to be polished.

Unifies selector styles

---

.editorconfig
components/app/explore/FiltersResume.js
css/_base.scss
css/components/app/explore/resume_filters.scss
css/index.scss
pages/app/Explore.js
services/DatasetService.js

Implements filters resume component. They need some styling, I just added a task for the designer (https://www.pivotaltracker.com/story/show/150666488).
Also, we are now displaying the values (not the labels) of these filters, shouldn't better display the labels? This would require some changes though.

Explore - filters resume

---

components/datasets/form/constants.js
components/datasets/form/steps/Step1.js
pages/app/Explore.js

Add new checkbox to Dataset form (geoInfo attribute)

---

pages/app/embed/EmbedDataset.js

The component wouldn't be correctly connected to the store.
[Pivotal task](https://www.pivotaltracker.com/story/show/150888363)

Fix an issue that prevented the dataset embed to work

---

components/widgets/WidgetEditor.js

The widget editor selectors are also shown in table view mode now

fix table view bug

---

css/components/areas/area_card.scss
css/components/areas/areas_list.scss

Task: https://www.pivotaltracker.com/story/show/150804158

Sets area cards with equal height

---

css/components/app/pages/explore_detail.scss
pages/app/ExploreDetail.js

Task: https://www.pivotaltracker.com/story/show/150884572

Hides description of dataset with huge ones

---

components/app/layout/Header.js
components/form/ToggleSearch.js
css/components/form/toggle-search.scss
css/index.scss
next.config.js
package.json

Added search in the header using Addsearch plugin.

added search with addserach plugin

---

css/components/areas/area_card.scss

Task: https://www.pivotaltracker.com/story/show/150997843

Places to bottom action in area cards

---

components/datasets/form/constants.js
components/datasets/form/steps/Step1.js
components/form/File.js

Task: https://www.pivotaltracker.com/story/show/150964522

Shows columns of an uploaded CSV

---

selectors/explore/filterDatasets.js

This pull request fixes the regression that prevented the filtering in Explore to work.

Fix explore filtering

---

components/datasets/form/constants.js
components/datasets/form/steps/Step1.js

Task: https://www.pivotaltracker.com/story/show/151040011

Backoffice datasets changes

---

components/form/File.js

Task: https://www.pivotaltracker.com/story/show/150964522

Filters empty columns in document selection

---

pages/app/ExploreDetail.js

The dataset title for https://staging.resourcewatch.org/data/explore/3f4b9be7-e000-41aa-bde2-83b9b13c8e35 was previously not being shown

Fix dataset title fetch

---

pages/app/Explore.js
selectors/explore/filterDatasets.js

Task: https://www.pivotaltracker.com/story/show/151176336

Explore: fixes datasets filtering

---

components/admin/metadata/form/MetadataForm.js
components/admin/metadata/form/constants.js
components/admin/metadata/form/steps/Step1.js
components/datasets/form/DatasetsForm.js
services/DatasetsService.js
utils/datasets/fields.js

Tasks: 
https://www.pivotaltracker.com/story/show/151168232
https://www.pivotaltracker.com/story/show/151169064

User should be able to see metadata fields for raster datasets depending on the provider

---

components/widgets/VegaChart.js

This PR fixes an issue that prevented the legend of the vega charts from displaying.

Fix an issue preventing the display of legend of the vega charts

---

components/areas/AreasList.js

Fix bug in AreasList as part of the section 'Areas of interest'

---

components/admin/widgets/form/WidgetsForm.js
components/admin/widgets/form/steps/Step1.js

Task: https://www.pivotaltracker.com/story/show/151210162

Users should not be able to save empty widgets

---

components/datasets/form/constants.js

Task: https://www.pivotaltracker.com/story/show/151175309

User should be able to see the table name in dataset edition

---

components/admin/layers/table/LayersTable.js
components/admin/pages/table/PagesTable.js
components/admin/partners/table/PartnersTable.js
components/admin/widgets/table/WidgetsTable.js
components/dashboards/table/DashboardsTable.js
components/datasets/table/DatasetsTable.js

https://www.pivotaltracker.com/story/show/151256369

Fixes displaying deleted resources after removing them

---

components/datasets/form/steps/Step1.js
components/form/File.js

Task: https://www.pivotaltracker.com/story/show/151322777

Fixes dataset JSON upload

---

components/app/explore/DatasetWidget.js
pages/app/ExploreDetail.js

Datasets cards shown in the section 'Similar datasets' include now their default widget and source if present.

Improvements in similar datasets section 

---

components/widgets/editor/helpers/getQueryByFilters.js
components/widgets/editor/nexgddp/NEXGDDPEditor.js
components/widgets/editor/services/DatasetService.js
components/widgets/editor/tooltip/FilterDateTooltip.js
components/widgets/editor/tooltip/FilterNumberTooltip.js
components/widgets/editor/tooltip/FilterStringTooltip.js
components/widgets/editor/tooltip/FilterTooltip.js
css/components/widgets/filter_tooltip.scss
css/index.scss
package.json
yarn.lock

I'm not very proud of the FilterTooltipDate but....it works. Anyway, we need to figure out how to deal with different frequencies

Widget editor: filters by date

---

components/app/myrw/widgets/MyRWWidgetsMy.js
components/widgets/editor/services/WidgetService.js
services/WidgetService.js

- The sorting of the list has also been fixed in this pull request

Fix My Widgets: Include widgets both from production and preproduction envs

---

components/datasets/form/steps/Step1.js

Allows geo info for any type of metadata

---

components/app/pulse/GlobeTooltip.js
utils/layers/pulse_layers.js

- Fix Earthquakes layer ID
- Prevent tooltip from closing itself when clicking inside of it

A couple of fixes for Planet Pulse

---

components/app/explore/DatasetWidgetChart.js
components/app/pulse/LayerCard.js
components/app/pulse/LayerNavDropdown.js
css/components/app/pulse/layer_card.scss
pages/app/Pulse.js
redactions/pulse.js

This pull request includes a prototype of similar widgets displayed in the layer card.

Some improvements for Planet Pulse

---

CHANGELOG.md
components/widgets/editor/tooltip/FilterStringTooltip.js
components/widgets/editor/tooltip/FilterTooltip.js
css/components/widgets/filter_tooltip.scss

Search input for widget editor filter

---

components/admin/metadata/form/steps/Step1.js
components/datasets/form/steps/Step1.js

Task: https://www.pivotaltracker.com/story/show/151124546

New fields for dataset/metadata

---

components/admin/metadata/form/MetadataForm.js
components/admin/metadata/form/steps/Step1.js
components/datasets/form/DatasetsForm.js
components/datasets/form/steps/Step1.js
services/DatasetsService.js
utils/datasets/fields.js

Changes did at dataset and metadata form
- Check type before getting fields, not only provider
- Spinner for columns

Fix metadata and dataset columns behaviour

---

components/form/File.js

Dataset: upload json fixes

---

.env.sample
Dockerfile-prod
Dockerfile-staging
components/admin/layout/head.js
components/app/layout/head.js
next.config.js

You must add this variable to your .env **```TRANSIFEX_LIVE_API```**

Transifex added to all pages

---

CHANGELOG.md
components/widgets/editor/helpers/pie.js
utils/widgets/pie.js

This PR makes the pie chart responsive. That also means that its thumbnail is now longer broken.

Responsive pie charts

---

utils/layers/pulse_layers.js

Some layers were updated (basically names and ids)

Updating layers in Planet Pulse

---

css/components/app/explore/dataset_widget.scss
pages/app/Explore.js
utils/explore/TreeUtil.js

- Tags icon relocated
- Filters sum up shows now the labels of the concepts instead of their ids

Explore: minor improvements

---

CHANGELOG.md
components/datasets/form/steps/Step1.js

- Datasets always show geoInfo value, even if they are rasters (it will be always true)

Datasets geoinfo

---

components/app/myrw/profiles/form/ProfilesForm.js
services/UserService.js

MyRW profile: update name available

---

utils/layers/pulse_layers.js

Updating layers for planet pulse and adding widgets

Updating layers

---

components/app/pulse/LayerCard.js
css/components/app/pulse/layer_card.scss
pages/app/Pulse.js
redactions/pulse.js

Planet Pulse: similar widgets

---

pages/app/ExploreDetail.js
pages/app/Pulse.js

Source is now displayed in Explore Detail header

---

css/components/app/explore/dataset_widget.scss

Fix styles of title container in list mode

---

components/app/myrw/widgets/pages/new.js
components/widgets/editor/modal/SaveWidgetModal.js

* In My RW, the user wouldn't be able to create a widget due to a regression from 83b78c4
* In the admin section, the band wouldn't be saved properly due to a regression from f2f5071

Fix several bugs related to the widget creation

---

components/app/layout/Header.js
components/app/layout/header/HeaderUser.js
pages/app/MyRW.js

Use name for My RW header

---

CHANGELOG.md
components/app/layout/Layout.js
components/app/layout/head.js
components/form/ToggleSearch.js
pages/app/ExploreDetail.js
static/styles/add-search-results.css

Changed search results styles.
Before:
After:

styles for search results

---

CHANGELOG.md
components/app/layout/Footer.js
css/components/ui/terms.scss
css/index.scss
pages/app/Policy.js
pages/app/Terms.js
routes.js

Terms and privacy added

---

CHANGELOG.md
components/widgets/editor/map/Map.js
components/widgets/editor/map/constants.js
components/widgets/editor/map/controls/BasemapControl.js
css/components/ui/tooltip.scss
redactions/explore.js

added support for labels above layers and tiles without labels

---

components/app/explore/DatasetWidget.js

add last update to explore cards

---

components/widgets/editor/WidgetEditor.js
components/widgets/editor/chart/ChartEditor.js
components/widgets/editor/map/MapEditor.js
components/widgets/editor/nexgddp/NEXGDDPEditor.js
components/widgets/editor/raster/RasterChartEditor.js
css/components/widgets/chart_editor.scss
css/components/widgets/map_editor.scss
css/components/widgets/raster_chart_editor.scss
pages/app/ExploreDetail.js

Show text instead of save button when an user is not logged in

---

CHANGELOG.md
pages/app/ExploreDetail.js

Add technical title to Explore Detail (formal name)

---

components/app/layout/head.js

- User report added to site
- some eslint fixes

User-report added to site

---

components/app/layout/head.js

Tracking IDs should probably be moved to .env

Add GA and CrazyEgg to head

---

components/app/layout/Footer.js
css/layouts/_footer.scss

Footer: social links

---

components/app/dashboards/DashboardCard.js
pages/app/DashboardsDetail.js
pages/app/embed/EmbedDashboard.js
redactions/user.js

This PR fixes a couple of bugs that prevented the user from "favouriting" a widget in the water dashboard.
[Pivotal task](https://www.pivotaltracker.com/story/show/150511334)

Fix bugs that prevented a user from "favouriting" a widget

---

utils/layers/pulse_layers.js

Were deleted one layer (Land surface temperature anomalies) and was added one widget (for Potential Landslide Areas)

Update of layers

---

CHANGELOG.md
components/modal/LayerInfoModal.js
css/components/modal/layer_info_modal.scss
css/index.scss

Add styles for LayerInfoModal component

---

pages/app/ExploreDetail.js

This PR fixes two eslint and two prop validation errors as well as improves the errors shown to the user.
In addition, it simplifies two functions that either were related to one of the errors or that displayed non-descriptive errors to the user.

Fix eslint and prop validation errors in ExploreDetails

---

pages/app/ExploreDetail.js

Add sources metadata field to Explore Detail

---

CHANGELOG.md
components/app/explore/DatasetList.js
components/app/explore/DatasetTagsTooltip.js
components/app/explore/DatasetWidget.js
components/app/myrw/datasets/MyRWDatasetsStarred.js
components/app/myrw/datasets/pages/index.js
components/app/myrw/widgets/pages/index.js
css/_settings.scss
css/components/app/explore/dataset_tags_tooltip.scss
css/components/app/explore/dataset_widget.scss
css/components/app/pages/explore_detail.scss
css/components/app/pages/myrw/myrw_datasets_starred.scss
css/index.scss
pages/app/Explore.js
pages/app/ExploreDetail.js
redactions/explore.js
services/UserService.js

Favorite datasets

---

components/admin/widgets/form/WidgetsForm.js
components/app/myrw/widgets/pages/edit.js
components/modal/EmbedMyWidgetModal.js
components/widgets/editor/WidgetEditor.js
components/widgets/editor/embed/EmbedEditor.js
components/widgets/editor/form/Field.js
components/widgets/editor/helpers/WidgetHelper.js
components/widgets/editor/modal/SaveWidgetModal.js
components/widgets/editor/redux/widgetEditor.js
components/widgets/list/WidgetCard.js
css/components/admin/widget/widget_chart.scss
css/components/app/pages/embed/embed_widget.scss
css/components/widgets/widget_editor.scss
pages/app/embed/EmbedEmbed.js
pages/app/embed/EmbedMap.js
pages/app/embed/EmbedWidget.js
redactions/widget.js
routes.js

This PR is important because, before it, you can't update map widgets....

Widgets: embed widget created

---

components/app/layout/head.js
components/datasets/table/DatasetsTable.js
components/datasets/table/td/OwnerTD.js

Add owner column to dataset table in the back office

---

components/app/explore/DatasetWidget.js

Everything's in the title.
[Pivotal task](https://www.pivotaltracker.com/story/show/152595065)

Remove a "0" from the UI in the cards in Explore

---

components/widgets/editor/form/Checkbox.js
components/widgets/editor/map/controls/BasemapControl.js
yarn.lock

Everything's in the title and the commit names.
[Pivotal task](https://www.pivotaltracker.com/story/show/152441963)

Correctly display the state of the labels in the Explore map's controls

---

.env.sample
components/widgets/editor/services/WidgetService.js
services/DatasetService.js
services/DatasetsService.js
services/WidgetService.js

This PR creates an `API_ENV` variable to store the value of the `env` parameter to send to the API.
To test it, add `API_ENV=production,preproduction` to your `.env` file.
When you merge, don't forget to post a message in the channel ;).

Create an API_ENV variable

---

.env.sample
components/app/explore/DatasetWidget.js
components/app/layout/Layout.js
components/app/layout/Sidebar.js
components/app/layout/head.js
components/app/myrw/widgets/pages/new.js
components/app/pulse/LayerNavDropdown.js
components/areas/AreasForm.js
components/dashboards/form/DashboardsForm.js
components/datasets/form/DatasetsForm.js
components/modal/AreaSubscriptionModal.js
components/modal/ShareExploreDetailModal.js
components/widgets/editor/WidgetEditor.js
components/widgets/editor/chart/ChartEditor.js
components/widgets/editor/modal/SaveWidgetModal.js
components/widgets/editor/modal/ShareModalExplore.js
components/widgets/editor/nexgddp/NEXGDDPEditor.js
components/widgets/editor/ui/AreaIntersectionFilter.js
components/widgets/editor/ui/CategoryContainer.js
components/widgets/editor/ui/FilterContainer.js
components/widgets/editor/ui/SortContainer.js
components/widgets/editor/ui/ValueContainer.js
package.json
pages/app/Explore.js
pages/app/ExploreDetail.js
pages/app/Pulse.js
utils/analytics.js
yarn.lock

This PR configures the Google Analytics page views and events. A `GOOGLE_ANALYTICS` environment variable has been added, so don't forget to let the channel know about it when merged.
When the app is ran in the development environment, the events and page views are logged in the console (using `console.info`) instead of being sent.
[Pivotal task](https://www.pivotaltracker.com/story/show/151640936)

Configure the Google Analytics page views and events

---

PULL_REQUEST_TEMPLATE.md

This PR adds a template for all the pull requests in order to provide enough details for the reviewer.
None.
None.

Add a template for the pull requests

---

components/app/layout/header/HeaderUser.js
pages/app/ExploreDetail.js
pages/app/Splash.js

This PR makes sure we use `next-routes` for the routing as much as we can.
[Pivotal task](https://www.pivotaltracker.com/n/projects/1374154/stories/152804708)

Remove the unnecessary window.location from the code

---

pages/app/Explore.js

Filters' values are now sorted alphabetically
[Pivotal Task] https://www.pivotaltracker.com/story/show/152884617

Explore: Sort filters alphabetically

---

components/app/pulse/LayerCard.js
components/modal/LoginModal.js
css/components/app/pulse/layer_card.scss
css/components/modal/login_modal.scss
css/index.scss
pages/app/ExploreDetail.js

[Pivotal Task](https://www.pivotaltracker.com/story/show/153171460)

Visibility of subscribing functions for anonymous users

---

css/components/error.scss
css/index.scss
pages/_error.js

[Pivotal Task](https://www.pivotaltracker.com/story/show/153172795)

Add customized 404 page

---

css/components/app/pages/splash_detail.scss
pages/app/SplashDetail.js

- Cursor pointer when hovering over hotspots
- Use HTML markup for hotspots' content
- Change position of the hotspots so that one is in front of the camera and the other at the back

Coral panorama improvements

---

components/app/common/CardStatic.js
components/app/layout/Footer.js
components/app/layout/header/HeaderDropdownData.js
components/ui/CompoundMenu.js
pages/app/ExploreDetail.js
pages/app/ExploreDetailBeta.js
pages/app/Home.js

I changed all the planet pulse links to anchors to be sure that we reload the page. That will prevent the loading Cesium error.
https://www.pivotaltracker.com/story/show/153242409

Planet pulse: links updated to avoid using next routes

---

components/app/explore/DatasetWidget.js

Little re-structure to avoid having widget and layers at the same time in the 
https://www.pivotaltracker.com/story/show/153245736

Widget: Select correct chart. widgets has preference over layers

---

components/form/Navigation.js

Hit enter does not submit the form
https://www.pivotaltracker.com/story/show/153280053

Dataset: Hit enter does not submit the form

---

pages/app/ExploreDetail.js
pages/app/ExploreDetailBeta.js

The Explore Detail page returns a 404 if a dataset doesn't exist.

checkin if dataset exists

---

components/datasets/form/constants.js
components/datasets/form/steps/Step1.js
components/datasets/table/DatasetsTable.js
components/datasets/table/actions/DeleteAction.js
utils/request.js

This PR adds a new attribute to dataset form => protected. If it is activated you won't be able to delete the dataset unless you change it.
https://www.pivotaltracker.com/story/show/153314868

Dataset: protected attribute added to form

---

components/admin/tags/TagsForm.js

https://www.pivotaltracker.com/story/show/153318444

Cancel button added to TagForm

---

pages/app/Pulse.js

https://www.pivotaltracker.com/story/show/153558615

Planet pulse: navigation bug fixed

---

components/areas/AreasForm.js
pages/app/MyRWDetail.js

- Correct user token
- Cancel button does not trigger the submit function
https://www.pivotaltracker.com/story/show/153285230

Areas: correct token

---

components/dashboards/wysiwyg/widget-block/widget-block-component.js
pages/app/DashboardsDetail.js

https://www.pivotaltracker.com/story/show/153367652

Thumbnail list added again only for published dashboards

---

pages/app/ExploreDetail.js
redactions/explore.js

Check any dataset detail page that has at least one layer.
[Pivotal task](https://www.pivotaltracker.com/story/show/153453387)

Explore detail: Open in Explore button

---

css/components/app/pages/embed/embed_widget.scss
pages/app/embed/EmbedMap.js
pages/app/embed/EmbedWidget.js

Check these two embed pages:
- Map: `http://localhost:3000/embed/map/4521b085-cb91-4ec9-8da9-b4f85739b494`
- Widget: `http://localhost:3000/embed/widget/5f5f7899-ccd2-4477-aa7e-43805880eb33`
[Pivotal task](https://www.pivotaltracker.com/story/show/153542840)

Add "Powered by" to embed pages

---

components/ui/SearchInput.js
pages/app/Explore.js
selectors/explore/filterDatasets.js

The explore search now looks for text in the following dataset fields:
- Metadata title _(or dataset name if the latter doesn't exist)_
- Metadata info source
- Metadata info functions
- Tags
Search by values present in the fields: `source`, `functions` or tag names in the Explore page.
[Pivotal task](https://www.pivotaltracker.com/story/show/153594389)

Explore: Search improvements

---

components/admin/layout/Header.js
components/admin/layout/Layout.js
components/admin/layout/Page.js
components/app/layout/Header.js
components/app/layout/Layout.js
components/app/layout/header/HeaderUser.js
components/app/layout/search/search-component.js
pages/app/Home.js
pages/app/Insights.js
pages/app/Pulse.js
pages/app/Splash.js
pages/app/SplashDetail.js

There was a bug in the way of storing of the user. So I decided to put together admin and app layouts to always use the user from redux. It's very important to deploy this fix to production as soon as possible as long as it doesn't work well in prod.
No

User: admin and app fixes to better use of the user info

---

components/admin/datasets/pages/index.js
components/admin/layout/Header.js
components/datasets/table/DatasetsTable.js
components/datasets/table/td/OwnerTD.js
css/components/ui/table.scss
css/layouts/_container.scss
pages/admin/Dashboards.js
pages/admin/DashboardsDetail.js
pages/admin/Data.js
pages/admin/DataDetail.js
pages/admin/Pages.js
pages/admin/PagesDetail.js
pages/admin/Partners.js
pages/admin/PartnersDetail.js
pages/admin/Tools.js
pages/admin/ToolsDetail.js

- Styles of the table changed
- Admin max-width increased 
https://www.pivotaltracker.com/story/show/153629254

Fix admin grid and tables

---

components/widgets/editor/services/WidgetService.js

Fix: remove application parameter from fetch in save user widget request

---

components/datasets/table/DatasetsTable.js
services/DatasetsService.js

Check the datasets table `http://localhost:3000/admin`
[Pivotal task](https://www.pivotaltracker.com/story/show/153542866)

Back office: load only datasets that were created by users with an ADMIN role

---

components/admin/dashboards/pages/index.js
components/admin/tags/TagsForm.js
components/admin/widgets/pages/index.js
components/admin/widgets/table/WidgetsTable.js
components/app/dashboards/DashboardCard.js
components/dashboards/wysiwyg/DashboardWidget.js
components/dashboards/wysiwyg/widget-block/widget-block-actions.js
components/widgets/editor/services/DatasetService.js
components/widgets/editor/services/UserService.js
components/widgets/editor/services/WidgetService.js
redactions/explore.js
services/DatasetService.js
services/GraphService.js
services/UserService.js
services/WidgetService.js

[Pivotal task](https://www.pivotaltracker.com/story/show/153939810)

Fix for application being sent in wrong places across different endpoints

---

components/app/explore/explore-dataset-filters/explore-dataset-filters-actions.js
components/app/explore/explore-dataset-filters/explore-dataset-filters-component.js
css/components/app/pages/explore.scss
pages/app/Explore.js

This PR adds a _*Request data*_ button to the Explore page that appears when the combination of filters + search text didn't return any results.
Choose a filter and/or search string that returns no results on the Explore page
[Pivotal Task](https://www.pivotaltracker.com/story/show/154118312)

Explore: Request data button

---

components/admin/widgets/form/steps/Step1.js
components/app/explore/DatasetWidgetChart.js
components/widgets/charts/VegaChart.js
css/components/admin/widget/form.scss

This PR adds a preview that can be refreshed at will for the *_"Advanced"_* mode of the widget form.
Check the `advanced` mode of any widget both on the process of creation and update.

Widget preview in Advanced mode

---

css/components/app/pages/splash_detail.scss
utils/splash/Panoramas.js

This PR fixes the scrolls that were appearing in videos loaded through `<iframe/>` tags.
Go to http://localhost:3000/splash/coral and select the hotspot: `Coral bleaching on the rise`

Make coral video responsive

---

components/app/myrw/areas/AreasTab.js
components/app/myrw/areas/pages/index.js
components/app/myrw/areas/pages/new.js
components/areas/AreasForm.js
components/areas/AreasList.js
pages/app/MyRWDetail.js

Areas URL query params --> Use Redux

---

components/widgets/charts/VegaChart.js
components/widgets/charts/VegaChartTooltip.js
yarn.lock

This PR contains changes merged in PREP. See the details here: https://github.com/resource-watch/prep-manager/pull/31
There are currently not test cases in RW.
None.

Improve the tooltip of the Vega Chart

---

components/widgets/charts/VegaChart.js
components/widgets/charts/VegaChartTooltip.js
yarn.lock

Reverts resource-watch/resource-watch#504

Revert "Improve the tooltip of the Vega Chart"

---

components/admin/layers/form/LayersForm.js
components/admin/layers/form/steps/Step1.js
css/components/admin/layer/form.scss
css/index.scss
pages/app/Explore.js

This PR adds a layer preview to the layer form in the back office. It includes a *_"Refresh"_* button that allows the user to update the preview.
Check any layer in the back office _(scroll down to the bottom of the form to see the preview)_

Back office --> Layer preview

---

pages/app/SplashDetail.js

Splash coral: fix arrow

---

components/modal/ShareModalExplore.js
components/widgets/editor/modal/ShareModalExplore.js

Explore share modal styles fix

---

pages/app/ExploreDetail.js

This PR fixes a problem with datasets that had null values for some of the metadata fields.
Check the Explore detail page for the datasets mentioned in the PT task.

Explore detail fix

---

components/widgets/editor/ui/Legend.js

This PR allows an easier and more complete way to manage timelines.
The field `dateTime` is no longer needed as part of the `layerConfig` object. These are all the fields that should be present instead:
- `timeline`: should be equals to `true` for the layers that should be part of the timeline
- `order`: number that will be used to calculate the position of the layer in the timeline
- `timelineLabel`: text that will appear in the timeline when the layer is active
Check the Explore page with the the dataset *[Standard Precipitation Index selected](http://localhost:3000/data/explore?page=1&layers=%255B%257B%2522dataset%2522%253A%2522c0c71e67-0088-4d69-b375-85297f79ee75%2522%252C%2522visible%2522%253Atrue%252C%2522layers%2522%253A%255B%257B%2522id%2522%253A%2522d57be513-7510-4c97-bc0c-88b3a64 …

Improve how timelines are managed

---

components/datasets/metadata/form/MetadataForm.js
components/modal/SubscribeToDatasetModal.js
components/modal/UploadAreaIntersectionModal.js
components/subscriptions/SubscriptionCard.js
components/ui/SliderSelect.js

This PR removes completely the use of Autobind in the project.

Get rid of Autobind for good

---

components/ui/customtable/header/TableHeaderActions.js
components/ui/customtable/header/TableSorts.js
utils/widgets/bar.js
utils/widgets/line.js
utils/widgets/pie.js

Fixes for a few bugs originated from the WidgetEditor migration

---

components/app/layout/head.js

Do not include either UserReport or Transifex in any of the embed pages

---

services/collections-service.js

Updates collection service with application filter

Updates collection service with application filter

---

components/datasets/list/index.js
selectors/admin/datasets.js
selectors/myrw/datasets.js

Restores the previous selector for admin
Go to MyRW (as admin) > datasets

Fixes dataset selector for admin

---

package.json

This PR upgrades the WidgetEditor dependency.
Check the Widget editor

Upgrade widget editor dependency

---

services/collections-service.js

Sets application when creates a collection

Sets application when creates a collection

---

redactions/admin/datasets.js
redactions/admin/widgets.js

Updates favourite filter according to API specification.

Updates favourites filter

---

css/components/app/pages/embed/embed_dataset.scss
pages/app/embed/EmbedDataset.js

Embed dataset: fix that allows the widget to be displayed properly

---

redactions/user.js

Allows the user to delete a collection.
https://www.pivotaltracker.com/n/projects/1374154/stories/154794195

Creates delete collection action

---

components/admin/partners/table/PartnersTable.js
components/app/layout/Footer.js
css/components/app/pages/partner_detail.scss
pages/app/PartnerDetail.js
pages/app/Partners.js
redactions/admin/partners.js
redactions/partnerDetail.js
selectors/admin/partners.js

This PR adds a related content section - datasets - to the partner detail pages.
Check this link for instance: http://localhost:3000/about/partners/wri

Partner detail: Add related datasets

---

components/widgets/list/WidgetCard.js

This PR adds a delay of 8 seconds to give the widget the possibility to render
You can't test it locally

Export to PDF: add waitFor=8000

---

components/app/pulse/LayerCard.js
components/app/pulse/LayerNavDropdown.js
components/app/pulse/Legend.js
css/components/app/pulse/layer_card.scss
css/components/app/pulse/layer_nav_dropdown.scss
pages/app/Pulse.js
redactions/pulse.js
utils/layers/LayerGlobeManager.js
utils/layers/pulse_layers.js

Planet pulse improvements (not fully finished)

---

components/app/pulse/LayerCard.js
components/app/pulse/layer-pill/layer-pill-component.js
components/app/pulse/layer-pill/layer-pill.js
pages/app/Pulse.js
redactions/pulse.js
utils/layers/pulse_layers.js

This PR incorporates a new component `LayerPill` as well as fixes the contextual layers legend visibility.

Planet Pulse: Improvements

---

utils/layers/pulse_layers.js

new iteration of layers/context and widgets

---

components/admin/widgets/table/WidgetsTable.js

This PR adds:
- page size 9999 to admin widgets table
- proper way to filter by dataset
Go to admin widgets page

Widget: admin table

---

pages/app/MyRWDetail.js

Fixes https://www.pivotaltracker.com/story/show/154948814
https://www.pivotaltracker.com/story/show/154948814
---

Fixes myRW redirects

---

components/admin/faqs/FaqsTab.js
components/admin/faqs/form/FaqsForm.js
components/admin/faqs/form/constants.js
components/admin/faqs/form/steps/Step1.js
components/admin/faqs/pages/index.js
components/admin/faqs/pages/new.js
components/admin/faqs/pages/show.js
components/admin/faqs/table/FaqsTable.js
components/admin/faqs/table/actions/DeleteAction.js
components/admin/faqs/table/actions/EditAction.js
components/admin/faqs/table/td/QuestionTD.js
components/admin/layout/Header.js
components/app/common/Faqs/FaqBlock.js
components/app/layout/Footer.js
components/app/layout/header/HeaderDropdownAbout.js
css/components/admin/faqs/faqs_table.scss
css/components/app/common/faq.scss
css/index.scss
pages/admin/Faqs.js
pages/admin/FaqsDetail.js
pages/app/Faqs.js
redactions/admin/faqs.js
redactions/index.js
routes.js
selectors/admin/faqs.js
services/FaqsService.js

**Towards:** https://www.pivotaltracker.com/n/projects/1374154/stories/155029252

Admin App: add FAQs functionality and pages

---

components/admin/faqs/table/FaqsTable.js
components/app/common/ContactUs/ContactUsForm.js
components/app/common/ContactUs/constants.js
components/app/layout/header/HeaderDropdownAbout.js
css/components/ui/contact-us.scss
css/index.scss
pages/app/ContactUs.js
routes.js

**Closes:** https://www.pivotaltracker.com/story/show/155030340
**Note:** although initial contact us form is created the form does not post data.

Add contact us page with initial form

---

components/app/layout/header/HeaderDropdownAbout.js
pages/app/Faqs.js
pages/app/Howto.js
redactions/admin/faqs.js
routes.js

This PR adds HowTo page and the link to header

How to: page added

---

components/admin/faqs/table/FaqsTable.js

Fix: restore faq table state

---

components/admin/layout/Header.js
pages/admin/Faqs.js

Fixes labels from *Faqs* to *FAQs*

Update admin label values for FAQs

---

components/app/common/ContactUs/ContactUsForm.js
components/app/common/ContactUs/constants.js
components/form/Navigation.js
services/ContactUsService.js

Towards integrating Contact us UI with Contact us service.

Add contact us service

---

components/app/explore/DatasetList.js
components/app/layout/head.js
components/app/layout/header/header-component.js
components/app/layout/header/header-menu-mobile/header-menu-mobile-component.js
components/explore-detail/explore-detail-actions/explore-detail-actions-component.js
components/explore-detail/explore-detail-helpers.js
components/explore-detail/explore-detail-widget-editor/explore-detail-widget-editor-component.js
components/explore-detail/explore-detail-widget-editor/index.js
components/modal/LoginModal.js
css/_foundation_settings.scss
css/components/app/pages/explore_detail.scss
css/components/explore-detail/explore-detail-actions.scss
css/layouts/_page.scss
pages/app/Explore.js
pages/app/ExploreDetail.js
utils/responsive.js

This PR adds:
https://www.pivotaltracker.com/story/show/155220889

Explore detail: responsive first steps

---

components/datasets/form/constants.js
components/datasets/form/steps/Step1.js

Add new field so its possible to edit mainDate in the dataset form
https://www.pivotaltracker.com/story/show/155358235

add mainDateField for dataset form

---

components/datasets/form/steps/Step1.js
css/_helpers.scss

Allow all datatypes for columns displayed in mainDateField
Also show what type the column is in the options
https://www.pivotaltracker.com/story/show/155358235

FIX: (dataset form): do not restrict columns to date for mainDateField

---

components/app/myrw/widgets/my-rw-widgets/my-rw-widgets-component.js

Add a toastr success msg for when removing a widget successfully. 
https://www.pivotaltracker.com/story/show/155392162

BUG: add success msg for when deleting widget on profile page

---

package.json
pages/app/explore-detail/explore-detail-actions.js
pages/app/explore-detail/index.js
services/DatasetService.js
yarn.lock

This PR adds a WRI json serializer

Explore detail: WRI serializer

---

components/layout/footer/footer-component.js
components/modal/newsletter-modal/component.js
components/modal/newsletter-modal/index.js
css/layouts/_footer.scss

This PR adds a button to the footer ("Join us") that opens a modal with the form to sign up to the newsletter.
Go to the footer of any page and click on "Join us"

Join us button at footer and newsletter modal

---

components/admin/layers/form/steps/Step1.js

Ended up with some conflicts in the Step1 form (admin layers)

conflicts for step1 layers form resolved

---

css/components/app/pages/myrw/myrw_widgets_my.scss
css/components/app/pages/myrw/myrw_widgets_new.scss
css/components/form/field.scss
css/index.scss

Check the Pivotal task below 👇

Fixes for styles in Profile --> Widgets section

---

components/layout/head/app.js
components/splash/layout/Header.js
css/components/splash/layout/splash_header.scss
pages/app/Splash.js

Remove Feedback button on splash page
Add skip intro button & logic
go to /splash and skip intro
https://www.pivotaltracker.com/story/show/155220290
https://www.pivotaltracker.com/story/show/155220729

FIX/ splash page fixes

---

components/layout/header/header-actions.js
components/layout/header/header-menu-mobile/component.js
components/layout/header/header-reducers.js
components/layout/header/search-mobile/component.js
components/layout/header/search-mobile/index.js
components/ui/SearchInput.js
css/components/ui/search-input.scss
css/components/ui/search-list.scss
css/index.scss
css/layouts/_header-menu-mobile.scss
pages/app/search/index.js
pages/app/search/search-actions.js
pages/app/search/search-component.js
pages/app/search/search-default-state.js
pages/app/search/search-list/index.js
pages/app/search/search-list/search-list-component.js
pages/app/search/search-reducers.js
pages/app/search/search.js
routes.js
store.js

This PR adds a search page with:
- pagination
- input for searching
It also adds a search input to the mobile menu
You can only access it via mobile
https://www.pivotaltracker.com/story/show/155629600
https://www.pivotaltracker.com/story/show/155358148

Search page

---

utils/splash/Panoramas.js

This PR updates the widgets/maps used in the Splash coral page
Go to `localhost:3000/splash/coral`

Update Splash coral page widgets

---

components/ui/CompoundMenu.js
css/layouts/_footer.scss
layout/footer/footer-component.js

This PR updates the elements shown in the footer as well as the layout/appearance changes necessary to comply with the latest version of the design prototype.
Check the footer of any page e.g. `localhost:3000`

Footer updates: elements and layout

---

components/vis/globe-cesium/component.js

This PR increases the speed of the zoom when using the zoom component
Check `localhost:3000/data/pulse` and click on the zoom component +/-

Planet Pulse: increase zoom component speed

---

components/app/explore/DatasetList.js
layout/catalog/actions.js
layout/catalog/component.js
layout/catalog/default-state.js
layout/catalog/index.js
layout/catalog/reducers.js
pages/app/catalog/index.js
pages/app/catalogue/index.js
routes.js
store.js

This PR adds the first version of the new catalog page
Go to `localhost:3000/catalog`

Catalog page

---

components/admin/widgets/form/steps/Step1.js
components/ui/map/Map.js
components/widgets/metadata/form/steps/Step1.js
components/wysiwyg/widget-block/widget-block-component.js
css/components/dashboards/dashboard-card.scss
css/components/form/wysiwyg.scss
layout/header/header-default-state.js

This PR includes the following updates related to topic pages
- Widget captions can be now created/edited in the back office
- Widget captions surface now in the topic pages
Check any of the topic pages.

Topic pages tasks

---

components/datasets/form/DatasetsForm.js
components/datasets/form/steps/Step1.js
components/form/Validator.js

General subscription issues,
1. Undefined subscription types, now we save the values correctly 
- now we use `.filter` instead of `.splice` for remove subscription. Otherwise it will return undefined as the index is cashed from before. 
2. Remove subscriptions now work 
3. Preview queries rendered all fields when clicking on preview, now we only render the selected one.
4. Add unique validation rule, we want the subscription types to be unique.  
go to `http://localhost:9000/admin/data/datasets/{id}` and edit subscriptions 
then go to: `http://localhost:9000/myrw/areas` and make sure your changes are working as expected
https://www.pivotaltracker.com/story/show/155938214

Subsrciption issues

---

components/admin/widgets/form/steps/Step1.js
css/components/map/map-controls.scss
layout/explore/explore-embed-component.js
layout/head/app.js
pages/app/embed/EmbedEmbed.js

This PR adds support for widgets of type `embed`
You can check it [here](http://localhost:3000/admin/data/widgets/8f50acdb-3550-4986-a538-03bf18bc18e6/edit) and [here](http://localhost:3000/embed/embed/8f50acdb-3550-4986-a538-03bf18bc18e6)

Embed of widgets type 'embed'

---

pages/app/explore/index.js

This PR fix the bug related to save the url in the explore page

Explore: fix url bug

---

components/modal/SaveWidgetModal.js

Widget Editor --> Title and caption inputted into the editor copy over to the save widget dialog

---

layout/explore-detail/explore-detail-widget-editor/explore-detail-widget-editor-component.js

This PR adds the vega chart to explore detail
https://www.pivotaltracker.com/story/show/155220889

Explore detail: mobile vega chart

---

components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-component.js
components/datasets/list/list-item/actions.js
components/datasets/list/list-item/component.js
components/datasets/search/search-component.js
css/components/datasets/search.scss
css/components/form/checkbox.scss
css/components/ui/tag.scss
layout/explore-detail/explore-detail-actions.js
layout/explore/explore-actions.js
layout/explore/explore-datasets/explore-datasets-component.js
layout/explore/explore-datasets/index.js
layout/explore/explore-default-state.js
layout/explore/explore-header/explore-header-component.js
layout/explore/explore-reducers.js
layout/head/app.js
pages/app/explore/index.js
utils/concepts.js
utils/graph/TagsUtil.js
utils/tags.js

This PR adds:
Possibility of clicking on the tags tooltip and toggle custom filters to the search

Explore tag selected

---

css/components/app/pulse/layer_menu_dropdown.scss

Closes https://www.pivotaltracker.com/story/show/155248690

Planet Pulse:  Fix dropdown box shadow

---

layout/catalog/actions.js
layout/catalog/component.js
layout/catalog/default-state.js
layout/catalog/index.js
layout/catalog/reducers.js
pages/app/catalog/index.js

This PR adds:
- Server rendering
- Improve code
Got to the catalog page
https://www.pivotaltracker.com/story/show/156434726
https://www.pivotaltracker.com/story/show/156434790
Suggestions:
- Apply filters from Explore
- Sort by name as soon as the API provides us the way to do it

Catalog: server rendering

---

utils/layers/pulse_layers.js

Layer updates for PP. Still contains placeholders for raster layers.

WIP: new pulse layers and descriptions

---

css/components/modal/newsletter_modal.scss
pages/app/MyRW.js

Changes the title in the users myRW page if no username is found from `Hi!` to `My Resource Watch`

change Hi! to My Resource Watch in user profile

---

index.js

Task: https://www.pivotaltracker.com/story/show/153181886
Add `origin=rw` to auth login url to show RW logo and branding to user

add rw origin to auth login url

---

components/vis/globe-cesium/actions.js
components/vis/globe-cesium/component.js
components/vis/globe-cesium/index.js
components/vis/globe-cesium/initial-state.js
components/vis/globe-cesium/reducers.js
css/components/app/pulse/layer_card.scss
layout/pulse/component.js
layout/pulse/layer-card/component.js
layout/pulse/layer-card/index.js
layout/pulse/layer-menu/actions.js
layout/pulse/layer-menu/component.js
utils/layers/pulse_layers.js

Planet pulse: specific initial position for each layer plus rotate globe functionality

---

css/components/app/pages/pulse.scss
css/components/app/pulse/layer_card.scss
css/components/app/pulse/layer_menu.scss

Pulse --> fix z-index values

---

css/components/app/pulse/layer_card.scss
layout/pulse/layer-card/component.js
utils/layers/pulse_layers.js

Should be final pulse layers. 
Whole layer card scrolls rather than small windows.
Issues:
- Image collection layers don't load in Pulse, including drought, arctic sea ice etc. (note: the 'crop and vegetation health' will not load because it doesn't yet have a layer config, but the ID is correct.)

Pulse layer updates and minor layer card style updates

---

layout/explore/explore-actions.js

This PR adds:
- search result filtered by !isBlack && !isGeography && hasDatasets

Explore: search dataset filtered

---

services/DatasetsService.js
services/LayersService.js
services/WidgetsService.js
services/favourites-service.js

This will disable cache in admin and MyRW.

added header to disable cache in manager and myrw

---

css/components/dashboards/dashboard-card.scss
css/components/map/map-popup.scss
layout/explore/explore-map/explore-map-component.js
pages/app/embed/EmbedMap.js

- disable scroll on map embed (topic pages) (embed maps)
- min height on embed widget (topic pages)
- max height on map tooltip (map)
https://www.pivotaltracker.com/story/show/156556703

Bug fixes and improvements for map embeds and tooltips

---

utils/layers/pulse_layers.js

Added focus on North pole

---

utils/layers/pulse_layers.js

Pulse layer copy edit and layer+basemap swaps.

More pulse layer updates :D

---

components/splash/layout/Header.js
components/vis/globe-cesium/component.js
pages/app/Splash.js
pages/app/SplashDetail.js

Update Pulse + Splash default basemaps plus splash header fix.

Pulse + splash default basemaps

---

components/datasets/search/search-component.js
layout/explore/explore-datasets-header/explore-datasets-header-component.js
layout/explore/explore-map/explore-map-component.js
utils/concepts.js

This PR adds:
- Enabled scroll zoom only on explore
- Current view of datasets
- Sort filters by label

Explore: fixes

---

components/admin/widgets/table/WidgetsTable.js
pages/app/Splash.js

Changes to Splash initial animation

---

components/ui/map/Map.js

This PR adds:
- Map widgets fit bounds correctly
https://www.pivotaltracker.com/story/show/156595647

Widget: fit bounds after set view

---

components/areas/AlertWidget.js

Hide data table, until we have the data available

hide data table for now (subscriptions)

---

components/blog/latest-posts/actions.js
components/blog/latest-posts/component.js
components/blog/latest-posts/default-state.js
components/blog/latest-posts/index.js
components/blog/latest-posts/reducers.js

This PR fixes:
- Home blog posts
https://www.pivotaltracker.com/story/show/156642319

Home: blog posts fixed

---

pages/app/embed/EmbedDataset.js
pages/app/embed/EmbedEmbed.js
pages/app/embed/EmbedMap.js
pages/app/embed/EmbedSimilarDatasets.js
pages/app/embed/EmbedTable.js
pages/app/embed/EmbedText.js
pages/app/embed/EmbedWidget.js
pages/app/embed/map-swipe/index.js
static/insights/map-as-wildfires-burn-nearby-air-quality-suffers-in-california.html
utils/splash/Panoramas.js

Make sure we dont link to staging, and update any regex containing hardcoded staging link
https://www.pivotaltracker.com/story/show/156645134

change any reference that goes to staging

---

components/app/myrw/areas/pages/alerts.js
components/areas/AreaCard.js
components/subscriptions/SubscriptionSelector.js
pages/app/MyRWDetail.js
utils/layers/LayerManager.js

use dataset *meta title*, not *dataset.label*
Fix setOpacity issue on undefined methods in layerMannager
bonus, some minor linting
https://www.pivotaltracker.com/story/show/156643527

Subscription issues

---

css/layouts/_sidebar.scss
package.json
yarn.lock

This PR upgrade the redux-tool version. Compatible with IE
`yarn`
https://www.pivotaltracker.com/story/show/156624052

Redux tools: updated

---

pages/app/explore/index.js

This PR resets the state of the explore page whenever you leave the page

Explore: reset store if you unmount the page

---

components/admin/layers/form/LayersForm.js
components/areas/AlertWidget.js
utils/datasets/dataset-helpers.js

Fix layers undefined issues and trying to grab metadata that does not exist yet.

Opbeat issues

---

components/app/myrw/widgets/pages/edit.js
services/DashboardsService.js
services/DatasetService.js
services/DatasetsService.js
services/UserService.js
services/WidgetService.js
services/WidgetsService.js
services/collections-service.js

This PR removes cache from all the calls inside the profile

Profile: remove cache from all get calls

---

services/UserService.js

If we dont have `common` available on store, default subscription lang to english.

add default english if state not present for lang

---

css/components/app/pages/home.scss
css/layouts/_container.scss
layout/header/header-default-state.js
layout/header/header-menu-mobile/component.js
layout/header/header-menu-mobile/index.js
layout/header/header-menu/component.js
layout/header/header-menu/index.js
layout/header/header-user/component.js

This PR adds:
- The possibility of log in in the mobile header
- The possibility of log out in the mobile header
https://www.pivotaltracker.com/story/show/156738443

Mobile: login through header

---

css/components/app/pulse/layer_card.scss

https://www.pivotaltracker.com/story/show/156723994

Planet pulse: layerd card

---

pages/_error.js

Log to GA the url requested when reaching a 404 page

---

components/admin/layers/form/interactions/interactions-actions.js
components/ui/map/MapPopup.js
services/LayersService.js

This PR fixes the interactivity behavior inside the layer form. We should check that everything works
https://www.pivotaltracker.com/story/show/156876020

Map: interactivity fixed

---

components/datasets/list/list-item/component.js
layout/explore/explore-datasets/explore-datasets-actions/component.js

Using slug instead ID to show and access to dataset detail page.

accesing to dataset page using slug instead id

---

utils/layers/pulse_layers.js

New layer ID from moving nighttime imagery layer into separate dataset.
Check that layer loads in pulse

Update nighttime imagery layer id

---

components/ui/map/constants.js

Updated labels and boundaries url for map.

updated labels and boundaries url

---

components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-card-component.js

MyRW --> Favorited dataset cards link problem

---

components/app/myrw/widgets/my-rw-widgets/index.js

This PR fixes a little bug related to my-widget. A call to retrieve collection widgets was made even if you are not on the page.
https://www.pivotaltracker.com/story/show/157044828

MYRW: fix bug

---

components/areas/AlertWidget.js
layout/explore/explore-component.js

Show warning for Explore mobile version

---

components/vis/globe-cesium/component.js
components/vis/globe-cesium/index.js
layout/pulse/labels-pill/actions.js
layout/pulse/labels-pill/component.js
layout/pulse/labels-pill/index.js
layout/pulse/labels-pill/initial-state.js
layout/pulse/labels-pill/reducer.js
layout/pulse/layer-menu/actions.js
layout/pulse/layer-pill/index.js
store.js
utils/layers/pulse_layers.js

Planet Pulse --> Labels overlay added

---

components/topics/thumbnail-list/index.js
components/ui/CompoundMenu.js
layout/footer/footer-component.js
layout/footer/index.js
layout/header/header-actions.js
layout/header/header-reducers.js
layout/page/index.js
redactions/admin/widgets.js
redactions/topics/actions.js
redactions/topics/index.js
redactions/topics/initial-state.js
redactions/topics/reducers.js
store.js

This PR 
- fetchs topics from API. It does it on the server side, son we can use the topics list whenever we want.
- use header items to display the footer. So we only have `one ring to rule them all`.
https://www.pivotaltracker.com/story/show/156573009

Header && Footer: fetch published topics from api

---

components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-component.js
components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/index.js
components/app/myrw/widgets/my-rw-widgets/index.js

https://www.pivotaltracker.com/story/show/157044828

MyRW: prevent unnecessary api calls

---

components/ui/map/Map.js
components/ui/map/MapPopup.js

This PR adds again the popup to maps

Map: popup fixed

---

Dockerfile
Jenkinsfile

As soon as we deploy to develop, we will have the correct staging variable
https://www.pivotaltracker.com/story/show/157422483

WRI_API_URL: staging

---

components/collections-panel/collections-panel-component.js
components/collections-panel/collections-panel-item/collections-panel-item-component.js
components/wysiwyg/widget-block-edition/widget-block-edition-actions.js
components/wysiwyg/widget-block-edition/widget-block-edition-component.js
components/wysiwyg/widget-block-edition/widget-block-edition.js
css/components/collections/collections-panel.scss
css/index.scss

This PR:
- Adds new tab `favorites` to topic and dashboard widget edition
- It also adds a HOTFIX: users can't save favorites in PRO!!!!
https://www.pivotaltracker.com/story/show/156602863

Dashboard widget edition add favourites

---

package.json
yarn.lock

Upgrade the widget editor version

---

pages/app/explore-detail/index.js
routes.js

Fix for Powerwatch dataset url

---

components/app/common/Browser.js
components/ui/Modal.js
css/components/ui/browser.scss
css/index.scss
layout/layout/layout-app/layout-app-component.js
pages/app/Home.js
utils/browser.js

We dont support internet explorer, add popup message telling them to update their browser.
We should still support **edge** see no reason to exclude it. 
if on mac, update your **network conditions** within dev tools, and set user agent to internet explorer. 
https://www.pivotaltracker.com/story/show/156102650

add popup if user is on IE to update their browser

---

components/app/myrw/widgets/pages/edit.js
css/components/admin/widget/form.scss

https://www.pivotaltracker.com/story/show/157418613

Bug fixes 

---

components/app/myrw/widgets/my-rw-widgets/my-rw-widgets-component.js
components/areas/AreaActionsTooltip.js
components/ui/SearchInput.js
components/ui/Tabs.js
components/widgets/list/WidgetActionsTooltip.js
css/_base.scss
css/components/app/pages/home.scss
pages/app/MyRW.js

https://www.pivotaltracker.com/story/show/155221014

hide specified menu items on mobile @profile

---

package.json
yarn.lock

https://www.pivotaltracker.com/story/show/156551248

update wri components

---

components/app/myrw/widgets/pages/edit.js
services/WidgetService.js

https://www.pivotaltracker.com/story/show/157039831
Now user can save caption in the metadata
Moved title to the widget editor, this is so we keep it consistent with the other widget editor locations.

Feat / enable user metadata save/patch (widgets)

---

components/dashboards/form/DashboardsForm.js
components/dashboards/form/steps/Step1.js

This PR:
- Fix the form when no image is added
- Allow users to remove images that were already added
https://www.pivotaltracker.com/story/show/158320035

Dashboards: fix image behaviour

---

package.json
yarn.lock

https://www.pivotaltracker.com/story/show/158365637

upgrade wri api components to latest

---

package.json
yarn.lock

Widget editor upgraded to v.1.3.1

update widget editor version

---

components/vis/globe-cesium/component.js
utils/layers/pulse_layers.js

Pulse basemaps updated

---

services/DatasetService.js
services/FaqsService.js
services/GraphService.js
services/PagesService.js
services/PartnersService.js
services/RasterService.js
services/ToolsService.js
services/TopicsService.js
services/UserService.js
services/WidgetService.js
services/favourites-service.js

https://www.pivotaltracker.com/story/show/159333031

add UIR header on all get requests

---

css/components/ui/modal.scss
css/components/ui/modal2.scss

https://www.pivotaltracker.com/story/show/159000299

remove horizontal scroll for modals

---

components/admin/widgets/form/WidgetsForm.js
components/admin/widgets/form/steps/Step1.js
services/WidgetsService.js

https://www.pivotaltracker.com/story/show/159497425
@rrequero @aagm Let me know if this feature is enabled in the **API** if so please approve this PR and I will merge :)

Allow users to unfreeze widgets in admin

---

package.json

Reverts resource-watch/resource-watch#802

Revert "Upgrade widget editor to 1.3.6"

---

pages/app/Home.js

Homepage fix: develop your app wrong link

---

pages/app/ContactUs.js

Corey is our new comms coordinator: corey.filiault@wri.org

Rose -> Corey

---

components/app/myrw/areas/pages/alerts.js
components/areas/AlertWidget.js
components/areas/AreaCard.js

https://www.pivotaltracker.com/story/show/159926412
question, is zoom to fit the layer data default? seems like a thing I should not have to touch right @mbarrenechea  
atm I just default the zoom to 0.
Also, we should probably remove the map component inside RW at this point?

use wri-api-comp map on alerts also

---

css/_settings.scss
css/components/ui/header-dropdown.scss
layout/header/header-user/component.js

Adds MyRW menu to user header menu. Also removes some `eslint` warnings in this component.
Log-in and hover your avatar in the header.
https://www.pivotaltracker.com/story/show/160448847
---

Adds MyRW menu to user header menu

---

layout/explore/explore-map/explore-map-component.js
package.json
yarn.lock

Brings back timeline in map legend.
Add a layer with timeline in the map, like: http://localhost:9000/data/explore?zoom=2&lat=40.19146303804063&lng=-43.86566162109375&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%25228671f536-1979-4b6f-a147-70152fcb44ed%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522562795be-8713-4cc9-acf6-5925f0cbff08%2522%257D%252C%257B%2522dataset%2522%253A%2522b8307c16-fd77-4e35-9b68-8726a025f401%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522f66acc52-455b-44d9-ad48-d10a301a0f4f%2522%257D%255D&page=1&sort=relevance&sortDirection=-1&search=birth
https://www.pivotaltracker.com/story/show/160611343
---
[ ] …

Brings back timeline

---

layout/explore/explore-actions.js

Fix issue with preproduction data not showing in the preproduction site (Explore)

---

layout/explore/explore-datasets-header/explore-datasets-header-component.js
layout/explore/explore-datasets-header/explore-datasets-mode/explore-datasets-mode-component.js
layout/explore/explore-datasets-header/explore-datasets-sort/explore-datasets-sort-component.js
layout/explore/explore-datasets-header/index.js
package.json
yarn.lock

Go to Explore page, datasets section and check counter.
https://www.pivotaltracker.com/story/show/160884730

Fixes explore dataset counter

---

layout/header/header-topics/component.js
layout/header/header-topics/index.js
layout/header/header-topics/selectors.js
layout/page/index.js

Fixes topics displayed in header menu
Hover `topics` entry in app menu.
https://www.pivotaltracker.com/story/show/161046700

Fixes topics displayed in header menu

---

components/dashboards/detail/dashboard-detail-component.js
components/dashboards/detail/dashboard-detail.js
pages/app/dashboards-detail/component.js
pages/app/dashboards-detail/index.js
pages/app/dashboards-detail/selectors.js
routes.js

Displays summary and description of a dashboard in dashboard detail page.
Go to `http://localhost:9000/data/dashboards/89`
https://www.pivotaltracker.com/story/show/161017390

Displays summary and descriptio in dashboard detail page

---

components/datasets/list/index.js
components/datasets/list/list-item/component.js
components/datasets/list/selectors.js
layout/explore-detail/explore-detail-header/explore-detail-header-component.js
layout/explore-detail/explore-detail-header/index.js
layout/explore-detail/explore-detail-header/selectors.js
layout/explore/explore-datasets/index.js
layout/explore/explore-datasets/selectors.js
layout/page/index.js
package.json
pages/app/explore-detail/index.js
pages/app/explore/index.js
redactions/common.js
utils/utils.js

Add dataset last update date to Explore and Explore detail pages

---

css/components/app/pulse/layer_card.scss
layout/pulse/layer-card/component.js
layout/pulse/layer-card/index.js
layout/pulse/layer-card/selectors.js
pages/app/pulse/index.js

The last update date has been added to the legend component in Planet Pulse
Check data sets such as fires or Air quality in the Planet Pulse page.

Data last update date added to Planet Pulse

---

components/admin/layers/form/steps/Step1.js

Back office: Allow users to update the interactionConfig object in GEE layers

---

layout/explore-detail/explore-detail-component.js
layout/explore-detail/explore-detail-info/explore-detail-info-component.js
package.json
pages/app/dashboards-detail/component.js
yarn.lock

Adds markdown support to some fields.
https://www.pivotaltracker.com/story/show/161268384

Adds markdown to some fields

---

components/datasets/list/list-item/component.js
layout/explore-detail/explore-detail-header/explore-detail-header-component.js
layout/pulse/layer-card/component.js

dataset dates hidden until update process is fixed

---

css/components/ui/paginator.scss
css/layouts/_sidebar.scss
layout/explore/explore-sidebar/explore-sidebar-component.js

No margin below pagination in firefox
Go to explore datasets and scroll down to the bottom.
https://www.pivotaltracker.com/story/show/161503219
---

swapped padding for margin

---

components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-component.js
components/app/myrw/widgets/my-rw-widgets/my-rw-widgets-component.js
pages/app/MyRW.js

Fixing the wrong alignment of added buttons. Separator and button (Discover Datasets) have to be aligned with the content section no main page.
Go to My Resource Watch section and click in each button of section nav
https://www.pivotaltracker.com/story/show/161949908
---

fixing wrong alignment

---

css/layouts/_log-in.scss
layout/forgot-password/component.js
layout/forgot-password/constants.js
layout/forgot-password/index.js
layout/log-in/component.js
layout/reset-password/component.js
layout/reset-password/constants.js
layout/reset-password/index.js
pages/app/forgot-password/index.js
pages/app/reset-password/index.js
routes.js
services/UserService.js

Adds pages and process for user recovery password
Go to `/sign-in`, click on the forgotten password link and follow steps.
https://www.pivotaltracker.com/story/show/161953310

Recovery password

---

components/admin/layers/form/layer-preview/layer-preview-component.js
components/areas/AlertWidget.js
components/widgets/list/WidgetCard.js
components/wysiwyg/widget-block/widget-block-component.js
layout/embed/map-swipe/component.js
layout/explore/explore-map/explore-map-component.js
package.json
pages/app/embed/EmbedMap.js
yarn.lock

Changes a little the map implementation in order to make the `layer-manager` work again with latest version.
Also, fixes the issue where leaflet's tileLayer layer didn't have interactivity implemented.

Makes the app compatible with latest layer-manager version

---

components/admin/layers/form/layer-preview/layer-preview-component.js
layout/explore/explore-actions.js
layout/explore/explore-default-state.js
layout/explore/explore-map/explore-map-component.js
layout/explore/explore-map/explore-map-selectors.js
layout/explore/explore-map/index.js
layout/explore/explore-reducers.js
package.json
yarn.lock

Adds support for canvas layer and timestep
This PR relies on:
- https://github.com/Vizzuality/layer-manager/pull/30
- https://github.com/resource-watch/wri-api-components/pull/42
I think the PR needs some polishment, but it's a good beginning.
Look up "tree cover loss" in the dataset search, go to the last page and click on the last dataset.
You will see a timestep in the legend, click on the play button to reproduce.

Adds support for canvas layer and timestep

---

Dockerfile
Jenkinsfile

This PR adds:
- ARG for control tower inside Jenkins file

Control tower url

---

components/admin/partners/form/constants.js
pages/app/partners/component.js
pages/app/partners/index.js
pages/app/partners/selectors.js
routes.js

- Adds "anchor funder" category to back-office.
- Adds a new section in `about/partners`.
https://www.pivotaltracker.com/story/show/162408863

Adds anchor funders section and category

---

layout/footer/footer-default-state.js
layout/header-admin/header-admin-user/header-admin-user-component.js
layout/header/header-default-state.js
layout/header/header-user/component.js
pages/app/MyRW.js

Makes "Visualizations" default tab of MYRW.
https://www.pivotaltracker.com/story/show/162409257
---

Makes visualization as default tab in MYRW

---

layout/sign-in/component.js

Adds a loader on click "register" button to avoid the user to click on it several times (and perform several requests).

Adds loader during register process

---

components/modal/newsletter-modal/component.js

Fixing typo in the newsletter signup modal identified by user

fix-newsletter-modal-text

---

layout/explore/explore-default-state.js
layout/layout/layout-app/layout-app-component.js

Updates sorting value

---

index.js

Redirects all urls to the login page.
Go to `/admin` without being logged.
**Blocked reason**: approval.

Redirects to new login page going to /admin

---

components/ui/map/controls/SearchControl.js
layout/head/app.js

fixed bug in location search,  searchControl component coordinates readjusted according to api
Go to data/explore datasets click on search icon in the map to zoom into  an specific location
https://www.pivotaltracker.com/story/show/162727491
---

location bug fixed in SearchControl component

---

layout/explore/explore-actions.js
layout/explore/explore-component.js
layout/explore/explore-map/explore-map-component.js
layout/explore/explore-map/explore-map-selectors.js
layout/explore/explore-reducers.js
package.json
utils/data.js
utils/dates.js
utils/layers/params-parser.js
yarn.lock

Adds more canvas layer

---

components/dashboards/detail/dashboard-detail-actions.js
components/dashboards/form/steps/step-1/component.js
components/dashboards/thumbnail-list/dashboard-thumbnail-list-actions.js
components/tools/related-tools/actions.js
components/topics/form/steps/Step1.js
components/topics/thumbnail-list/actions.js
layout/explore-detail/explore-detail-actions.js
layout/footer/footer-actions.js
layout/get-involved-detail/get-involved-detail-actions.js
layout/get-involved/get-involved-actions.js
layout/page/index.js
layout/topics-detail/topics-detail-actions.js
next.config.js
package.json
redactions/insights.js
redactions/partnerDetail.js
redactions/partners.js
redactions/static_pages.js
selectors/admin/topics.js
services/ContactUsService.js
services/DashboardsService.js
services/FaqsService.js
services/PagesService.js
services/PartnersService.js
services/ToolsService.js
services/UserService.js
store.js
yarn.lock

This PR overrides all old `API_URL`=> `WRI_API_URL`
Please test itby changing your `.env` `WRI_API_URL` => `http://staging-api.globalforestwatch.org/v1`

API migration, DO NOT MERGE!!!

---

components/datasets/similar-datasets/similar-datasets-actions.js
components/datasets/similar-datasets/similar-datasets-component.js
components/topics/thumbnail-list/component.js
layout/topics-detail/topics-detail-component.js
services/PagesService.js

API migration. Overrides old API_URL=> WRI_API_URL
Please test it by changing your .env WRI_API_URL => http://staging-api.globalforestwatch.org/v1
---

updated API URL in similar datasets and topics detail

---

components/dashboards/template-selector/component.js
components/dashboards/template-selector/constants.js
components/dashboards/template-selector/import-selector/component.js

Minor changes to text from the Dashboard form

Dashboard form text changes

---

layout/sign-in/component.js

toastr.error added when user introduce wrong credentials
Go to login and introduce wrong email and or password
https://www.pivotaltracker.com/story/show/163559865
---

error message added when credentials are incorrect

---

layout/explore-detail/explore-detail-component.js
layout/explore-detail/index.js
layout/explore-detail/selectors.js
layout/head/app.js
layout/layout/layout-app/layout-app-component.js

Adds widget thumbnail to explore-detail page
Share any `/data/explore/{dataset-id}` page.
https://www.pivotaltracker.com/story/show/156724508
---

Adds widget thumbnail to explore-detail page

---

layout/layout/layout-app/layout-app-component.js

Removes stray symbol

---

components/admin/layers/form/layer-preview/layer-preview-component.js
components/areas/AlertWidget.js
components/wysiwyg/widget-block/widget-block-component.js
layout/embed/map-swipe/component.js

Fixes: https://www.pivotaltracker.com/story/show/163714564
Updates layer-manager implementation. Latest version included a breaking change.
Go to `http://localhost:9000/data/dashboards/land-use-and-land-cover-change` and check maps.
https://www.pivotaltracker.com/story/show/163714564
---

Fixes layer manager implementation

---

components/dashboards/form/steps/step-1/component.js
pages/admin/DashboardsDetail.js

Fixes: https://www.pivotaltracker.com/story/show/163728158
Clone a dashboard and check the preview content.
https://www.pivotaltracker.com/story/show/163728158
---

Fixes dashboard content in WYSIWYG

---

layout/explore/explore-map/explore-map-component.js
package.json
yarn.lock

Restore timeline legend
http://localhost:9000/data/explore?zoom=3&lat=0&lng=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522c0c71e67-0088-4d69-b375-85297f79ee75%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522e6ddf90a-c822-46bf-8e02-de86d7bdf5d0%2522%257D%255D&page=1&sort=most-visited&sortDirection=-1&topics=%255B%2522precipitation%2522%255D
https://www.pivotaltracker.com/story/show/163759326
---

Restore timeline legend

---

css/index.scss
css/layouts/_error.scss
layout/head/error.js
package.json
pages/_error.js
pages/app/explore-detail/index.js
pages/app/topics-detail/index.js
pages/app/widget-detail/index.js
yarn.lock

App crashed when a route didn't exist or res status codes weren't managed properly.
http://localhost:9000/data/explore/5159fe6f-defd-44d2-9e7d-15665e14deeb
https://www.pivotaltracker.com/story/show/164166614
~~https://github.com/Vizzuality/layer-manager/pull/50~~
---

Sets error page properly

---

pages/app/Home.js

Quick fix to make home page "join the community" link

Fixing the Join the Community link on the homepage

---

layout/explore/explore-map/explore-map-component.js

This PR disables mouse scroll in embed explore maps
Go to `/embed/data/explore`

Explore: embed scroll disabled

---

components/widgets/list/WidgetCard.js
services/LayersService.js
services/TopicsService.js

Fixes passing wrong param to fetch layer
Go to `http://localhost:9000/data/widget/ef6ea89e-0a8c-466d-8197-e294985f3e43`, it should load insteaf of crashing.
–
---

Fixes passing wrong param to fetch layer

---

layout/head/app/component.js
layout/widget-detail/widget-detail-component.js

thumbnailUrl added to widget-detail component.
http://localhost:9000/data/widget/771b8762-353b-4738-8734-e34b551f7754.
https://www.pivotaltracker.com/story/show/165209233.
---

thumbnailUrl added to widget-detail component

---

layout/head/admin.js
layout/head/app/component.js
layout/layout/layout-admin/layout-admin-component.js
pages/_app.js
pages/_document.js

Fixes an issue where Leaflet override custom styles.
Check pop-up map.
-
---

Fixes leaflet styles override

---

components/admin/data/layers/form/LayersForm.js

Fixes an error preventing the user to save/update a layer in the admin.
Go to [http://localhost:9000/admin/data/layers/b9c87986-91dd-45e7-a0cd-009915cb0017/edit](http://localhost:9000/admin/data/layers/b9c87986-91dd-45e7-a0cd-009915cb0017/edit) (with production variables) and hit `save` button. It should trigger a success notification.
---

Fixes error preventing save a layer in admin

---

layout/app/widget-detail/component.js
layout/explore-detail/explore-detail-component.js
layout/explore/explore-component.js
layout/explore/explore-embed-component.js
layout/layout/layout-app/component.js
layout/topics-detail/component.js

Removes unused category prop from head app
–
–
---

Removes unused category prop from head app

---

README.md
next.config.js
package.json
yarn.lock

Adds bundle analyzer.
Read the README's Optimization section.
–
---

Adds bundle analyzer

---

package.json
yarn.lock

Removes dependencies not used in the project.
`rm -rf node_modules && yarn`
–
---

Dependency cleanup

---

README.md

Fixing dead link in readme file

patch link for JSDocs in readme

---

components/admin/data/layers/table/component.js
components/admin/data/layers/table/index.js
components/admin/data/layers/table/td/owner/component.js
components/admin/data/widgets/table/component.js
components/admin/data/widgets/table/td/owner/component.js
components/datasets/table/component.js
components/datasets/table/index.js
components/datasets/table/td/owner/component.js
services/LayersService.js
services/dataset.js
services/widget.js

Fixes a bug where table didn't display the owner of the resource and sort it properly.
Go to http://localhost:9000/admin/data/{resource} and check the owner column in the tables. It should be populated (not always, some resources don't have an user 🤔 ) and perform the sorting properly.
–
---

[ADMIN] Fixes owner value in column tables

---

yarn.lock

Just removing that warning appearing when you run the server.
Run the app as usual. The message shouldn't appear anymore (and the app work as usual).
–
---

Upgrades autoprefixer

---

package.json
yarn.lock

This upgrade should fix the issue when adding visualizations to dashboards 
- https://www.pivotaltracker.com/story/show/166636457
- https://www.pivotaltracker.com/story/show/166712154

vizz-wysiwyg version upgraded to 2.1.2

---

components/widgets/list/WidgetActionsTooltip.js
components/widgets/list/WidgetCard.js
components/widgets/list/WidgetList.js
services/WidgetService.js

This PR updates MyRW so that it complies with the new design available [here](https://www.pivotaltracker.com/story/show/166955836)
Go to http://localhost:9000/myrw/widgets/my_widgets and check the widget cards

Update MyRW with new design to remove elements

---

components/app/myrw/collections/CollectionsTab.js
components/app/myrw/collections/form/CollectionsForm.js
components/app/myrw/collections/pages/edit.js
components/collections-list/related-content.js
components/collections-list/td/RelatedContentTD.js
layout/myrw/detail/component.js

This PR fixes an error that was thrown when the collections page was loaded. It was related to a unnecessary request that was performed to the dataset endpoint including erroneous parameters.
Go to http://localhost:9000/myrw/collections

Fix error thrown on Collections page load

---

components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-card-component.js
components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/index.js
components/collection-list-aside/collection-list-aside-component.js
components/collection-list-aside/index.js
components/collections-list/related-content.js

Fix issues with collections, myrw datasets tabs and collections links to datasets + widgets

---

components/modal/share-modal/share-modal-component.js

Regarding this comment: https://www.pivotaltracker.com/story/show/166956378/comments/204679857

Email share fields updated

---

components/admin/data/layers/form/LayersForm.js
components/admin/data/layers/form/layer-preview/component.js
components/admin/data/layers/form/steps/Step1.js
components/admin/data/widgets/form/component.js
components/admin/data/widgets/form/index.js
components/form/Navigation.js
css/components/admin/layer/form.scss
css/components/form/field-buttons.scss
css/components/ui/button-container.scss

Related to this comment: https://www.pivotaltracker.com/story/show/167107248/comments/204680983

Back office layer+widget form updates

---

k8s/preproduction/deployment.yaml

Adds auth to preproduction environment
Not visible until deployment
https://www.pivotaltracker.com/story/show/167423900
---

adds auth in preproduction environment

---

index.js
k8s/preproduction/deployment.yaml
k8s/staging/deployment.yaml

Simplifies auth and variables involved in auth process.
–
–
---

simplifies auth and variables involved

---

index.js
k8s/preproduction/deployment.yaml
k8s/staging/deployment.yaml

Updates key names

---

services/WidgetsService.js
services/layer.js

Related to this PT task: https://www.pivotaltracker.com/story/show/167442611

Fix issue with layers and widgets having two environments associated at once

---

services/user.js

Adds origin in reset-password token generation

---

components/app/myrw/widgets/tabs/edit.js
services/WidgetService.js
services/WidgetsService.js
services/layer.js

Fix for: "Array error when saving widget"

---

components/modal/layer-info-modal/layer-info-modal-component.js
css/components/explore-detail/explore-detail-info.scss
css/components/ui/markdown.scss
css/index.scss
layout/explore-detail/explore-detail-component.js
layout/explore-detail/explore-detail-info/explore-detail-info-component.js

Encapsulate CSS for markdown lists into a separate CSS class

---

layout/app/newsletter/component.js

This PR includes the text changes and additions requested in the BC thread referred in the corresponding PT task.
Go to http://localhost:9000/about/newsletter

Newsletter text and layout improvements

---

css/components/app/pages/newsletter.scss
layout/app/newsletter/component.js

Newsletter styles fix: reposition the sign-up button

---

components/areas/AreaCard.js
components/modal/subscriptions-modal/subscriptions-preview/table/component.js
components/modal/subscriptions-modal/subscriptions-preview/table/styles.scss
css/_settings.scss

This PR adds a disclaimer text to the preview subscription table.
Go to MyRW --> Areas of interest. Then, in the process of creating a new subscription, click on the button 'Preview'

Alert preview improvements

---

components/admin/data/layers/form/interactions/actions.js
components/admin/data/layers/form/interactions/component.js
components/admin/data/layers/form/layer-preview/component.js
components/admin/data/layers/form/steps/Step1.js

Provides a fix for layers without `interactionConfig` by default.
–
https://www.pivotaltracker.com/story/show/167250786
---

Fixes edge case for layer interactions

---

components/map/layer-manager/component.js
components/map/popup/component.js
components/map/popup/index.js
components/map/popup/styles.scss
css/components/map/map-popup.scss
css/mapbox.scss
layout/explore/explore-datasets/explore-datasets-actions/component.js
layout/explore/explore-map/explore-map-component.js
layout/explore/explore-map/explore-map-selectors.js
layout/explore/explore-map/index.js
layout/explore/explore-reducers.js

Adds interactivity to layers.
Use `production` env. Add some layers and check data of them.
–
---

Mapbox: layer interactivity

---

layout/explore/component.js
layout/explore/embed.js
layout/explore/explore-embed-component.js
layout/explore/initial-state.js
pages/app/explore/embed.js
pages/app/explore/index.js

[Mapbox]: Sets and gets url params

---

components/map/layer-manager/component.js
css/_settings.scss
layout/explore/actions.js
layout/explore/explore-map/component.js
layout/explore/explore-map/constants.js
layout/explore/explore-map/index.js
layout/explore/explore-map/selectors.js
layout/explore/explore-map/styles.scss
package.json
utils/layers/canvas-decoders.js
utils/layers/params-parser.js

http://localhost:9000/data/explore?zoom=3&lat=0&lng=0&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522f4d44e54-1562-4190-8f09-73234c31cde1%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522dd9ba117-4465-486b-9a28-673ad2a96477%2522%257D%255D&page=1&sort=relevance&sortDirection=-1&search=tree%20cover%20loss <- Tree Cover Loss layer displaying timeline
---

[Mapbox]: Legend

---

components/admin/data/layers/form/steps/Step1.js

Fix placeholder and improve text of Environment field in Layer form

---

.env.sample
k8s/mapbox/deployment.yaml
layout/explore/explore-map/component.js
next.config.js

Adds MAPBOX_API_TOKEN env variable

---

package.json
yarn.lock

This PR fixes [this issue](https://www.pivotaltracker.com/story/show/168017068)

Upgrade widget editor to 1.4.5

---

components/widgets/list/WidgetCard.js

Related to this two PT tasks:
- https://www.pivotaltracker.com/n/projects/2154258/stories/168222426
- https://www.pivotaltracker.com/story/show/168017056

Fix related to the widget editor and how we infer is a widget is of type map or not

---

components/datasets/form/DatasetsForm.js

This PR fixes the issue mentioned in this PT task comment: https://www.pivotaltracker.com/story/show/166815177/comments/206400636

Fix error thrown when saving edit dataset page

---

components/widgets/list/WidgetCard.js

See the following PT task comment for more info: https://www.pivotaltracker.com/story/show/167509722/comments/206639545

Edit button link logic fixed

---

.eslintrc.json
package.json
yarn.lock

Adds `react-hooks` to lint React's hooks.
Adds `lint-staged`: it won't allow committing anything **you changed** that doesn't satisfy the linter.
Run `yarn` to install dev dependencies. Reset code editor just in case. You should be able to see some warning in hooks from now on.
Regarding `lint-staged`: try to make a commit, it will run a process. If everything is OK, it will proceed as usual, otherwise, it will trigger the things you need to change.
---

Hooks linter & Staged lint

---

layout/app/newsletter-thank-you/component.js

small patch to edit sentence on newsletter ty page

---

components/areas/AreaCard.js
components/modal/subscriptions-modal/actions.js
redactions/user.js
services/geostore.js
services/subscriptions.js
utils/layers/LayerManager.js
utils/user/areas.js

Displays bounds and styles in area cards map again.
Go to your areas, you should be able to see the bounds and styles properly.
https://www.pivotaltracker.com/story/show/168471054
---

Fixes bounds and styles in area cards

---

components/app/myrw/dashboards/DashboardsTab.js
components/areas/AreaCard.js
components/dashboards/form/DashboardsForm.js
components/dashboards/list/DashboardsList.js
components/modal/subscriptions-modal/actions.js
components/modal/subscriptions-modal/area/component.js
components/modal/subscriptions-modal/area/index.js
components/modal/subscriptions-modal/dataset-manager/component.js
redactions/user.js
selectors/admin/dashboards.js
services/dashboard.js
services/geostore.js
services/subscriptions.js
services/topics.js
utils/layers/LayerManager.js
utils/user/areas.js

This PR addresses the following problems:
1. Issue allowing users to create "empty" subscriptions
2. Problems when creating/updating subscriptions
3. Wrong text shown in Update/Subscribe button
4. Error thrown when clicking on `Preview`
5. Issue causing the threshold input not to reflect the changes made to it.
6. Areas not showing up in the area cards from the AOI section in MyRW
Go to `http://localhost:9000/myrw/areas` and try both creating and updating subscriptions.
- https://www.pivotaltracker.com/story/show/168669186
- https://www.pivotaltracker.com/story/show/168404799
- https://www.pivotaltracker.com/story/show/168471054
- https://www.pivotaltracker.com/story/show/168598484

Subscriptions fixes

---

components/areas/AreasForm.js

This PR fixes the issue with the "edit area" option
Go to http://localhost:9000/myrw-detail/areas and click on `Edit area` in one of the area cards.

Fix area update and fields displayed in form

---

components/areas/AreasForm.js

This PR fixes the existing issues as part of the area creation process
Go to http://localhost:9000/myrw/areas? and try creating areas using the following options:
1. Select an country from the drop down
2. Draw your own area
3. Upload a geojson file

Fix area creation

---

modules/topics/actions.js

Related to this PT task: https://www.pivotaltracker.com/story/show/168783694

Fix for content shown in the topics tooltip from the navigation bar

---

components/app/myrw/collections/form/CollectionsForm.js
components/collection-list-aside/collection-list-aside-selector.js
components/collections-list/actions/DeleteAction.js
components/collections-list/index.js
components/collections-list/related-content.js
components/collections-list/td/NameTD.js
components/collections-panel/collections-panel-component.js
components/collections-panel/collections-panel-helpers.js
components/collections-panel/collections-panel-selectors.js
redactions/user.js
selectors/myrw/collections.js
services/WidgetService.js
services/collections.js
services/favourites.js

This PR refactors the collections service adding the following improvements:
- use axios instead of promises
- better error handling
- better request logs
- serialize responses from favourites service using `WRISerializer`
Test all the features that involve collections and favourites.

Collections service refactor

---

components/app/common/ContactUs/ContactUsForm.js
services/contact-us.js

Refactor of the `contact us` service including better error handling, use of axios, and better logs.
Go to http://localhost:9000/about/contact-us 
⚠️  _it seems that the `contact us` endpoint does not exist in the staging environment at the moment_

Contact us service refactor

---

components/app/myrw/widgets/tabs/list/index.js
components/app/myrw/widgets/tabs/new.js
layout/myrw/detail/component.js

This PR fixes the issue that consisted of an erroneous widgets load when clicking on the button `New visuzalition` in MyRw --> Visualizations
Go to http://localhost:9000/myrw-detail/widgets/ and verify that all widgets are not loaded temporarily when clicking on the button `New visualization`

Fix erroneous widgets load when clicking on new visualization in MyRW

---

services/user.js

https://www.pivotaltracker.com/story/show/168861757
I didn't test this, so you may want to.

Set origin parameter when signing up user on the API

---

components/datasets/metadata/form/steps/Step1.js

See details of the bug in the following PT task: https://www.pivotaltracker.com/story/show/169470852

Fix for metadata form bug

---

components/dashboards/table/actions/DeleteAction.js
services/dashboard.js

Fix for an issue with the delete link in the dashboards table from the back office
Go to the back office section and test the deletion of all the different types of entities available.

Fix for an issue with the delete link in the dashboards table from the back office

---

components/app/common/CardStatic.js
css/components/app/pages/getInvolved.scss

This PR fixes the responsive bug on get-involved page
Go to http://localhost:9000/get-involved . Check responsive for "Develop your app" block.

Get involved page - style fix

---

layout/app/pulse/welcome-modal/component.js

Check the context for this in this [PT comment](https://www.pivotaltracker.com/story/show/169544926/comments/210031615).

Minor change to Pulse pop up text

---

components/admin/data/layers/form/LayersForm.js
services/layer.js

This PR modifies the `LayerService` so that it complies with the current approach for API services.
Go to the back office and test both the layer update and creation.

Layers service refactored to comply with new approach for services

---

layout/app/dashboards/component.js
layout/footer/selectors.js
layout/header/header-dashboards/component.js

Check the following PT comment: https://www.pivotaltracker.com/story/show/169732869/comments/210640919

Fix "More" link to point to dashboards gallery

---

layout/app/pulse/layer-menu/component.js

This PR adds opportunities to display the native menu depends on screen width.
Go to http://localhost:9000/data/pulse
Set window width < 780px to see the native menu
---

Fix planetpulse dropdown native menu showing

---

components/admin/pages/form/PagesForm.js
components/admin/pages/table/actions/DeleteAction.js
redactions/admin/pages.js
services/pages.js

This PR refactors the `pages` service to comply with the new approach for all API services.
Go to http://localhost:9000/admin/pages and check all the endpoints involved _(CRUD)_

Refactor of `pages` service to use axios

---

layout/footer/selectors.js
layout/header/header-dashboards/component.js

More info about this [here](https://www.pivotaltracker.com/story/show/169732869/comments/210938688)

Dashboards "More" links removed

---

components/admin/partners/form/PartnersForm.js
components/admin/partners/form/constants.js
components/admin/partners/form/steps/Step1.js
components/admin/partners/pages/new/component.js
components/admin/partners/pages/show/component.js
components/admin/partners/table/actions/DeleteAction.js
services/partners.js

This PR refactors the partner's service for working with axios and fix some issues in forms param names. 
Go to http://localhost:9000/admin/partners/partners
Test all actions (fetch, create, update, delete)
---

Refactor partners service for working with axios

---

components/admin/faqs/components/actions/DeleteAction.js
components/admin/faqs/form/FaqsForm.js
redactions/admin/faqs.js
selectors/admin/faqs.js
services/areas.js
services/faqs.js

This PR refactors faqs service for working with axios.
Go to http://localhost:9000/admin/faqs/faqs
Test all action (fetch, edit, create, delete)
---

Rfactor faqs service for working with axios

---

CHANGELOG.md

bump changelog header date from version 2019.0 to 2020.0 😉
---

patch typo recent changlog dates

---

components/vis/globe-cesium/component.js
components/vis/globe-cesium/selectors.js
layout/app/pulse/component.js
layout/app/pulse/layer-card/actions.js
layout/app/pulse/layer-card/component.js
layout/app/pulse/layer-menu/actions.js
layout/app/pulse/layer-pill/actions.js
layout/layout/layout-admin/layout-admin-component.js
layout/layout/layout-app/component.js
utils/layers/LayerGlobeManager.js

Use layer service in planet pulse related components

---

components/admin/data/layers/form/layer-preview/component.js

More info can be found on the PT task.
Go to https://preproduction.resourcewatch.org/admin/data/layers/2aa7754e-aebb-4c4b-a870-57ab3a791afd/edit?dataset=bf14690e-a3d8-466b-b382-04876f27caf1 and verify that there's no error thrown.

Fix issue with layer preview in back office

---

layout/explore/explore-detail/component.js
layout/explore/explore-detail/dataset-layers/component.js
layout/explore/explore-detail/dataset-layers/dataset-layer-card/component.js
layout/explore/explore-detail/dataset-layers/dataset-layer-card/index.js
layout/explore/explore-detail/dataset-layers/dataset-layer-card/selectors.js
layout/explore/explore-detail/dataset-layers/dataset-layer-card/styles.scss
layout/explore/explore-detail/dataset-layers/index.js
layout/explore/explore-detail/dataset-layers/styles.scss

This PR adds the section `Dataset layers` to Explore detail.
Try toggling different layers on and off in different scenarios such as:
- No datasets added to the map
- Other datasets have been added to the map
- Toggle on and off layers from the same dataset
- ....

Explore detail: dataset layers section

---

layout/explore/explore-topics/list/component.js
layout/explore/explore-topics/list/styles.scss

Explore: some style fixes for topic buttons

---

components/admin/data/explore-form/component.js
components/admin/data/explore-form/styles.scss
layout/explore/explore-detail/component.js
layout/explore/explore-detail/index.js
layout/explore/explore-discover/component.js

This PR includes the following updates:
- Related topics section removed from Explore form _(this is done by means of a GitHub JSON file now)_
- Extra checks in Explore detail component for published datasets that have no metadata object.
- Make sure all datasets loaded in the `Discover` section have a status of `published=true`

A few improvements and fixes

---

components/charts/widget-chart/index.js
components/map/popup/component.js
components/map/popup/styles.scss
layout/explore/explore-datasets/component.js
layout/explore/explore-datasets/list/list-item/component.js
layout/explore/explore-datasets/list/list-item/styles.scss
layout/explore/explore-datasets/styles.scss
layout/explore/explore-discover/component.js
layout/explore/explore-menu/component.js

This PR addresses several tasks at once. Check the different Pivotal Tracker links included for more information about each of them

Explore: some improvements and refinements

---

components/collections-panel/collections-panel-component.js
components/ui/read-more/component.js
components/ui/read-more/index.js
components/ui/read-more/styles.scss
layout/explore/explore-collections/styles.scss
layout/explore/explore-datasets/list/list-item/component.js
layout/explore/explore-datasets/list/list-item/index.js
layout/explore/explore-datasets/styles.scss
layout/explore/explore-detail/component.js
layout/explore/explore-detail/further-information/component.js
layout/explore/explore-detail/related-content/styles.scss
layout/explore/explore-discover/styles.scss
layout/explore/explore-login/styles.scss
layout/explore/explore-near-real-time/styles.scss
layout/explore/explore-topics/constants.js

See the various PT task links for more information.

Second batch of improvements for Explore

---

css/components/ui/button.scss
layout/explore-detail/explore-detail-header/component.js
layout/explore-detail/explore-detail-header/index.js
layout/explore/explore-datasets/component.js
layout/explore/explore-datasets/list/component.js
layout/explore/explore-datasets/list/list-item/styles.scss
layout/explore/explore-datasets/list/styles.scss
layout/explore/explore-datasets/styles.scss
layout/explore/explore-detail/dataset-layers/dataset-layer-card/component.js
layout/explore/explore-detail/dataset-layers/dataset-layer-card/styles.scss
layout/explore/explore-detail/explore-detail-buttons/styles.scss
layout/explore/explore-detail/explore-detail-footer/styles.scss
layout/explore/explore-detail/explore-detail-header/component.js
layout/explore/explore-detail/explore-detail-header/styles.scss
layout/explore/explore-discover/component.js
layout/explore/explore-discover/styles.scss
layout/explore/explore-menu/component.js
layout/explore/explore-near-real-time/component.js
layout/explore/explore-near-real-time/styles.scss

This PR addresses most of the changes requested here: https://docs.google.com/document/d/1a79NaBWiNwz6_3k98qDlXyUJRAEnR7zXmiaqGB03YmU/edit#.

Explore design refinements

---

layout/explore/component.js
layout/explore/constants.js
layout/explore/explore-datasets/list/list-item/styles.scss
layout/explore/explore-favorites/component.js
layout/explore/explore-favorites/index.js
layout/explore/explore-favorites/selectors.js
layout/explore/explore-favorites/styles.scss
layout/explore/explore-menu/component.js

This PR adds the `Favorites` section.
Verify that the favorites section surfaces the right datasets. Check the link both logged in and as an anonymous user.

Explore: Favorites section

---

package.json
yarn.lock

Reverts resource-watch/resource-watch#1294

Revert "Bump next from 9.1.2 to 9.3.2"

---

components/ui/Paginator.js
layout/explore/explore-datasets/component.js
layout/explore/explore-datasets/styles.scss
layout/explore/explore-detail/component.js
layout/explore/explore-detail/dataset-layers/dataset-layer-card/component.js
layout/explore/explore-detail/dataset-layers/dataset-layer-card/styles.scss
layout/explore/explore-detail/explore-detail-buttons/styles.scss
layout/explore/explore-detail/styles.scss
routes.js

Explore: some style refinements

---

public/static/data/ExploreConfig.json

Test update to discover tab by Emily

---

layout/explore/explore-discover/component.js

Fix for issue with link in the Discover section

---

public/static/data/ExploreConfig.json

Met with RW team members, decided to use "Start Exploring" as the section header for the launch!
Emily met with RW team members, decided to use "Start Exploring" as the section header for the launch
N/A
N/A
---

Change title to "Start Exploring"

---

layout/explore/explore-datasets/component.js
layout/explore/initial-state.js
pages/app/explore/index.js

Follow the steps specified in the PT task.

Fix the issue with the Vector map thumbnails becoming blurry sometimes

---

layout/explore/explore-login/component.js
layout/explore/explore-login/styles.scss

Explore: minor text updates to login text

---

components/ui/maintenance-banner/component.js
components/ui/maintenance-banner/helpers.js
components/ui/maintenance-banner/index.js
components/ui/maintenance-banner/styles.scss
layout/layout/layout-app/component.js

Maintenance Banner

---

layout/layout/layout-app/component.js

This PR removes the maintenance banner that is currently being shown in the production site.

Remove maintenance banner

---

constants/app.js
layout/head/app/component.js

This PR adds HotJar to the various Explore pages.

Add HotJar to Explore pages

---

components/charts/widget-chart/index.js
components/widgets/card/styles.scss
components/wysiwyg/widget-block/component.js
layout/app/dashboard-detail/component.js
layout/app/dashboard-detail/constants.js
layout/app/dashboard-detail/energy-country-explorer/component.js
layout/app/dashboard-detail/energy-country-explorer/constants.js
layout/app/dashboard-detail/energy-country-explorer/country-selector/component.js
layout/app/dashboard-detail/energy-country-explorer/country-selector/index.js
layout/app/dashboard-detail/energy-country-explorer/country-selector/styles.scss
layout/app/dashboard-detail/energy-country-explorer/custom-section/component.js
layout/app/dashboard-detail/energy-country-explorer/custom-section/index.js
layout/app/dashboard-detail/energy-country-explorer/custom-section/styles.scss
layout/app/dashboard-detail/energy-country-explorer/index.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/index.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/styles.scss
layout/app/dashboard-detail/energy-country-explorer/styles.scss
layout/app/dashboard-detail/index.js
public/static/data/CountryEnergyExplorer.json
services/config.js
services/geostore.js

GEDC PR (1)

---

layout/app/dashboard-detail/energy-country-explorer/component.js
layout/app/dashboard-detail/energy-country-explorer/constants.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/component.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/index.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/component.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/index.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/indicator-tooltip/component.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/indicator-tooltip/index.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/indicator-tooltip/styles.scss
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/ranking-bar/component.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/ranking-bar/index.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/ranking-bar/styles.scss
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/styles.scss
layout/app/dashboard-detail/energy-country-explorer/country-indicators/styles.scss
layout/app/dashboard-detail/energy-country-explorer/country-selector/component.js
layout/app/dashboard-detail/energy-country-explorer/country-selector/styles.scss
layout/app/dashboard-detail/energy-country-explorer/styles.scss

Mainly country indicators working plus World view
Go to http://localhost:9000/dashboards/energy?tab=country

GEDC: second batch of improvements

---

layout/app/dashboard-detail/energy-country-explorer/component.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/component.js
layout/app/dashboard-detail/energy-country-explorer/country-indicators/indicator-card/styles.scss
layout/app/dashboard-detail/energy-country-explorer/custom-section/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/map-menu/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/map-menu/index.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/map-menu/styles.scss
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/styles.scss

This PR adds the map section to the tool among other improvements.

GEDC: third batch of updates

---

layout/app/dashboard-detail/component.js
layout/app/dashboard-detail/energy-country-explorer/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/map-menu/component.js

Customizable header text for Power sector profiles dashboard

GEDC: customizable header text

---

layout/app/dashboard-detail/energy-country-explorer/country-selector/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/layer-info-modal/component.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/layer-info-modal/index.js
layout/app/dashboard-detail/energy-country-explorer/power-generation-map/layer-info-modal/styles.scss
layout/explore/explore-map/component.js

- Layer info modal for map
- Country search text input auto focus on open

GEDC: fourth batch of improvements

---

public/static/data/ExploreConfig.json

To match the "Start Exploring" datasets
---

Changing related topics for launch

---

components/ui/map/map-thumbnail/index.js
layout/app/dashboard-detail/component.js
pages/app/explore/index.js

Check the links to the various Pivotal Tracker tasks to see more information.
More information about how to test the fixes for the issues tackled is included in each of the Pivotal Tracker tasks linked below.
- https://www.pivotaltracker.com/n/projects/1374154/stories/172950068

A few fixes for Explore

---

layout/app/widget-detail/component.js

Fix issue with widget preview page

---

layout/app/dashboard-detail/dashboard-widget-card/component.js
layout/app/dashboard-detail/dashboard-widget-card/ranking-widget/component.js
layout/app/dashboard-detail/dashboard-widget-card/ranking-widget/index.js
layout/app/dashboard-detail/dashboard-widget-card/ranking-widget/styles.scss
layout/app/dashboard-detail/energy-country-explorer/custom-section/component.js

GEDC: ranking widget

---

layout/explore/explore-detail/explore-detail-visualization/component.js
layout/explore/explore-detail/explore-detail-visualization/error-boundary/component.js
layout/explore/explore-detail/explore-detail-visualization/error-boundary/index.js

Error boundary added to Widget Editor in Explore detail

---

layout/explore/explore-datasets/component.js

Fix for the issue described in the PT task.
See more information on the PT task.

Explore: Fix sporadic dataset navigation error

---

layout/explore/explore-detail/index.js

See the PT task for more information about the fix.

Explore detail: fix layer loaded when accessed directly from URL

---

components/dashboards/template-selector/import-dashboard-selector/component.js
services/dashboard.js

Check the PT link for more information.

Fix issue when cloning dashboards

---

services/dataset.js

Fix issue with ghost layer

---

layout/explore/explore-detail/styles.scss

Fix markdown issues regarding lists in Explore Detail

---

CHANGELOG.md
components/admin/data/widgets/form/component.js

Fixes updating widget fields. 
As `admin`, to the admin zone and try to edit a map-type widget.
https://www.pivotaltracker.com/story/show/174996497
---

fixes widget update in widget-editor

---

CHANGELOG.md
components/widgets/card/component.js

Improves error handle fetching layers in `WidgetCard` component.
–
–
---

widget card: improves error handling

---

CHANGELOG.md
layout/explore/explore-detail/explore-detail-header/styles.scss
layout/explore/explore-detail/styles.scss

fixes visual glitch with top bar in explore detail

---

CHANGELOG.md
layout/explore/explore-areas-of-interest/intro/component.jsx
layout/explore/explore-areas-of-interest/intro/styles.scss

Text tweaks for AoIs.
–
https://www.pivotaltracker.com/story/show/175788944
---

text tweaks for AoIs

---

CHANGELOG.md
components/admin/data/widgets/form/steps/index.js
components/app/myrw/widgets/tabs/edit/index.js
components/app/myrw/widgets/tabs/new/index.js
components/charts/widget-chart/index.js
components/wysiwyg/widget-block/index.jsx
layout/app/dashboard-detail/dashboard-widget-card/component.js
layout/app/dashboard-detail/dashboard-widget-card/index.js
layout/embed/dataset/index.js
layout/embed/widget/component.js
layout/embed/widget/index.js
layout/explore/explore-detail/explore-detail-visualization/index.js
utils/widget-editor.js

Memoizes `widget-editor` adapter to avoid unexpected re-renders.
https://www.pivotaltracker.com/story/show/175594527
---

memoized widget-editor adapter

---

CHANGELOG.md
components/map/utils.js
components/wysiwyg/widget-block/component.js
layout/embed/map/selectors.js

Parses `bbox` coming from `widget-editor` to display in a Mapbox map.
https://www.pivotaltracker.com/story/show/175450361
---

parses bbox coming from widget-editor to display in a Mapbox map

---

CHANGELOG.md
layout/app/dashboard-detail/dashboard-widget-card/component.js
layout/app/dashboard-detail/dashboard-widget-card/styles.scss
layout/app/dashboard-detail/energy-country-explorer/custom-section/styles.scss

Adds captions to widgets in energy/countries dashboard.
Go to `http://localhost:9000/dashboards/energy?tab=country`, captions should be there.
https://www.pivotaltracker.com/story/show/175203532
---

captions to widgets in energy/countries dashboard

---

CHANGELOG.md
Dockerfile
Jenkinsfile
components/app/myrw/areas/pages/index/component.jsx
components/areas/card-list/component.jsx
components/areas/card/component.jsx
components/areas/card/styles.scss
components/areas/card/tooltip/component.jsx
components/modal/subscriptions-modal/area/index.js
components/modal/subscriptions-modal/area/selectors.js
css/_settings.scss
hooks/subscription/fetch-subscriptions-by-area.js
hooks/subscription/fetch-subscriptions.js
layout/embed/map/component.jsx
layout/explore/explore-areas-of-interest/component.jsx
layout/explore/explore-map/component.jsx
layout/explore/explore-map/index.js
next.config.js
services/areas.js
utils/axios.js
utils/user/areas.js

Migration to `v2/areas`
–
–
---

Migration to v2/areas

---

CHANGELOG.md
layout/app/dashboard-detail/energy-country-explorer/custom-section/component.js

avoids passing null/undefined widgets in GEDC

---

CHANGELOG.md
css/components/app/pages/explore.scss

fixes wrong height page loading certain pages

---

Jenkinsfile

enables v2 areas in preproduction

---

Jenkinsfile

enables v2 areas in production

---

Dockerfile
Jenkinsfile

updates value of WRI_API_URL_V2 env var

---

CHANGELOG.md
layout/explore/explore-areas-of-interest-new-area/component.jsx

adds spinner to area creation

---

CHANGELOG.md
components/admin/data/widgets/form/component.js
layout/explore/explore-areas-of-interest-new-area/component.jsx

deploys preproduction

---

CHANGELOG.md
package.json
yarn.lock

Removes `json-loader` dependency.
`rm- rf node_modules && yarn`
–
---

removes json-loader dependency

---

.gitignore
CHANGELOG.md
layout/app/dashboard-detail/component.jsx
pages/app/dashboards-detail/index.jsx

production deployment

---

CHANGELOG.md
pages/sign-in/index.jsx
redactions/admin/dashboards.js
redactions/admin/datasets.js
redactions/admin/faqs.js
redactions/admin/pages.js
redactions/admin/partners.js
redactions/admin/sources.js
redactions/admin/tools.js
redactions/dashboards.js
redactions/insights.js
redactions/modal.js
redactions/page.js
redactions/routes.js
redactions/tooltip.js
redactions/user.js
redactions/widget.js

Runs [name-default-component codemod](https://nextjs.org/docs/advanced-features/codemods#name-default-component) to replace nameless functions.
–
–
---

runs name-default-component codemod

---

CHANGELOG.md
components/modal/share-modal/share-modal-actions.js
cypress/integration/components/share-modal.spec.js
layout/app/dashboard-detail/component.jsx
package.json
yarn.lock

Updates `bitly` reducing significantly the size of the package.
–
–
---

bitly@7.1.2

---

CHANGELOG.md
layout/explore/explore-map/component.jsx

release preproduction

---

CHANGELOG.md
layout/app/dashboard-detail/energy-country-explorer/component.js
public/static/data/CountryEnergyExplorer.json

Adds new widgets to energy dashboard.
Go to `/dashboards/energy` and check the new widgets.
–
---

Energy dashboard: new widgets

---

components/modal/login-modal/component.jsx
cypress.json
cypress/integration/user/registration.spec.js
cypress/plugins/index.js
package.json
services/user.js
yarn.lock

- Removes the password field from the registration process.
- `react-google-recaptcha@2.1.0`
- tests for user registration
https://vizzuality.atlassian.net/browse/RW-22
---

Okta registration

---

cypress/integration/user/registration.spec.js
package.json

runs firefox headless by default

---

cypress/integration/components/share-modal.spec.js
cypress/integration/dashboards-create.spec.js

fixes wrong form selection in dashboard test

---

CHANGELOG.md

updates CHANGELOG

---

Jenkinsfile

remove containers after docker-compose test run

---

cypress/integration/components/share-modal.spec.js

Skips test temporary triggering falsy errors. The test passes locally under the same conditions.
–
–
---

skips test triggering falsy errors

---

CHANGELOG.md
cypress/integration/user/update-profile.spec.js
server/auth.js

Fixes deserialization of the user object when the user updated its profile.
- Log-in and go to `/profile`,
- update your info, save it.
- Refresh the page, updated information should be displayed correctly.
https://vizzuality.atlassian.net/browse/RW-21
---

fixes user object deserialization

---

cypress/integration/components/share-modal.spec.js

increases wait time for bitly test

---

CHANGELOG.md
layout/explore/explore-detail/explore-detail-header/component.jsx
layout/explore/explore-detail/explore-detail-header/index.js

fixes visual bug with dataset navigation bar in explore

---

hooks/dashboard/index.js
layout/footer/footer-links/component.jsx
services/dashboard.js

Provides a graceful way to fail fetching dashboards.
–
–
---

fails gracefully fetching dashboards

---

CHANGELOG.md
components/map/component.js
components/wysiwyg/widget-block/component.jsx
components/wysiwyg/widget-block/styles.scss
layout/app/dashboard-detail/dashboard-widget-card/component.jsx
layout/app/dashboard-detail/dashboard-widget-card/styles.scss

Fixes issue with height and padding styles in map-type widgets.
–
https://vizzuality.atlassian.net/browse/RW-44
---

RW-44 – Fixes issue with height and padding styles in map-type widgets

---

CHANGELOG.md
components/map/component.js
components/wysiwyg/widget-block/component.jsx
components/wysiwyg/widget-block/styles.scss
layout/app/dashboard-detail/dashboard-widget-card/component.jsx
layout/app/dashboard-detail/dashboard-widget-card/styles.scss
package.json

hotfix - RW-44

---

CHANGELOG.md
components/map/component.js
components/wysiwyg/widget-block/component.jsx
components/wysiwyg/widget-block/styles.scss
layout/app/dashboard-detail/dashboard-widget-card/component.jsx
layout/app/dashboard-detail/dashboard-widget-card/styles.scss
package.json

hotfix RW-44

---

CHANGELOG.md
Jenkinsfile
README.md
pages/dashboards/ocean-watch/about/index.jsx
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/index.jsx
pages/dashboards/ocean-watch/partners/index.jsx

Adds Ocean Watch routes.
https://vizzuality.atlassian.net/browse/OW-54
---

ocean watch: routing

---

CHANGELOG.md
pages/_document.jsx

Fixes search place in Explore map.
Go to `/data/explore` and lookup for a place.
https://vizzuality.atlassian.net/browse/RW-58
---

fixes search place in Explore map

---

CHANGELOG.md
pages/_document.jsx

https://vizzuality.atlassian.net/browse/RW-58
---

hotfix: fixes search place in Explore map

---

CHANGELOG.md
layout/explore/component.jsx
layout/explore/index.js
layout/head/app/component.jsx
layout/head/app/index.js
layout/layout/layout-app/component.js
pages/_app.jsx
redactions/common.js

Removes `hostname` key from global state.
–
–
---

removes hostname from global state

---

layout/app/contact-us/component.js

update rw media contact info

---

CHANGELOG.md
pages/dashboards/ocean-watch/partners/index.jsx

Updates texts from OW's partners page.
Text changes should be visible.
https://vizzuality.atlassian.net/browse/OW-24
---

ocean watch: updates texts from partners page

---

Jenkinsfile
cypress/integration/pages/explore/my-data/my-data-logged.spec.js
cypress/integration/pages/explore/my-data/my-data-non-logged.spec.js
cypress/integration/user/update-profile.spec.js

fixes tests

---

cypress/integration/user/sign-in.spec.js

fixes user sign-in tests

---

CHANGELOG.md
package.json
yarn.lock

Upgrades `redux` to latest version.
- Install dependencies via `yarn`
- Run application (`yarn dev`). Application should behave as usual.
https://vizzuality.atlassian.net/browse/RW-48
---

redux@4.1.0

---

CHANGELOG.md
components/mini-explore/component.jsx
components/mini-explore/map/index.jsx
hooks/country/index.js
layout/app/dashboard-detail/energy-country-explorer/component.jsx
layout/app/dashboard-detail/energy-country-explorer/custom-section/component.jsx
services/geostore.js

USA and World boundaries

---

CHANGELOG.md
components/mini-explore/component.jsx
components/mini-explore/map/index.jsx
hooks/country/index.js
layout/app/dashboard-detail/energy-country-explorer/component.jsx
layout/app/dashboard-detail/energy-country-explorer/custom-section/component.jsx
services/geostore.js

merge preproduction

---

Jenkinsfile

Optimize jenkinsfile execution order

---

pages/dashboards/ocean-watch/about/index.jsx
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/index.jsx
pages/dashboards/ocean-watch/partners/index.jsx

fixes Ocean Watch feature flag check

---

lib/store.js

Updates imports to avoid import components. Only reducers and initial states are imported now.
–
---

updates imports in store

---

CHANGELOG.md
README.md
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/index.jsx
public/static/data/ocean-watch.json
services/ocean-watch.js

https://vizzuality.atlassian.net/browse/OW-49
---

Ocean Watch: indicators set in introduction page

---

CHANGELOG.md
components/widgets/types/chart/index.jsx
package.json
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/country/index.jsx
public/static/data/ocean-watch.json
services/ocean-watch.js
utils/api.js
utils/widget.js
yarn.lock

Implements widget parametrization for chart-type widgets.
–
–
---

ocean watch: widget parametrization

---

CHANGELOG.md
components/widgets/types/map/component.stories.jsx
components/widgets/types/map/index.jsx

Adds the possibility of customising opacity per layer in map-type widgets.
–
https://vizzuality.atlassian.net/browse/OW-86
---

custom opacity per layer

---

CHANGELOG.md
components/areas/card/component.jsx
layout/embed/map/component.jsx
layout/explore/explore-map/component.jsx

removes Axios' cancel token

---

CHANGELOG.md
cypress/integration/user/registration.spec.js
services/user.js

Removes origin param from auth endpoints
Those endpoints should work as usual.
https://vizzuality.atlassian.net/browse/RW-71
---

removes origin param from auth endpoints

---

CHANGELOG.md
components/widgets/info/component.jsx
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map-swipe/component.stories.jsx
components/widgets/types/map-swipe/index.jsx
components/widgets/types/map/component.jsx
css/components/map/map-swipe.scss
css/index.scss
pages/dashboards/ocean-watch/country/[iso].jsx
public/static/data/ocean-watch.json
utils/layers/index.js

–
https://vizzuality.atlassian.net/browse/OW-87
---

map swipe widget: multiple layers

---

CHANGELOG.md
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map-swipe/index.jsx
components/widgets/types/map/component.jsx
components/widgets/types/map/index.jsx
pages/dashboards/ocean-watch/country/[iso].jsx
public/static/data/ocean-watch.json
utils/layers/index.js

https://vizzuality.atlassian.net/browse/OW-88
---

Ocean Watch – basin mask

---

public/static/data/ocean-watch.json

Added widget Id for Sediment pressure Chart 1.

added sed pressure chart 1 widget

---

CHANGELOG.md
components/card-indicator-set/indicator-visualization/component.jsx
components/mini-explore-widgets/component.jsx
components/mini-explore-widgets/component.stories.jsx
components/mini-explore-widgets/index.js
components/mini-explore-widgets/map/index.jsx
components/mini-explore-widgets/map/reducer.js
components/mini-explore-widgets/styles.scss
components/mini-explore-widgets/widget-sidebar/component.jsx
components/mini-explore-widgets/widget-sidebar/index.jsx
components/mini-explore-widgets/widget-sidebar/widget-item/component.jsx
components/mini-explore-widgets/widget-sidebar/widget-item/index.jsx
components/mini-explore/map/component.jsx
components/widgets/header/styles.scss
components/widgets/info/component.jsx
components/widgets/info/styles.scss
components/widgets/types/chart/component.jsx
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map/component.jsx
css/components/widget.scss
pages/dashboards/ocean-watch/country/[iso].jsx
public/static/data/ocean-watch.json

–
https://vizzuality.atlassian.net/browse/OW-68
---

River Water Quality section

---

components/mini-explore-widgets/component.jsx
components/mini-explore-widgets/map/index.jsx
public/static/data/ocean-watch.json

adds mask layer to mini explore widgets

---

components/map/component.js
components/widgets/types/map-swipe/index.jsx
components/widgets/types/map/index.jsx

fixes issue updating map styles

---

components/mini-explore-widgets/component.jsx
components/mini-explore-widgets/map/index.jsx
components/mini-explore-widgets/reducer.js
components/mini-explore-widgets/widget-sidebar/index.jsx
components/mini-explore/map/component.jsx
package.json
pages/dashboards/ocean-watch/country/[iso].jsx
public/static/data/ocean-watch.json
yarn.lock

Map state hover

---

public/static/data/ocean-watch.json

- Added the layers form the spreadsheet to the mini-explore
- Added the line pattern to the mask for the watershed boundaries

added layers to mini-explore and changed lines in mask

---

components/widgets/types/chart/component.jsx
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map/component.jsx
pages/dashboards/ocean-watch/country/[iso].jsx

loads widgets on view

---

components/map/component.js
components/map/utils.js
components/tooltip-list/component.jsx
components/tooltip-list/component.stories.jsx
components/tooltip-list/index.js
components/tooltip-list/styles.scss
css/layouts/_ocean-watch.scss
css/mapbox.scss
layout/layout/ocean-watch/map/component.jsx
layout/layout/ocean-watch/map/index.js
layout/layout/ocean-watch/storytelling/component.jsx
layout/layout/ocean-watch/storytelling/index.js
layout/layout/ocean-watch/storytelling/indicators-navigation/component.jsx
layout/layout/ocean-watch/storytelling/indicators-navigation/index.js
layout/layout/ocean-watch/storytelling/story-step/component.jsx
layout/layout/ocean-watch/storytelling/story-step/index.js
package.json
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/index.jsx
public/static/data/ocean-watch.json
services/ocean-watch.js
yarn.lock

–
https://vizzuality.atlassian.net/browse/OW-27
---

Ocean Watch Intro page - map

---

components/card-indicator-set/indicator-visualization/component.jsx
components/card-indicator-set/indicator-visualization/styles.scss
pages/dashboards/ocean-watch/country/[iso].jsx
public/static/data/ocean-watch.json

Added the 2 first widgets to the top indicator section.
I replicated the widget structure to add widgets to the bottom part but it's not showing, so not sure what I did wrong.

Added the first indicators to the top section and tried to add the section at the bottom

---

components/card-indicator-set/component.jsx
components/card-indicator-set/component.stories.jsx
components/card-indicator-set/indicator-visualization/component.jsx
components/card-indicator-set/numeric-card-indicator/component.jsx
components/card-indicator-set/numeric-card-indicator/index.jsx
components/card-indicator-set/numeric-card-indicator/styles.scss
components/ui/icon/component.jsx
hooks/sql.js
hooks/user.js
pages/dashboards/ocean-watch/country/[iso].jsx
public/static/data/ocean-watch.json

https://vizzuality.atlassian.net/browse/OW-72
---

adds numeric card indicator

---

CHANGELOG.md
components/app/common/Banner.jsx
css/components/app/common/banner.scss
pages/dashboards/ocean-watch/country/[iso].jsx

–
https://vizzuality.atlassian.net/browse/OW-32
https://vizzuality.atlassian.net/browse/OW-41
https://vizzuality.atlassian.net/browse/OW-41
–
–

ocean watch: adds call to actions in country page

---

CHANGELOG.md
pages/dashboards/ocean-watch/index.jsx

https://vizzuality.atlassian.net/browse/OW-109
–
–

ocean watch: intro texts

---

CHANGELOG.md
components/card-indicator-set/numeric-card-indicator/component.jsx
public/static/data/ocean-watch.json

Add several texts to country page.
–
https://vizzuality.atlassian.net/browse/OW-110
–
–

ocean watch: country page texts

---

CHANGELOG.md
components/mini-explore/datasets-sidebar/component.jsx
components/mini-explore/datasets-sidebar/index.jsx
components/mini-explore/styles.scss
package.json
yarn.lock

–
https://vizzuality.atlassian.net/browse/OW-102
–
–

collapsible mini-explore

---

CHANGELOG.md
css/layouts/_ocean-watch.scss
layout/layout/ocean-watch/storytelling/component.jsx

–
https://vizzuality.atlassian.net/browse/OW-106
–
–

added back to top button to storytelling

---

public/static/data/ocean-watch.json

Updated text in the country profile page

---

public/static/data/ocean-watch.json

Content changes for the scrollytelling piece on the frontend- Text changes, some header changes and 'info' pop up changes

Updates to the scrollytelling element

---

constants/ocean-watch.js
layout/app/partners/component.jsx
layout/footer/component.jsx
layout/footer/partners-carousel/component.jsx
layout/footer/partners-carousel/index.js
layout/footer/partners-carousel/index.jsx
layout/layout/ocean-watch/component.jsx
pages/dashboards/ocean-watch/partners/index.jsx

Fixes partners display in preproduction.
https://vizzuality.atlassian.net/browse/OW-122

fixes partners

---

constants/ocean-watch.js
hooks/favorite/index.js
hooks/favorite/is-favorite.js
layout/app/partners/component.jsx
layout/embed/widget/component.jsx
layout/embed/widget/index.js
layout/footer/component.jsx
layout/footer/partners-carousel/component.jsx
layout/footer/partners-carousel/index.js
layout/footer/partners-carousel/index.jsx
layout/layout/ocean-watch/component.jsx
package.json
pages/dashboards/ocean-watch/partners/index.jsx
pages/embed/widget/[id].jsx
public/static/data/ocean-watch.json
services/favourites.js

preproduction <-- develop

---

layout/app/partners/component.jsx

fixes wrong default value for partners

---

public/static/data/ocean-watch.json

Full list of changes:
- Added half- and full-width text sections to section Catchment Areas and Land Cover
- Renamed River Water Quality section (title and heading)
- Added widgets, generally by duplicating and lightly editing elements within RWQ section
- Moved mini-explore widget element to beginning of RWQ section
Resolves #XXX
Optional. Ancillary topics, caveats, alternative …

OW WRI testing: First set of schematic tests, mostly just rearranging and modifying text

---

CHANGELOG.md
public/static/data/ocean-watch.json

https://vizzuality.atlassian.net/browse/OW-123

adds text blocks

---

CHANGELOG.md
layout/layout/ocean-watch/map/component.jsx

https://vizzuality.atlassian.net/browse/OW-113

increases zoom one level

---

public/static/data/ocean-watch.json

Duplicated Sediment Pressure Map swipey element in section
Catchment Areas and Land Cover: one copy with half size,
one with modified comment
Resolves #XXX

OW WRI Testing: Simple testing of swipey element with OW schematic

---

CHANGELOG.md
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/index.jsx

https://vizzuality.atlassian.net/browse/OW-129

updates text and link for suggest a story banner

---

public/static/data/ocean-watch.json

•	Duplicated third grouping in section Catchment Areas and Land Cover.
•	Retitled and resized first map element 
•	Replaced chart with pair of (half-size) map elements, using arbitrary map widgets (first one 682b7153-c6f8-483d-b803-41ce942f6493 “Active Fires (MODIS)”, second one 756a71fb-1d9c-409f-82d5-efb4ebcac285 “Major Ports”)
•	Inserted text element to confirm layout parsing
Resolves #XXX
Optional. Screenshots, `curl` …

OW WRI Testing: Map element

---

public/static/data/ocean-watch.json

- Duplicated last grouping in section Catchment Areas and Land Cover, and moved it to front of section
- Resized (to full) and modified comment for first element, leaving widget intact
- Inserted full-sized text element immediately after
- Made final row of grouping a pair of half-size arbitrary chart elements: first one 34dd8dd0-48c2-4729-8b01-981416d121e9 “Population Exposed to Unhealthy Levels of PM2.5 (%)”, second one 50c3fb9c-cef3-4533-8ae7-9ad122bb7963 “Top 10 Protected Areas by Size”
* Include test case, and …

OW WRI Testing: Chart element of JSON schematic

---

public/static/data/ocean-watch.json

Only made changes to production section
- Added widget ids to the Intro page and where missing in the country profile.
- Added some datasets to mini explore

updated intro page and country profile

---

public/static/data/ocean-watch.json

- (All changes made to mini-Explore element in section Ecosystems and Pressures)
- Change title
- Reorder groupings: Climate Pressures to first, Ecosystems to second
- Renamed grouping Land-sea pressures
- Removed group Response
- Added new group Test group, with datasets drawn from other groups and random set of defaults
Resolves #XXX
Optional. Ancillary topics, caveats, alternative …

OW WRI Testing: mini-Explore element

---

public/static/data/ocean-watch.json

Updated copy changes to the homepage 
@andresgnlez - I also deleted an 'info' button under Dependence on the Ocean 
Could you add me another one Ocean Biodiversity pls?

Updated copy on the homepage

---

public/static/data/ocean-watch.json

Copy updated for the country profile page- @andresgnlez Can you merge pls?

Changed Country Profile Copy

---

README.md

data environments docs

---

CHANGELOG.md
components/widgets/share-modal/component.jsx
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map-swipe/index.jsx
layout/embed/map-swipe/component.jsx
layout/embed/map-swipe/index.jsx
pages/dashboards/ocean-watch/country/[iso].jsx
pages/embed/map-swipe/[id].jsx
pages/embed/map-swipe/index.jsx
pages/embed/widget/[id].jsx
utils/embed.js
utils/widget.js

Go to [/embed/map-swipe/2d80df96-f93e-4a1b-95fc-4f1241139c0e?geostore_env=geostore_prod&geostore_id=08071a69b43cd5cc16dc2c6aedda966e&aoi=08071a69b43cd5cc16dc2c6aedda966e](/embed/map-swipe/2d80df96-f93e-4a1b-95fc-4f1241139c0e?geostore_env=geostore_prod&geostore_id=08071a69b43cd5cc16dc2c6aedda966e&aoi=08071a69b43cd5cc16dc2c6aedda966e)
https://vizzuality.atlassian.net/browse/OW-121
–
–

embeds: map-swipe

---

CHANGELOG.md
pages/dashboards/ocean-watch/country/[iso].jsx
public/static/data/ocean-watch.json

https://vizzuality.atlassian.net/browse/OW-146

adds custom anchor titles

---

CHANGELOG.md
components/mini-explore-widgets/component.jsx
components/mini-explore-widgets/reducer.js

https://vizzuality.atlassian.net/browse/OW-147

mini-explore-widgets: fixes data placeholder

---

layout/footer/component.jsx
layout/layout/ocean-watch/component.jsx
layout/layout/ocean-watch/partners/component.jsx
layout/layout/ocean-watch/partners/index.jsx
pages/dashboards/ocean-watch/about/index.jsx
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/country/index.jsx
pages/dashboards/ocean-watch/index.jsx
services/pages.js

Setup of about page to fetch content from API.
https://vizzuality.atlassian.net/browse/OW-21
https://vizzuality.atlassian.net/browse/OW-63
Resolves #XXX

ocean watch: about page

---

public/static/data/ocean-watch.json

'biodiversity-1' indicator updated

---

components/card-indicator-set/indicator-visualization/component.jsx

This PR fixes the issue described in https://vizzuality.atlassian.net/browse/OW-152
See the Jira issue for more information.
https://vizzuality.atlassian.net/browse/OW-152

fix issue regarding widgets not updating correctly when changing country

---

components/card-indicator-set/indicator-visualization/component.jsx

Fix issue described in https://vizzuality.atlassian.net/browse/OW-126

Fix overflowing widgets issue

---

public/static/data/ocean-watch.json

The year in the `query` for the `biodiversity` indicator on the country and intro page was changed 2021
Resolves #XXX

`biodiversity` query updated to 2021

---

public/static/data/ocean-watch.json

changed basin level 3 to 5 in the interactive map.

set level 5 in mask of intercative map

---

components/card-indicator-set/indicator-visualization/component.jsx

https://vizzuality.atlassian.net/browse/OW-156

Fix units issue OW-156

---

components/widgets/share-modal/component.jsx
services/webshot.js

https://vizzuality.atlassian.net/browse/OW-44

Fix download image issue

---

public/static/data/ocean-watch.json

Updated query for `fishing` indicator on country page
Resolves #XXX

Added `fishing` query

---

public/static/data/ocean-watch.json

Added `AS value` so query could be read properly
Resolves #XXX

Fixed `Maritime Transport: Shipping` query

---

public/static/data/ocean-watch.json

Changes to copy 
@pablopareja - I've tried to add 'i' text to each of the indicator cards, although the 'i' button only appears on the first card. Can you please check I've done this correctly and it's coming through right? 
Cheers
Becky

Update to Value indicators

---

CHANGELOG.md
components/card-indicator-set/card-indicator/component.jsx
components/collections-panel/component.jsx
components/widgets/share-modal/component.jsx
layout/layout/ocean-watch/storytelling/component.jsx

Adds some analytics events.
–
https://vizzuality.atlassian.net/browse/OW-155

ocean watch analytics events

---

CHANGELOG.md
components/map/constants.js
components/mini-explore-widgets/map/index.jsx
components/mini-explore/map/index.jsx
public/static/data/ocean-watch.json

Map interactity based on id field presence.
https://vizzuality.atlassian.net/browse/OW-155

map interactity based on id field presence

---

public/static/data/ocean-watch.json

Updates to copy

---

public/static/data/ocean-watch.json

@andresgnlez - Sorry, a second PR!

More merges for copy

---

public/static/data/ocean-watch.json

@andresgnlez - Most of Rachel's changes were fine; I've tweaked a couple of them 
Cheers
B

Copy Updates

---

CHANGELOG.md
css/layouts/_page.scss
layout/layout/ocean-watch/hero/component.jsx

–
https://vizzuality.atlassian.net/browse/OW-171

adds beta to Ocean Watch

---

pages/dashboards/ocean-watch/index.jsx

https://vizzuality.atlassian.net/browse/OW-173

adds beta warning text

---

components/mini-explore-widgets/widget-sidebar/index.jsx

–
https://vizzuality.atlassian.net/browse/OW-174

updates text of mini explore widgets

---

components/mini-explore-widgets/widget-sidebar/index.jsx
layout/explore/explore-datasets/component.jsx
layout/explore/explore-topics/constants.js

preproduction <- develop

---

layout/layout/ocean-watch/map/component.jsx

adjust map selector

---

CHANGELOG.md
components/card-indicator-set/indicator-visualization/component.jsx
package.json

–
https://vizzuality.atlassian.net/browse/OW-167

fixes invalid score in OW widget

---

public/static/data/ocean-watch.json

This query was drawing from a deleted table. It has been updated to draw from the correct table

Fixed `marine-protected-areas` query

---

CHANGELOG.md
components/card-indicator-set/indicator-visualization/component.jsx

Allows strings as indicator score.
https://vizzuality.atlassian.net/browse/OW-194

allows strings as indicator score

---

CHANGELOG.md
constants/app.js
layout/head/app/component.jsx
utils/layers/pulse_layers.js

- Removes conditional Cesium script load.
- Removes old layer.
https://vizzuality.atlassian.net/browse/RW-106

Planet Pulse fixes

---

public/static/data/ocean-watch.json

Update 1st swipe map & eutrophication layer

---

public/static/data/ocean-watch.json

Updated text for `oceans-climate` caption, updated widget ids

---

CHANGELOG.md
components/card-indicator-set/indicator-visualization/component.jsx

Fixes false error in Climate NDC indicator after enabling `useQuery` for other indicators.
https://vizzuality.atlassian.net/browse/OW-193

fixes false error in Climate NDC indicator

---

public/static/data/ocean-watch.json

Remove `Fisheries (mang)` in prod

---

layout/layout/ocean-watch/storytelling/component.jsx
layout/layout/ocean-watch/storytelling/story-step/component.jsx
pages/dashboards/ocean-watch/index.jsx

Storytelling performance tweaks

---

CHANGELOG.md
components/widgets/types/chart/component.jsx
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map/component.jsx
css/components/widget.scss

Standardize caption widget styles.
https://vizzuality.atlassian.net/browse/OW-164

standardize caption widget styles

---

CHANGELOG.md
components/widgets/types/chart/component.jsx
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map/component.jsx
css/components/widget.scss
layout/layout/ocean-watch/map/component.jsx

preproduction release

---

CHANGELOG.md
next.config.js
package.json
yarn.lock

Updates to `next@12` and uses `webpack5` by default.
–

next@12 & webpack 5

---

CHANGELOG.md
components/map/layer-manager/providers/gee/index.ts
components/map/layer-manager/providers/index.ts
components/map/layer-manager/providers/wms/index.ts
components/map/layer-manager/providers/wms/types.d.ts
pages/layer-manager.tsx

Adds custom Layer Manager provider to support WMS layers
https://vizzuality.atlassian.net/browse/RW-113

adds WMS provider

---

CHANGELOG.md
components/map/layer-manager/providers/feature-service/index.ts
components/map/layer-manager/providers/feature-service/types.d.ts
components/map/layer-manager/providers/index.ts
package.json
pages/layer-manager.tsx
yarn.lock

adds FeatureService provider

---

components/map/component.tsx
components/map/constants.ts
components/mini-explore-widgets/map/index.jsx
components/mini-explore/map/index.jsx
components/widgets/types/map-swipe/component.jsx
components/widgets/types/map-swipe/index.jsx
components/widgets/types/map/component.jsx
components/widgets/types/map/component.stories.jsx
components/widgets/types/map/index.jsx

Updates Storybook stories related to maps to support new layer spec.
https://vizzuality.atlassian.net/browse/RW-98

updates Storybook stories

---

CHANGELOG.md
components/map/selectors.js
components/map/utils.js
components/mini-explore-widgets/map/index.jsx
components/mini-explore/map/component.jsx
components/mini-explore/map/index.jsx

Fixes basins interactivity in Water Quality widget.
https://vizzuality.atlassian.net/browse/OW-201

ocean watch: fixes water quality basins interactivity

---

public/static/data/ocean-watch.json

Update query for `fishing` indicator to display data from the year 2021

Update year for `fishing` indicator

---

components/mini-explore-widgets/map/index.jsx

Removes hardcoded bboxes for Russia and United States of America.
–

removes custom bbox for USA and RUS

---

CHANGELOG.md
pages/webshot/layer/[id].tsx

hotfix: increases layer webshot time

---

components/widgets/types/chart/component.tsx

Removes issue of charts exceeding container's height
https://vizzuality.atlassian.net/browse/OW-202

removes flex-grow from widget container

---

CHANGELOG.md
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/index.jsx

Updates texts and links for Coral Reefs calls to action.
https://vizzuality.atlassian.net/browse/OW-29

updates Coral Reefs calls to action

---

layout/layout/ocean-watch/map/component.jsx

Fixes Ocean Watch's coastal map.
–

ocean watch: fixes coastal map

---

CHANGELOG.md
components/card-indicator-set/indicator-visualization/component.jsx
public/static/data/ocean-watch.json

https://vizzuality.atlassian.net/browse/OW-179

ocean-watch: custom no data for set of indicators

---

components/card-indicator-set/indicator-visualization/component.jsx

Removes format condition as a requirement to be displayed.
https://vizzuality.atlassian.net/browse/OW-205

removes format condition

---

CHANGELOG.md
pages/_document.tsx

Disables robots crawling for staging and preproduction sites
https://vizzuality.atlassian.net/browse/RW-124

disables robots for staging, preproduction sites

---

CHANGELOG.md
components/card-indicator-set/indicator-visualization/component.jsx
components/widgets/card/component.tsx
components/widgets/types/map/index.tsx
layout/app/widget-detail/component.tsx
layout/embed/map-swipe-widget/component.jsx
layout/embed/map/component.jsx
layout/embed/widget/component.tsx
pages/dashboards/ocean-watch/country/[iso].jsx

geostore names in widget titles

---

CHANGELOG.md
layout/header/constants.js
layout/header/header-menu-mobile/component.jsx
layout/header/header-menu/component.jsx

https://vizzuality.atlassian.net/browse/RW-92

fixes highlighting of navigation bar based on current page

---

CHANGELOG.md
components/map/component.tsx
components/widgets/types/map-swipe/component.tsx
components/widgets/types/map/component.tsx
types/layer.d.ts
types/widget.d.ts
utils/layers/index.ts

Adds ability render map attribution.
https://vizzuality.atlassian.net/browse/RW-77

map: renders attribution

---

public/static/data/ocean-watch.json

Switched water quality and land cover widgets to new versions which belong to different parent datasets

Testing widgets for new parent assets in staging

---

public/static/data/ocean-watch.json

Following testing in staging, I have updated the widget IDs of several widgets. These new widgets are copies of the old widgets that have been created under a new parent asset for better organization.

Update new widgets in production

---

CHANGELOG.md
components/app/common/Banner.jsx
components/card-indicator-set/card-indicator/_styles.scss
components/card-indicator-set/card-indicator/component.jsx
components/tooltip-list/_styles.scss
components/tooltip-list/component.jsx
components/ui/Tabs.js
css/components/ui/tabs.scss
css/layouts/_ocean-watch.scss
layout/layout/ocean-watch/component.jsx
layout/layout/ocean-watch/hero/component.jsx
layout/layout/ocean-watch/map/component.jsx
layout/layout/ocean-watch/storytelling/background/component.jsx
layout/layout/ocean-watch/storytelling/component.jsx
layout/layout/ocean-watch/storytelling/indicators-navigation/component.jsx
layout/layout/ocean-watch/storytelling/story-step/_styles.scss
layout/layout/ocean-watch/storytelling/story-step/component.jsx
pages/dashboards/ocean-watch/country/[iso].jsx
pages/dashboards/ocean-watch/country/index.jsx
pages/dashboards/ocean-watch/index.jsx

Makes Ocean Watch homepage more responsive to mobile devices.
https://vizzuality.atlassian.net/browse/OW-209

Ocean Watch homepage responsive

---

CHANGELOG.md
layout/explore/component.jsx
layout/explore/index.js
pages/data/explore/[[...dataset]].jsx
services/dataset.ts
types/dataset.d.ts

Adds `<meta name="robots" content="noindex, follow" />` to unpublished datasets in Explore page.
https://vizzuality.atlassian.net/browse/RW-126

adds meta tag to not index unpublished datasets

---

components/survey-prompt/component.tsx

fixes tests with survey modal

---

CHANGELOG.md
package.json
yarn.lock

Bumps `next` dependency to version `12.1.6`.
–

bumps next@12.1.6

---

CHANGELOG.md
layout/layout/coral-reefs-dashboard/condition-section/component.jsx

Text updates to Coral Reef's dashboard.
https://vizzuality.atlassian.net/browse/RW-137

coral reefs dashboard: text changes

---

CHANGELOG.md
layout/admin/data-detail/component.js
package.json
yarn.lock

- replaces `react-fast-compare` with `lodash/isEqual`.
- removes `react-fast-compare`.
–

removes react-fast-compare

---

CHANGELOG.md
package.json
yarn.lock

removes chroma-js

---

CHANGELOG.md
layout/explore/component.jsx
layout/explore/constants.js
scripts/schemas/foo065brw1-global-cropland-change.tsx
scripts/schemas/gender-gap-index-2.tsx
scripts/schemas/gini-index.tsx
scripts/schemas/material-extraction-trade-and-use.tsx
scripts/schemas/population-exposed-to-unhealthy-levels-of-pm-25.tsx
scripts/schemas/soc-003-2015-gridded-infant-mortality.tsx
scripts/schemas/soc025-gender-inequality-index.tsx
scripts/schemas/trees-in-mosaic-landscapes.tsx
scripts/schemas/wetlands-and-waterbodies.tsx

Adds a JSON, vía script, to allow [Schema](https://schema.org/) service reading additional metadata of some specific widgets.
https://vizzuality.atlassian.net/browse/RW-141

adds rich schema scripts for specific datasets

---

CHANGELOG.md
components/areas/form/component.jsx
components/map/_styles.scss
components/map/component.tsx
components/map/plugins/compare/component.jsx
components/widgets/types/map-swipe/component.tsx
layout/explore/explore-map/component.jsx
package.json
yarn.lock

- Fixes a bug that prevented the user to draw a polygon on the map.
- updated `@mapbox/mapbox-gl-draw` dependency to the most recent fixed version.
–

fixes bug preventing user draw on map

---

CHANGELOG.md
components/map/component.stories.tsx
components/map/layer-manager/component.tsx
components/map/layer-manager/utils.ts
components/widgets/types/map/component.stories.tsx
package.json
types/deck.gl.d.ts
types/layer.d.ts
yarn.lock

https://vizzuality.atlassian.net/browse/RW-138

adds support for deck.gl: TileLayer with DecodedRasterLayer sublayers

---

scripts/schemas/material-extraction-trade-and-use.tsx

Fixes schema for Material-Extraction-Trade-and-Use schema dataset.
https://vizzuality.atlassian.net/browse/RW-150

fixes Material-Extraction-Trade-and-Use schema

---

package.json

removes firefox as cypress browser

---

components/map/plugins/compare/component.jsx

Replaces old load map callback with new API.
https://gfw.atlassian.net/browse/RW-10

updates map load API callback

---

CHANGELOG.md

updates changelog after release
