- components/admin/dataset/pages/index.js
- components/admin/dataset/table/DatasetTable.js
- css/components/admin/dataset/datasets_index.scss
- css/components/ui/custom_select.scss
- css/index.scss
- redactions/admin/datasets.js
- redactions/index.js
- selectors/admin/datasets.js
This PR lets the user filter the datasets by name on the listing page of the CMS.
</p>
In order to bring the functionality, a numerous number of changes have been necessary. Here are the main changes:
* `DatasetTable` doesn't store the list of datasets anymore, Redux's store does
* A new selector (from `reselect`) has been created to filter the datasets
[Pivotal task](https://www.pivotaltracker.com/story/show/144274023)
> CMS - Search for a dataset on the listing page

- components/widgets/WidgetEditor.js
- utils/widgets/bar.js
- utils/widgets/line.js
</p>
This PR brings a few improvements to the bar and line charts:
- both charts now support a temporal x axis
- both charts won't necessarily have an y axis that starts with 0
- line charts will have *approximatively* 6 ticks on the x axis
- lines of the line charts will be sharp (no interpolation)
[Pivotal task](https://www.pivotaltracker.com/story/show/148241329)
> Widget chart improvements

- components/admin/dataset/form/constants.js
- components/admin/dataset/form/steps/Step1.js
- components/admin/dataset/pages/index.js
- components/admin/dataset/table/DatasetTable.js
- components/admin/dataset/table/td/PublishedTD.js
- components/admin/widget/table/WidgetTable.js
- components/ui/customtable/CustomTable.js
- css/components/form/checkbox.scss
- pages/admin/pages/edit.js
- redactions/admin/datasets.js
- redactions/explore.js
- redactions/user.js
- routes.js
This PR adds:
- Published dataset checkbox
- Published dataset column
- Filter in explore page
**IMPORTANT!!!!**
I just discovered that the API is not filtering by published. I mean, it does, but it does it wrong. It only sends 30 datasets, but we have 116 datasets published. I already told them that they need to check it out
**UPDATE**
It seems that is working now
> Published dataset

- components/widgets/VegaChart.js
- components/widgets/VegaChartTooltip.js
</p>
This PR fixes issues with the values of the tooltip:
- It wouldn't work properly for the pie charts because it was expecting an x axis
- It would keep the previous value when leaving a mark
- The algorithm would delete any eventual signals
- The code has been refactored
[Pivotal task](https://www.pivotaltracker.com/story/show/148345887)
> Fix the wrong values of the tooltip

- components/app/layout/Layout.js
The tooltip wouldn't disappear when the user would navigate to a new page. This is because the tooltip is managed in Redux.
The solution is to trigger an action for every new page to hide it (in case it was visible).
[Pivotal task](https://www.pivotaltracker.com/story/show/148655725)
> Prevent the tooltip for staying in place when routing

- utils/widgets/WidgetHelper.js
We try to avoid the line chart looking wrong when the data coming from the dataset is not sorted. If the user wants a custom sorting, they can do so, even if it doesn't make sense and doesn't do anything in that case.
> By default, sort the line chart data ASC

- components/admin/layout/Layout.js
- components/app/layout/Layout.js
Even with [the previous fix](https://github.com/resource-watch/resource-watch/pull/63), the Annoying Sticky Tooltip ™ would invite itself on some pages. This PR forbids it from showing up unexpectedly once and for all ⚔️.
In detail, the previous solution was to toggle off the tooltip every time the `Layout` component would mount. This had two flaws:
1. Only the `Layout` component of the public site had been updated, not the one of the CMS.
2. Some pages don't re-mount the component because they are sub-pages (basically the pages which are tabs).
To prevent the Annoying Sticky Tooltip ™ to come back, this PR toggles off the tooltip _each time_ some navigation occurs. The listener is registered once in both `Layout` components if not previously defined. Because each page extends the `Page` …
> Forbid the Annoying Sticky Tooltip ™ from showing up unexpectedly once and for all

- components/app/explore/DatasetWidgetChart.js
- components/widgets/VegaChart.js
- components/widgets/VegaChartLegend.js
- components/widgets/VegaChartTooltip.js
- components/widgets/WidgetCard.js
- components/widgets/WidgetEditor.js
- components/widgets/WidgetList.js
- css/components/admin/widget/widget_chart.scss
- css/components/widgets/vega_chart_legend.scss
- css/components/widgets/widget_editor.scss
- css/index.scss
- utils/widgets/1d_scatter.js
- utils/widgets/1d_tick.js
- utils/widgets/WidgetHelper.js
- utils/widgets/bar.js
- utils/widgets/line.js
- utils/widgets/pie.js
- utils/widgets/scatter.js
- utils/widgets/theme.js
- utils/widgets/vega-theme-thumbnails.json
This PR adds the support for legends for the charts. By default, in the widget editor, only the pie chart and the scatter chart with dots of varying sizes will get one.
</p>
In addition to that, the PR:
* fixes an issue where the widgets wouldn't be saved with the custom formattings of the ticks and the tooltip
* fixes the layout of the My RW > My Widgets section (the pie and bar charts, as thumbnails, still have an issue that will be dealt with later)
* updates the default color of the charts to dark blue
The PR includes these changes to the `VegaChart` component:
- a new `showLegend` prop to hide it if needed
- a new  `getForceUpdate` prop (a function) which is passed a function to call to force the re-render of the chart (useful when the grid/list layout changes)
> Brand new shiny legend

- components/app/layout/Layout.js
- components/app/myrw/widgets/MyRWWidgetsEdit.js
- components/modal/SaveWidgetModal.js
- components/modal/UploadAreaIntersectionModal.js
- components/ui/SliderSelect.js
- components/widgets/ChartEditor.js
- css/components/modal/upload_area_intersection_modal.scss
- css/components/ui/custom_select.scss
- css/components/ui/spinner.scss
- css/components/widgets/chart_editor.scss
- css/components/widgets/widget_editor.scss
- css/index.scss
- redactions/modal.js
- redactions/widgetEditor.js
- utils/widgets/WidgetHelper.js
This PR implements the feature to let the user upload an area or to select a country for intersection with the data of the widget.
</p>
In order to implement the feature, major changes has been made to the component `SliderSelect`:
* several (hopefully all) of its bugs have been fixed
* the code has been fully commented
* two props have been added:
* `allowNonLeafSelection` forces the user to select a leaf node in the tree
* `waitForChangeConfirmation` makes the component wait for the result of the callback prop `onValueChange` before setting an option as selected (can be asynchronous)
The `Modal` component has also received a small change: when the user closes it with the close button, by pressing the ESC key or by clicking the overlay, a callback can be executed …
> Area intersection in the widget editor

- components/modal/SubscribeToDatasetModal.js
- components/modal/UploadAreaIntersectionModal.js
- components/ui/SliderSelect.js
- css/components/modal/subscribe_to_dataset_modal.scss
- css/components/modal/upload_area_intersection_modal.scss
- css/components/ui/custom_select.scss
This PR lets the user upload an area to filter the results of a dataset subscription when registering it.
Additionally, the `SliderSelect` component has been updated to fix an issue where the clear button couldn't be triggered and to add a message when it waits for an action from the user.
[Pivotal task](https://www.pivotaltracker.com/story/show/150142421)
> Let the user upload an area when subscribing to a dataset

- pages/app/ExploreDetail.js
- redactions/user.js
- services/UserService.js
_UPDATE: the initial bug has been solved by Pablo._
This PR removes a bug preventing the Explore Detail page from loading when the user wouldn't be logged in.
The bug was due to the fact we would try to load the user's intersection area whereas they wouldn't be logged.
An additional bug has been fixed: when requesting the areas, the API could return a 20X error and the code would try to access attributes of the response which was empty. To fix it, I've add a line to check the status of the request (`response.ok`).
[Pivotal task](https://www.pivotaltracker.com/n/projects/1374154/stories/150884771)
> Fix an issue where Explore Detail wouldn't load

- services/DatasetService.js
This PR adds a timeout to the method which fetches the results from Jimmy to avoid blocking the widget editor for too long.
[Pivotal task](https://www.pivotaltracker.com/story/show/150913531)
> Add a timeout to fetch the result from Jiminy

- components/modal/EmbedMyWidgetModal.js
- components/ui/Legend.js
- components/widgets/WidgetCard.js
- css/components/app/pages/embed/embed_widget.scss
- css/components/ui/legend.scss
- pages/app/embed/EmbedMap.js
- pages/app/embed/EmbedWidget.js
- redactions/widget.js
- routes.js
This PR re-implements the embed of the map widgets. Their URLs are now different because a different file manages the map widgets.
</p>
The `Legend` component has been added a new prop called `interactionDisabled` to disable all of its interactions.
You can test an embedded map widget here: http://localhost:3000/embed/map/72a9871e-2fdb-44e4-adcd-239c5456b98f
> Re-implement the embed of the map widgets

- utils/widgets/WidgetHelper.js
This PR fixes an issue that prevented the editor from letting the user use the size field.
Remember that only numerical columns can be used in the size field.
[Pivotal task](https://www.pivotaltracker.com/story/show/151286241)
> Fix an issue that prevented the size field  from working in the editor

- components/admin/layers/table/LayersTable.js
- components/admin/layers/table/td/OwnershipTD.js
- components/admin/widgets/table/WidgetsTable.js
- components/admin/widgets/table/td/OwnershipTD.js
Task: https://www.pivotaltracker.com/story/show/151253803
The ownership is determined by the comparison of the resource's `userId` and the `id` of the current user.
> Adds ownership column to widget and layer tables

- components/widgets/editor/WidgetEditor.js
- components/widgets/editor/helpers/WidgetHelper.js
- components/widgets/editor/redux/widgetEditor.js
- components/widgets/editor/services/RasterService.js
- css/components/widgets/raster_chart_editor.scss
- utils/widgets/WidgetHelper.js
This PR fixes issues with the raster datasets in the widget editor. Most of the issues are due to the decoupling of the editor from the app (PR #238).
Here are the other changes:
* a toastr notification that used to show a JS error doesn't display it anymore
* the toastr notification regarding the fields not loading has been removed because raster datasets don't have fields and at the time of the request, we don't know if the dataset is a raster one
* the editor is not hidden anymore when the dataset is a raster one and it doesn't have any layer
* the band selector is not hidden below the loader of the stats table anymore
* a timeout of 15s has been added to the request loading the chart's data (not only for raster datasets)
[Pivotal …
> Fix issues with the raster datasets in the widget editor

- components/widgets/editor/helpers/WidgetHelper.js
- utils/widgets/WidgetHelper.js
The values are truncated to 2 decimals to improve legibility. The truncation is made at parse time instead of at rendering time because the horizontal ticks are categorical and can't be treated as numbers by Vega. Moreover, it would affect all the bar charts and not only the raster ones.
[Pivotal task](https://www.pivotaltracker.com/story/show/151002429)
> Truncate the x values of the raster bar charts

- services/DatasetsService.js
This PR adds by default datasets with `env=preproduction` to the response of the method `fetchAllData()` from DatasetsService.
> Add preproduction to fetchAllData service

- components/widgets/editor/helpers/WidgetHelper.js
- utils/widgets/WidgetHelper.js
This PR fixes a bug that would crash the app when the user would try to create a 3D scatter chart with the size column.
The bug is due to the fact one of the two `WidgetHelper` files weren't in sync.
> Fix a bug that would crash the app when creating a 3d scatter chart

- components/widgets/charts/VegaChartLegend.js
- components/widgets/editor/helpers/1d_scatter.js
- components/widgets/editor/helpers/1d_tick.js
- components/widgets/editor/helpers/WidgetHelper.js
- components/widgets/editor/helpers/bar.js
- components/widgets/editor/helpers/line.js
- components/widgets/editor/helpers/pie.js
- components/widgets/editor/helpers/scatter.js
- components/widgets/editor/table/TableView.js
- components/widgets/editor/ui/CategoryContainer.js
- components/widgets/editor/ui/ColorContainer.js
- components/widgets/editor/ui/ColumnBox.js
- components/widgets/editor/ui/FieldsContainer.js
- components/widgets/editor/ui/FilterContainer.js
- components/widgets/editor/ui/SizeContainer.js
- components/widgets/editor/ui/SortContainer.js
- components/widgets/editor/ui/ValueContainer.js
- utils/widgets/1d_scatter.js
- utils/widgets/1d_tick.js
- utils/widgets/WidgetHelper.js
- utils/widgets/bar.js
- utils/widgets/line.js
- utils/widgets/pie.js
- utils/widgets/scatter.js
This PR displays the aliases of the fields when present in the widget editor. The aliases can be seen for the "Chart" visualisation type and for the table as well.
You can test the feature with this dataset: `f2fe7588-6d1b-400e-b79c-0c86bf1273ea `.
> Display the aliases of the fields in the editor whenever possible

- components/app/pulse/LayerCard.js
- components/vis/Globe.js
- pages/app/Pulse.js
- redactions/pulse.js
- Bug fixed: state was not reset when leaving the page and thus the layer card of the last active layer stayed there when clicking on the 'Back' button of the browser.
- Lights test: The layers for Volcanos has now a red light for every Volcano object
- Number of 3D objects: The layer card includes now the number of 3D objects that are present on the globe
> Planet Pulse improvements

- components/app/explore/DatasetList.js
- components/app/explore/DatasetWidget.js
- css/components/app/pages/explore.scss
- pages/app/Explore.js
This pull requests includes:
- Allow users to filter by the dataset tags by clicking on them in the tags tooltip
- Sum up of the filters applied when the filters selectors are hidden
- Filters section is open on page load when filters are specified in the URL
> Improve filtering in Explore: tags + filters revamp

- components/admin/datasets/pages/show.js
- components/admin/layers/LayersTab.js
- components/admin/layers/pages/new.js
- components/admin/layers/pages/show.js
- components/admin/layers/table/LayersTable.js
- components/admin/layers/table/td/NameTD.js
- components/admin/widgets/WidgetsTab.js
- components/admin/widgets/pages/new.js
- components/admin/widgets/pages/show.js
- components/admin/widgets/table/WidgetsTable.js
- components/admin/widgets/table/td/TitleTD.js
- components/app/myrw/widgets/WidgetsTab.js
- pages/admin/DataDetail.js
- redactions/admin/widgets.js
> Fix: navigation issue when you create layers or widgets

- services/DatasetService.js
These endpoints are now requesting `published` datasets explicitly as well as including datasets with both `production` and `preproduction` environments.
> Update graph endpoints: search and similar datasets

- components/widgets/editor/helpers/bar.js
- utils/widgets/bar.js
It actually seems to be a bug from Vega: the null values are computed as "0" but don't count in the calculation of the y scale. That causes the bar to overlap the x axis when the the option "zero" is set to false in the vega configuration. After talking with Alicia, the vertical scale should always start with 0, so the problem is easily fixed.
[Pivotal task](https://www.pivotaltracker.com/story/show/151603686)
> Fix an issue where bars could overlap the x axis

- CHANGELOG.md
- components/widgets/editor/helpers/bar.js
- utils/widgets/bar.js
This PR modifies the bar chart to properly handle negative values. In addition, if any negative value is present in the dataset, a horizontal line is drawn at 0 to mark the change of sign.
> Support negative values in the bar chart

- css/components/widgets/widget_card.scss
The charts would be forced to take their container's full width and height whereas the bar and pie charts determine their sizes by themselves. This would distort them.
[Pivotal task](https://www.pivotaltracker.com/story/show/151472665)
> Fix the distorted charts in My RW > My widgets

- components/app/myrw/widgets/pages/new.js
- components/ui/SliderSelect.js
- components/widgets/editor/WidgetEditor.js
- components/widgets/editor/chart/ChartEditor.js
- components/widgets/editor/helpers/WidgetHelper.js
- components/widgets/editor/nexgddp/NEXGDDPEditor.js
- components/widgets/editor/raster/RasterChartEditor.js
- components/widgets/editor/services/RasterService.js
- components/widgets/editor/ui/AreaIntersectionFilter.js
- components/widgets/editor/ui/SliderSelect.js
- services/RasterService.js
- utils/widgets/WidgetHelper.js
This PR makes changes to the area intersection filter of the widget editor:
* the component is now decoupled from each individual editor (standard, nexgddp, etc.)
* the component has been added to the editor of the raster datasets
* the user must use it to render a chart or the table of a nexgddp dataset
* an issue has been fixed where, in certain cases, the filter wouldn't be restored
You can try to use it with this raster dataset (`8ecf07f5-3cae-4275-adfe-918d04439a1a`) or this nexgddp one (`5e11f2ae-77e8-4f1a-bd28-ad9e4ec97f01`).
> Area intersection filter changes in the widget editor

- components/ui/Tooltip.js
The tooltip has an option to determine in which direction we want to open it. I noticed that when opened towards the top, it's position was miscalculated. This PR fixes the issues.
> Fix the tooltip's direction not taken into account

- css/components/form/field.scss
This could happen due to the inline loaders used for example for the area intersection filter.
[Pivotal tracker](https://www.pivotaltracker.com/story/show/150479167)
> Prevent the content of the editor from jumping

- components/widgets/editor/helpers/WidgetHelper.js
- components/widgets/editor/ui/ColumnBox.js
The method that computes the query would inadvertently mutate the store and change the name of the column used to sort the data, when adding and then removing an aggregation function on the "value" column.
The issue has been fixed by copying the store's object that was being mutated.
You can reproduce the issue following these steps:
1. Choose whatever dataset you'd like.
2. Make a pie chart of it.
3. Sort the data with the field used in the "value" column.
4. Add an aggregation to the "value" column.
5. Remove the aggregation (choose the option "none").
6. Voila, the chart doesn't render because the query is wrong (look at the `GROUP BY` part).
> Fix a bug where the editor would generate a malformed query

- components/admin/widget/form/steps/Step2.js
- components/admin/widgets/form/WidgetsForm.js
- components/admin/widgets/form/steps/Step1.js
- components/app/myrw/widgets/pages/edit.js
- components/app/myrw/widgets/pages/new.js
- components/modal/SaveWidgetModal.js
- components/widgets/editor/WidgetEditor.js
- components/widgets/editor/chart/ChartEditor.js
- components/widgets/editor/modal/SaveWidgetModal.js
- components/widgets/editor/nexgddp/NEXGDDPEditor.js
- components/widgets/editor/raster/RasterChartEditor.js
- components/widgets/editor/redux/widgetEditor.js
- css/components/widgets/vega_chart_legend.scss
- css/components/widgets/widget_editor.scss
This PR makes sure the name of the widget is shown in the editor and that whenever it is updated, the title of the chart also is (the other direction is also true).
[Pivotal task](https://www.pivotaltracker.com/story/show/151751570)
> Editor: sync the title of the chart with the widget's name

- css/components/form/form.scss
This PR fixes a bug that seems to only affect Firefox' users: the editor would horizontally overflow and the user wouldn't be able to use some options such as the advanced editor because it's absolutely positioned to the right of the editor.
> Prevent the editor from overflowing its container in the admin

- components/widgets/charts/VegaChart.js
The `VegaChart` component would fetch the data each time the state or the props would be updated. This kind of code is wrong: there should be a condition to check whether updating is useful or not.
I deleted the `componentDidUpdate` method and did some tests (embed, editor, explore) and it seems nothing is affected by the change.
> Prevent the raster embeds from fetching data infinitely

- css/components/app/pages/embed/embed_widget.scss
The band information and statistical tables wouldn't be aligned like the rest of the content (and the other embeds).
Previous alignment of the embed:
</p>
> Improve the styles of the raster embeds

- selectors/explore/layersExplore.js
For some reason, someone was accessing the explore page with a layer that comes from a non-existing dataset (probably because it was removed). Because of that, the app would crash.
You can replicate the issues by going to [this URL](https://staging.resourcewatch.org/data/explore?page=1&layers=%255B%257B%2522dataset%2522%253A%252232213dbc-2ec1-4579-a9c8-21afa2793bb6%2522%252C%2522visible%2522%253Atrue%252C%2522layers%2522%253A%255B%257B%2522id%2522%253A%25226f1f8b5d-a6ba-436f-a7bf-b6812d0f3a20%2522%252C%2522active%2522%253Atrue%257D%255D%257D%255D&search=drou).
This PR makes sure that if the dataset is not found, we just skip it.
[Opbeat error](https://opbeat.com/vizzuality/resource-watch/errors/116/)
> Prevent the app from crashing when the URL contains a non-existing dataset

- components/widgets/editor/raster/RasterChartEditor.js
- css/components/widgets/raster_chart_editor.scss
This PR updates the layout of the raster editor so more content can fit and it doesn't overflow.
> Prevent the content of the raster editor from overflowing

- components/ui/Tooltip.js
- css/components/ui/tooltip.scss
This PR improves the position of the tooltip when displayed on either side of the screen: the tooltip is not cut anymore but gets "pinned" to the side and its tip is moved proportionally to point the desired position.
This behaviour hasn't been applied to the top and the bottom of the screen because the tooltip opens in these directions. If needed, we could reverse its direction but I don't think it's currently necessary.
</p>
[Pivotal task](https://www.pivotaltracker.com/story/show/151915521)
> Improve the position of the tooltip on the sides of the screen

- components/app/layout/EmbedLayout.js
- css/components/app/pages/dashboards.scss
- css/components/app/pages/embed/embed_widget.scss
- css/components/map/map.scss
- css/components/ui/legend.scss
- pages/app/embed/EmbedMap.js
- pages/app/embed/EmbedWidget.js
- services/WidgetService.js
This PR improves the layout of the widget (vega) and map embeds as well as the dashboards.
</p>
The table and layer embeds haven't been changed for the following reasons:
* The table one misses a lot of information and context (it's just a table for now) so it might need further changes. Instead of spending time on its layout, let's improve what's displayed first.
* The layer embed needs deeper changes because the legend can open a modal (this is a shared component). The embed won't be able to properly display it so we need to think about the best option.
@pablopareja do you mind creating tasks for these two types of embed so we don't forget to check them later?
Finally, note that some of the widgets of the dashboards still have vertical scrolling. This is because …
> Improve embeds and dashboards layout

- redactions/tooltip.js
This PR fixes a tricky bug that would crash the app: a tooltip could render with the props of a previous one if it's still opened.
What exactly happens is that when we toggle a tooltip, we throw several `dispatch` sequentially. The first one is to change the component that renders inside of the tooltip. Immediately after firing the action with `dispatch`, react would render the content, but with the old props because the action to update the props is fired right after.
Changing the order of the `dispatch` isn't a proper solution because that means the older content could render with props that belongs to the new tooltip. Instead, what we can do is close the tooltip, dispatch all what we need and open it again so the new content only renders when we're sure the props have been updated.
> Prevent the app to crash due to the content of the tooltip

- components/admin/widgets/form/WidgetsForm.js
This PR makes sure the widget editor's store is restored when the user wants to create a new widget in the admin.
It seems that when the user was visiting an existing widget and then would go to the creation page, the name of the previous widget would be displayed until the user select a dataset.
> Prevent the name of a widget from leaking into a new form

- components/admin/widgets/form/WidgetsForm.js
- components/app/layout/Sidebar.js
- components/app/myrw/widgets/pages/edit.js
- components/app/myrw/widgets/pages/new.js
- components/widgets/editor/WidgetEditor.js
- components/widgets/editor/map/Map.js
- components/widgets/editor/modal/SaveWidgetModal.js
- components/widgets/editor/modal/ShareModalExplore.js
- components/widgets/editor/redux/widgetEditor.js
- pages/app/Explore.js
- pages/app/embed/EmbedLayer.js
- pages/app/embed/EmbedMap.js
- redactions/explore.js
- redactions/widget.js
This PR does a few things:
* it saves the position and zoom of the map in the editor so it is correctly restored when editing a widget or in the map embed
* it saves (and restores) the position and zoom of the Explore map in the URL
* it saves (and restores) the position and zoom of the Explore map when embedded
The last commit might be difficult to understand without context: in Explore, when the sidebar is opened and the user centres the map on Madrid, we want to be able to create an embedded map effectively centred on Madrid. Nevertheless, as the sidebar is on top of the map, the real centre is somewhere in the ocean (there's an horizontal offset). The commit adds a bit of code to compute the "perceived" centre of the map so, when shared, the map is centred on Madrid.
[Pivotal …
> Save the position and zoom of the Explore + editor + embeds maps

- components/modal/LayerInfoModal.js
The user should be able to go from the layer info modal to the dataset detail page.
> Add more info button to layer modal

- CHANGELOG.md
- components/widgets/editor/tooltip/ColumnDetails.js
- components/widgets/editor/ui/ColumnBox.js
- components/widgets/editor/ui/FieldsContainer.js
- css/components/widgets/column_details.scss
- css/index.scss
This PR lets the users click the columns of the editor to get some information about them. The tooltip is only shown when the user clicks the columns outside of the containers "Category," "Value", "Filters", etc. to avoid too much interaction in a tiny space.
</p>
You can test the feature with the following datasets:
- `c465b42e-8c22-4dcb-9838-f6447393e28d`
- `d02df2f6-d80c-4274-bb6f-f062061655c4`
[Pivotal task](https://www.pivotaltracker.com/story/show/150545675)
> Tooltip showing the description of the columns in the editor

- components/widgets/list/WidgetActionsTooltip.js
- components/widgets/list/WidgetCard.js
Everything's in the title 😉.
</p>
In My RW, the user has a new action to download a PDF of the widget. The file is generated with its embed page.
[Pivotal task](https://www.pivotaltracker.com/story/show/151872468)
> Let the user download a widget as a PDF

- components/admin/widgets/form/constants.js
- components/widgets/editor/helpers/bar.js
- components/widgets/editor/helpers/line.js
- components/widgets/editor/helpers/pie.js
This PR replaces the templates of the editor's advanced mode by the basic templates used in the editor.
The two reasons behind the change are:
- having the advanced mode in sync with the generated charts
- having thumbnail-ready custom charts
This change is part of a broader task that includes more information on how to customise the charts in the advanced mode:
[Pivotal task (first point)](https://www.pivotaltracker.com/story/show/152108957)
> Replace the editor's advanced mode templates

- components/app/explore/DatasetListHeader.js
- css/components/app/explore/dataset_list_header.scss
- pages/app/Explore.js
- pages/app/ExploreDetail.js
- redactions/explore.js
- selectors/explore/filterDatasets.js
- services/GraphService.js
This PR lets the user sort the datasets in Explore by last modified date (default), most viewed or most favourited. Anytime the user changes the sorting order, the URL is updated so it can be restored later.
In addition, every time a user visits the Explore details page, a query is made to count a view to the dataset.
While testing, I noted that the endpoints used to get the order of the datasets are returning a small number of datasets which aren't displayed in Explore, so changing the sorting order won't actually change the cards order.
@pablopareja Any idea why we don't get useful answers?
[Pivotal task 1](https://www.pivotaltracker.com/story/show/152429987)
[Pivotal task 2](https://www.pivotaltracker.com/story/show/152429883)
> Let the user sort the datasets in Explore

- components/widgets/editor/WidgetEditor.js
- components/widgets/editor/helpers/WidgetHelper.js
This PR fixes an issue where a widget that was created with columns whose aliases have been renamed since, would still display the old aliases. The issue could also be that the columns didn't have any aliases at that time.
The issue relies on the fact that the aliases and column types are stored within the `widgetConfig` object whereas they can change over time. To address this, the PR makes sure that if the data doesn't coincide, the values are updated with the latest information. Also, if the fields used for the columns "Category", "Value", "Filters", etc. can't be found anymore, they are removed from the editor.
You can test with this dataset (compare the results with `develop`'s): `f8d3e79c-c3d0-4f9a-9b68-9c5ad1f025e4`.
[Pivotal …
> Editor: always check if the restored state is up-to-date

- Dockerfile
- Dockerfile-staging
- next.config.js
This PR fixes a bug where the newest ENV variables `API_ENV` and `GOOGLE_ANALYTICS` would be `undefined` in the browser causing what seems to be unrelated issues.
[Pivotal task (of a bug caused by this)](https://www.pivotaltracker.com/n/projects/1374154/stories/152806171)
> Fix undefined ENV variables in browser

- components/widgets/editor/WidgetEditor.js
This PR filters out the columns of the editor that are not "relevant" when the relevant columns are defined. If no one is defined, then the whole list is displayed (as before).
You can test with this dataset `0b9f0100-ce5b-430f-ad8f-3363efa05481` and compare the list of columns with `develop`.
[Pivotal task](https://www.pivotaltracker.com/story/show/152804387)
> Editor: only show the relevant columns, if defined

- components/widgets/editor/ui/ColumnBox.js
- components/widgets/editor/ui/FilterContainer.js
This PR fixes a bug where the tooltips of the filters would open when restoring the state of the editor.
You can test the issue with this dataset: `f8d3e79c-c3d0-4f9a-9b68-9c5ad1f025e4`.
The solution, while working, is based on the assumption that if a filter has no value, it's because it's just been dropped in the container of the filters. In such a case, the tooltip should open to let the user specify the filter.
I've spent _minutes_ finding a better approach, but it seems none of them is trivial. The problem here is that we need to know when a column has just been dropped vs. it's been added artificially to the container (case of the restoration of the editor's state). When a column is dropped, its instance is deleted and a new instance is created in the container. Linking those two …
> Editor: prevent the filter tooltip from opening when restoring the state

- components/app/explore/DatasetWidget.js
Datasets that had no tags were throwing an exception that resulted in buggy behavior across the page.
[Pivotal task](https://www.pivotaltracker.com/story/show/152880108)
> Explore bug fix for datasets that have no tags

- components/widgets/editor/WidgetEditor.js
- components/widgets/editor/helpers/WidgetHelper.js
- components/widgets/editor/services/DatasetService.js
- components/widgets/editor/ui/ColumnBox.js
- services/DatasetService.js
- utils/widgets/WidgetHelper.js
The featureservice datasets have fields whose types all start with `esriXXX`: `esriFieldTypeString`, `esriFieldTypeGeometry`, etc. When trying to drag a column with one of those types in the filter container, the tooltip would never finish to load. The issue is that we were managing two types of fields in the editor:
1. The real types of the fields, such as `esriFieldTypeString`
2. Simplified types, such as `string`
This PR makes sure that we always use the simplified types from the start (when fetching the fields), so we can remove inconsistencies (= bugs). In addition, the type `string` would be sometimes called `text`, so now it's always `string`.
As a result, the user can now use `esriXXX` columns to filter a dataset.
You can test the editor perfectly handles `esriXXX` types with this …
> Editor: fix ever-loading filter tooltip with featureservice datasets

- components/widgets/editor/services/DatasetService.js
- package.json
- yarn.lock
This PR fixes two independent issues affecting some layers in the widget editor:
1. The `env` parameter wouldn't be sent with the query retrieving the layers so some datasets would appear with less or no dataset.
2. A special kind of esri layer would fail to render on the map because the `esri-leaflet` dependency had a bug. It's been updated.
1. Go to the Explore Details page of any dataset.
2. Replace the ID in the URL by this one: `ffe316c8-c059-4ed6-a5c9-bc640afe4d0e ` and reload the page.
3. You should be able to display the layer on the map.
None. Bug originally found on PReP.
> Editor: some layers wouldn't appear and some esri ones wouldn't load

- components/widgets/editor/tooltip/FilterTooltip.js
This PR fixes a prop validation error when adding a filter in the editor.
Add a column which has string values only to the filter container and check whether or not there's a prop validation error related to the `FilterStringTooltip` component.
None. Bug detected in PReP.
> Editor: remove a prop validation error

- components/widgets/editor/WidgetEditor.js
If a dataset didn't contain any metadata, we would store the aliases and field descriptions as `0` in Redux because of the binary operators. Instead, a default empty string is now assigned.
This PR also resolves some related prop validation errors.
1. Go to the Explore Details page of this dataset: `45b6a92d-d8b1-49f1-80f6-27d962e7aae4`
2. Hover any column for a few seconds
The tooltip shouldn't contain any `0` below the column's name.
[Task](https://www.pivotaltracker.com/n/projects/1374154/stories/153056618)
> Editor: some "0" could be displayed instead of aliases or field descriptions

- package.json
- pages/app/Pulse.js
The spinner is now being hidden only when a callback is fired from the Map component.
[Pivotal task](https://www.pivotaltracker.com/story/show/153169487)
> Pulse: 3D layers loading improved

- components/widgets/editor/services/DatasetService.js
This bug is a regression from e0433d8 (PR #428). The `cartodb_id` field wouldn't be discarded when retrieving the list of fields which caused two issues:
1. The field would appear in the UI (in the editors `ChartEditor` and `NEXGDDPEditor`)
2. The editor would let the user create a standard chart (with `ChartEditor `) for raster datasets
Open the Explore Details page of this dataset: `16df8ada-87cc-4907-adce-a98bc4e91856 `. You shouldn't see two "Chart" visualisation types.
None, bug found while isolating the editor.
> Editor: "cartodb_id" not hidden and broken UI for the raster datasets

- components/widgets/editor/WidgetEditor.js
The editor is sometimes restored with widgets that use data that isn't available anymore. In such a case, the function `checkEditorRestoredState` makes sure to remove the bits that would cause an issue. Nevertheless, while the widget is being restored, and before its state is checked, the editor would try to render what was in the API.
To avoid this behaviour, a flag has been added in the state of `WidgetEditor`. This flag is set to `true` at the beginning of the initialisation of the editor and is not removed until the state is checked. While this flag is active, the visualisation can't be rendered.
Go to the Explore Details page of this dataset: `de452a4c-a55c-464d-9037-8c3e9fe48365 `. You shouldn't see non-existing columns in the column containers, nor an ever-loading spinner.
First …
> Editor: a widget using outdated data could break the UI

- components/app/explore/DatasetWidgetChart.js
- components/widgets/charts/VegaChart.js
If a widget is saved with a wrong Vega configuration, it would load indefinitely in Explore. Now, in that case, `VegaChart` executes a callback that lets you do the appropriate thing. In this example, we display an empty container.
Unfortunately Alicia fixed the broken widget. You can still see how the card would behave commenting the `try` part in `VegaChart`.
None.
> Display an empty container when a Vega chart fails to load in Explore

- components/widgets/editor/WidgetEditor.js
A regression from dc184c9 (PR #445) made that the editor wouldn't be able to render the widget that it's restoring.
The error comes from the fact that before rendering, we would make sure the props of the editor have changed. Nevertheless, while restoring a widget, at some point the props never change and only the property `initializing` of the state is toggled from `true` to `false`.
Go to the Explore Details page of this dataset: `35ce2b98-adbb-4873-b334-d7b1cc542de7`. The editor is loading and then it correctly displays a graph.
[Task](https://www.pivotaltracker.com/story/show/153313401)
> Editor: frozen while restoring some widgets

- components/widgets/editor/services/DatasetService.js
- components/widgets/editor/services/WidgetService.js
Some services wouldn't have the `application` and/or `env` parameter defined in their queries.
None.
None. Bug found in the [widget-editor](https://github.com/resource-watch/widget-editor).
> Add missing "application" and "env" params to some queries

- components/app/explore/DatasetWidget.js
- components/widgets/charts/LayerChart.js
For some cards of geographical datasets, the basemaps wouldn't be displayed in Explore.
Go to `/data/explore?page=3`. All the cards should show a basemap.
None. Bug reported by Alicia.
> Bug: some basemaps of the explore cards wouldn't be displayed

- pages/app/embed/EmbedMap.js
Non-logged user wouldn't be able to see embedded map widgets due to errors in the code: we would assume the users are always logged in, which is not true. This bug probably is the one that prevents a user from downloading a PDF of a map widget.
1. Open a private browsing window
2. Open this page: `/embed/map/4bed6e21-8ae2-437c-aa01-9ccd861ab4c0`
3. You should be able to see the widget
Probably fix [this task](https://www.pivotaltracker.com/story/show/153281863) but I need to test it once deployed to staging.
> Fix an access issue to the embedded map widgets as an anonymous user

- pages/app/Dashboards.js
- pages/app/DashboardsDetail.js
The back button ("breadcrumbs") located in the header of the dashboard pages has been updated/removed to ensure a correct user flow. In addition, the list of dashboard thumbnails is not displayed anymore in the detail page of a private dashboard.
On the dashboard index page, you shouldn't see any back button in the header, and in the detail page, the button should be called "Dashboards". In the detail page of a private dashboard such as `my-dash`, the thumbnail list shouldn't be visible.
[Task 1: back button](https://www.pivotaltracker.com/story/show/153368227)
[Task 2: thumbnail list](https://www.pivotaltracker.com/story/show/153367652)
> Small layout changes to the dashboards

- components/admin/widgets/form/steps/Step1.js
- components/app/myrw/widgets/pages/new.js
- components/widgets/editor/WidgetEditor.js
The `WidgetEditor` contained a prop called `onError` whose purpose is wrong. Instead of notifying of an error, it just notified that either the fields didn't load or the layers. *In any case that means that the editor can't work properly.* Raster datasets don't have fields for example.
This prop would be used in the admin preventing the creation of widgets with raster datasets and would throw an error in My RW for the same datasets. To fix the issue, the prop has been deleted. 
Note that the new version of the editor is not affected by this.
1. Go to `/admin/data/widgets/new?dataset=ff1425a9-4793-4ac2-99e5-7bdf87114cc7`
2. You should see the widget editor
1. Go to `/myrw-detail/widgets/new`
2. Select the dataset "Average Annual Precipitation (1971-2000)"
3. You shouldn't see any toastr …
> Bug: raster widgets couldn't be created properly

- pages/app/ExploreDetail.js
The description field has been moved below the widget editor. We are now showing 'Function' at the top instead.
[Pivotal task](https://www.pivotaltracker.com/story/show/153553616)
> Explore Detail: reorder metadata fields

- components/datasets/table/DatasetsTable.js
- components/datasets/table/td/CodeTD.js
A new column has been added to the back office datasets table that displays the RW ID
Go to `/admin`
[Pivotal task](https://www.pivotaltracker.com/story/show/153542856)
@mbarrenechea we need to fix the sorting for columns that are not displaying direct children of the dataset object: https://www.pivotaltracker.com/story/show/153592166
> Back office: Add code to datasets table

- css/components/app/pages/splash_detail.scss
- pages/app/SplashDetail.js
1. Close overlay on click outside of the text/widgets container
2. Set a minimum width for the central container
> Coral splash page: visual updates

- components/admin/tags/TagsForm.js
- services/GraphService.js
This PR fixes the Dataset tags form _(prior to this clicking in the button "Save" had no effect whatsoever)_
The request used to update the tags of a dataset has also been updated so that it uses *DELETE* when it's sending an empty array of tags.
> Dataset Tags form fixes

- components/admin/tags/TagsForm.js
Fix: we're not sending a request anymore when the selected tags are empty and the last tags loaded were also empty.
Try to save the TagsForm for in a dataset with no tags without selecting any new tag
[Pivotal Task](https://www.pivotaltracker.com/story/show/153850273)
> Fix for TagsForm

- pages/app/ExploreDetail.js
Fix for similar datasets tags tooltip _(some obsolete code has also been removed)_
Check the Explore detail page of any dataset, for instance: `http://localhost:3000/data/explore/63f34231-7369-4622-81f1-28a144d17835`. Go to the similar datasets section, click on the tags icon and click in any of the tag pills shown.
@davidsingal  There's a problem with the load of the Explore page though... it loads with a huge scroll when, in theory the page should not have any scroll at all 🤔 
It looks like it somehow _inherits_ the page size of the Explore Detail page. 
None, bug found by @pablopareja
> Fix for Explore Detail page

- css/components/app/explore/explore_layers_tooltip.scss
Check [this url](http://localhost:3000/data/explore?page=1&layers=%255B%257B%2522dataset%2522%253A%2522223b936e-06b8-4970-abd9-4f123904d95d%2522%252C%2522visible%2522%253Atrue%252C%2522layers%2522%253A%255B%257B%2522id%2522%253A%25220ac7bf69-388a-48b0-a869-c3240031c4bf%2522%252C%2522active%2522%253Afalse%252C%2522opacity%2522%253A1%257D%252C%257B%2522id%2522%253A%25224727b1ce-217a-4ebd-9018-596b17752226%2522%252C%2522active%2522%253Atrue%252C%2522opacity%2522%253A1%257D%252C%257B%2522id%2522%253A%2522b898f1f0-fb8e-40b6-ba39-9cdce7c32c34%2522%252C%2522active%2522%253Afalse%252C%2522opacity%2522%253A1%257D%252C%257B%2522id%2522%253A%2522699062bd-9d77-45f1-a380-b16f8bf8c9d6%2522%252C%2522active%2522%253Afalse%252C%2522opacity%2522%253A1%257D%252C%257B%2522id%2522%253A%2522e25191e9-8150-4371-8 …
> Fix for Explore bug: Layer selector can extend beyond the top of the screen on smaller displays

- components/app/explore/explore-dataset-filters/explore-dataset-filters-actions.js
- components/app/explore/explore-dataset-filters/explore-dataset-filters-component.js
- components/app/explore/explore-dataset-filters/explore-dataset-filters-constants.js
- components/app/explore/explore-dataset-filters/explore-dataset-filters-reducer.js
This PR temporarily hides the Geographies filter from the Explore.
Check the [Explore page](http://localhost:3000)
[Pivotal task](https://www.pivotaltracker.com/story/show/154118304)
> Hide the geographies filter from the Explore page

- components/app/myrw/areas/AreasTab.js
- components/app/myrw/areas/pages/index.js
- components/app/myrw/areas/pages/new.js
- components/areas/AreaCard.js
- components/areas/AreasForm.js
- components/areas/AreasList.js
- components/modal/AreaSubscriptionModal.js
- components/modal/SubscribeToDatasetModal.js
- components/subscriptions/SubscriptionSelector.js
- pages/app/ExploreDetail.js
- pages/app/MyRW.js
- pages/app/MyRWDetail.js
Fixes for the following two bugs:
- From dataset detail: subscribe to alerts
- Select a country AOI that you don't currently have, or upload new custom AOI
- Subscription is a success
- Bug: no subscription was created, AOI now in personal area
- Repeating will add the subscription since it's in your areas already.
- From dataset detail: subscribe to alerts
- Select an AOI for which you have existing subscriptions
- "There already exist a subscription for the selected area. Do you want to update it?"
- bug: Goes to AOI page with modal, options cleared, infinite loop.
Test any of the two scenarios aforementioned in the Explore Detail page of a subscribable dataset such as _*Earthquakes over the last 30 days*_
[Pivotal Task](https://www.pivotaltracker.com/story/show/153892133)
> Fixes for Subscription / AOI bugs from dataset detail page

- components/app/pulse/LayerCard.js
- pages/app/ExploreDetail.js
This PR includes a couple of updates related to the `subscribable` attribute. 
Explore detail and Planet Pulse pages have been modified so that they no longer show as subscribable datasets that had an empty object stored for that attribute.
Have a look at this dataset for instance: localhost:3000/data/explore/a7067e9f-fe40-4338-85da-13a6071c76fe
> Fix for subscribable attribute

- components/app/myrw/widgets/MyRWWidgetsMy.js
- components/widgets/list/WidgetActionsTooltip.js
- components/widgets/list/WidgetCard.js
- css/components/app/pages/embed/embed_widget.scss
- css/components/widgets/widget_actions_tooltip.scss
- pages/app/embed/EmbedWidget.js
- redactions/widget.js
This PR surfaces to app site the widget links that can be created from the metadata section in the back office. 
They are visible now in the following two pages:
1. `Profile --> My Widgets` section as part of the Widget Actions tooltip:
2. Embed Widget page in the flipcard
> NOTE: The title hyperlink of the widget embed page is deactivated when there exist `widgetLinks` defined.
Check the two pages mentioned above using a widget for which you've defined a set of widget links.
> Surface widget links

- components/admin/widgets/form/WidgetsForm.js
- components/admin/widgets/form/steps/Step1.js
- components/admin/widgets/pages/show.js
- css/components/admin/widget/form.scss
- services/WidgetsService.js
- utils/getQueryByFilters.js
- utils/widgets/WidgetHelper.js
This PR includes the logic needed to freeze widgets. 
> NOTE: This process cannot be undone, once a widget has been frozen the graphical part of it cannot be changed.
Create/update a new widget and select the `freeze` checkbox.
> Freeze widget feature

- components/datasets/table/DatasetsTable.js
Go to the admin home page: http://localhost:3000/admin and check that the datasets shown are those which have `published=true` or whose owner is a user with `ADMIN` role.
> Back office: Show datasets that either are published or whose owner is an ADMIN

- components/modal/EmbedMyWidgetModal.js
- components/ui/Modal.js
- components/widgets/list/WidgetCard.js
- css/components/modal/embed_my_widget_modal.scss
- css/components/ui/modal.scss
This PR adds two social media buttons - Facebook and Twitter - to the share widget modal. It also updates the design so that it complies with the layout used in other share modals.
Finally it changes the size of the close icon in all modals _(it was too big before this change)_
Go to Profile --> Widgets --> My Widgets/Starred Widgets and click in one of the actions Share/Embed
> Add media buttons to share widget modal

- components/widgets/editor/ui/Legend.js
This PR adds the possibility to display in Explore the timeline of any given dataset having a set of layers with the following attributes inside the `layerConfig` object:
- `timeline`: should be equals to `true` for the layers that should be part of the timeline
- `order`: number that will be used to calculate the position of the layer in the timeline
Check any of these two datasets in Explore:
- c0c71e67-0088-4d69-b375-85297f79ee75
- b8307c16-fd77-4e35-9b68-8726a025f401
or experiment with other datasets adding the _*timeline*_ capability to them following the instructions mentioned above.
> Timelines: layer order

- components/areas/AreaCard.js
- components/modal/AreaSubscriptionModal.js
- components/modal/SubscribeToDatasetModal.js
- components/subscriptions/SubscriptionSelector.js
- css/components/app/pages/splash_detail.scss
- pages/app/SplashDetail.js
- utils/splash/Panoramas.js
This PR a few updates for the Splash Coral page:
- Update version of the dead scenario background
- Set a bigger width for the text section in the hotspot detail menu
- Hide googles VR mode button
- Move the scenario selector to the right hand side of the screen
- Fix the z-index of the intro container
Go to the following address: http://localhost:3000/splash/coral
> Splash coral --> a few tweaks

- components/dashboards/wysiwyg/widget-block/widget-block-actions.js
- components/dashboards/wysiwyg/widget-block/widget-block-component.js
- components/dashboards/wysiwyg/widget-block/widget-block.js
- css/components/app/pages/embed/embed_widget.scss
- css/components/dashboards/dashboard-card.scss
This PR adds the widget links - when present - to the flipcard of widget blocks from dashboards.
Check the widget *_Forest Restoration Opportunity by Type_* from the forest dashboard --> http://localhost:3000/data/dashboards/forest-new
> Widget links appear now in the cards that are part of the dashboards

- components/ui/Legend.js
- pages/app/Explore.js
- pages/app/embed/EmbedLayer.js
This PR removes the layer selector in Explore layer embed pages.
Check [this link](http://localhost:3000/embed/layers/?layers=%5B%7B%22dataset%22%3A%22ad7a5641-57bc-417d-8acf-8dc9df398779%22%2C%22visible%22%3Atrue%2C%22layers%22%3A%5B%7B%22id%22%3A%22d8f78b42-cc9f-4f8c-939c-1afa57f6c7d6%22%2C%22active%22%3Atrue%7D%2C%7B%22id%22%3A%227f37560a-f4c4-4edc-a253-92226cada782%22%2C%22active%22%3Afalse%7D%2C%7B%22id%22%3A%22cf23dbd1-5944-4971-9701-3199673a8eb6%22%2C%22active%22%3Afalse%7D%2C%7B%22id%22%3A%2214087086-49d0-4260-b40c-797ebaef662e%22%2C%22active%22%3Afalse%7D%5D%7D%5D)
> Remove layer selector from Explore embed pages

- components/app/myrw/widgets/pages/edit.js
- components/app/myrw/widgets/pages/new.js
- css/components/app/pages/myrw/myrw_widgets_edit.scss
- css/components/app/pages/myrw/myrw_widgets_new.scss
This PR removes the fields: authors, source name, source url that are no longer used.
New or Edit widget in the profile section
> Remove widget obsolete fields

- components/app/layout/head.js
- css/components/app/pages/embed/embed_dataset.scss
- css/index.scss
- pages/app/embed/EmbedDataset.js
This PR rescues the `EmbedDataset` page and also makes sure that the bar widgets are properly shown.
Check the following url: https://staging.resourcewatch.org/embed/dataset/5e87d53c-10d9-419e-a0e6-122e26b064ca
> Rescue EmbedDataset page and fix how bar charts are displayed in it

- components/app/explore/DatasetList.js
- css/_base.scss
- css/_foundation_settings.scss
- css/_settings.scss
- css/components/app/pages/embed/embed_widget.scss
- css/components/dashboards/dashboard-card.scss
- css/components/form/field.scss
- css/components/form/toggle-search.scss
- css/components/ui/button.scss
- css/components/ui/custom_select.scss
- css/components/ui/tree_selector.scss
- css/components/widgets/filter_tooltip.scss
- css/components/widgets/widget_editor.scss
- css/index.scss
- css/layouts/_footer.scss
- css/layouts/_page.scss
- yarn.lock
It seems that we are using other libraries that, at the same time, they are using foundation grid (wysiwyg for sure).
What I did is to put the foundation grid at the bottom of the index page to be sure that we are going to override other styles related. The best solution should be to:
1. Namespace for grid used in wysiwyg
2. Avoid using foundation in wysiwyg
Go to /data/explore page to see that the grid is working now
Go to /data/explore/:id page to see the grid working as before
https://www.pivotaltracker.com/story/show/154762200
> Foundation settings working

- css/components/app/pages/explore_detail.scss
- pages/app/ExploreDetail.js
- utils/partners/partnersConnections.js
This PR adds a JSON file where the connections among partners and datasets are stored. It also shows the logo of the partner in the Explore detail page when it corresponds.
Check this dataset e.g. --> `c61c364b-1d68-4dd9-ae3d-76c2a0022280`
> Explore detail: Add partner logos

- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-card-component.js
- components/widgets/list/WidgetActionsTooltip.js
- components/widgets/list/WidgetCard.js
Allows users to only show *edit* or *remove* buttons for widgets and datasets when they are the creator of those resources.
**Create widget and datasets (options available):**
**Favourite the widgets and datasets of other users (options unavailable):**
[Parallel Prep app task](https://www.pivotaltracker.com/n/projects/1598595/stories/154366562)
> Update edit and delete authorisations for widgets and datasets

- redactions/user.js
This PR prevents calling for collections and favourites if user is not present
> Do not call collections and favourites if user is not present

- components/ui/map/Map.js
- components/ui/map/constants.js
- components/ui/map/controls/BasemapControl.js
- redactions/explore.js
This PR let the user choose between a light and dark themed labels layer on the Explore map and let them toggle a new boundaries layer.
Go to the Explore page, toggle on and off the labels and boundaries.
[Task](https://www.pivotaltracker.com/story/show/155029294)
> Explore: add new options for the labels and boundaries layers

- pages/app/Pulse.js
This PR fixes a bug triggered when going from P.Pulse to other pages using the header menu.
> Planet Pulse bug fix

- components/ui/map/Map.js
- pages/app/Explore.js
This fix will disable scrollZoom for the map component by default, so we do not block the default page scroll. Added property `disableScrollZoom` in case this should be activated in another case. 
Scroll over the map on this page: https://staging.resourcewatch.org/data/dashboards/climate for example, scroll should not trigger the map zoom.  
https://www.pivotaltracker.com/story/show/155229709
> disable scrollZoom by default for map widget

- css/components/widgets/widget_card.scss
we only need to add the wrap property and the buttons will be adjusted, also the `30px height` is already calculated on the button so no need to calculate it again! 
https://www.pivotaltracker.com/story/show/155392123
> BUG: fix flexbox issue for responsive widget card

- components/ui/legend/legend-component.js
- components/ui/legend/legend-list/legend-item/legend-item-component.js
- components/ui/legend/legend-list/legend-list-component.js
- pages/app/embed/EmbedMap.js
- redactions/widget.js
- utils/utils.js
Allow these settings to be turned off/on when embedding a map: 
disableZoom=0|1, defaults to enabled
legendExpanded=0|1, defaults to hidden
hideTimeline=0|1 defaults to shown 
example url: `http://localhost:9000/embed/map/8b931d66-cecc-4061-840c-deeaa40294f1?disableZoom=0&legendExpanded=1&hideTimeline=1`
Enter one of your widgets and grab the url, then start modifying these parameters `?disableZoom=0&legendExpanded=1&hideTimeline=1`
Make sure the page does not break when removing the parameters or using a weird value
https://www.pivotaltracker.com/story/show/155698396
https://www.pivotaltracker.com/story/show/155698328
> add query params to map embed for changing embed settings

- components/splash/layout/Header.js
- pages/app/Splash.js
- pages/app/SplashDetail.js
coral view, fix link to earth view, & hide skip intro button 
had to use a `classic href` for the earth view, as we need it to render on the client for the Map component. 
https://www.pivotaltracker.com/story/show/155774893
> coral splash view bug fixes

- components/wysiwyg/widget-block/widget-block-component.js
- css/components/dashboards/dashboard-card.scss
This PR adds support to widgets of type `embed` in the topic pages.
Check the forests topic page as an example: http://localhost:3000/topics/forests _Forests cover 42% source watersheds for the largest 100 cities widget_
> Topic pages --> support for widgets of type embed

- components/app/myrw/widgets/my-rw-widgets/my-rw-widgets-component.js
- components/app/myrw/widgets/pages/index.js
- components/widgets/list/WidgetActionsTooltip.js
- components/widgets/list/WidgetCard.js
- components/wysiwyg/widget-block-edition/widget-block-edition-component.js
- css/components/widgets/widget_card.scss
- pages/app/MyRW.js
This PR renames all 'Widget' labels to 'Visualization`.
Just look for any former references to the word `Widget` across the app.
> Rename "Widget" to "Visualization" across the app

- layout/layout/layout-admin/layout-admin-component.js
- layout/layout/layout-app/layout-app-component.js
- redactions/user.js
This PR adds:
- `token2` to user object. This token won't have Bearer incorporated to it
- Use `token2` in the function `setConfig` of the widget-editor
Upload some areas and find them in the area dropdown of the widget-editor
https://www.pivotaltracker.com/story/show/156269001
> User: save token without modifications

- layout/topics-detail/topics-detail-component.js
This PR adds a "Similar datasets" section to topic pages.
Check the bottom of any topic page.
> Add Similar datasets to topic pages

- css/components/form/wysiwyg.scss
Added CSS to overwrite quill styles with the base styles to update the dashboards/topic pages to use Lato and base fonts, colors, line height.
View any topics page. Inline styles will need to be manually stripped in editor (e.g. black text).
NA
> Update dashboard styles

- components/app/common/Banner.js
- components/app/common/CardApp.js
- components/app/common/ContactUs/ContactUsForm.js
- components/app/common/ContactUs/constants.js
- components/app/static-pages/get-involved/post-content/Apps.js
- components/app/static-pages/get-involved/post-content/ContributeData.js
- components/app/static-pages/get-involved/post-content/DevelopYourApp.js
- components/app/static-pages/get-involved/post-content/JoinCommunity.js
- components/app/static-pages/get-involved/post-content/SuggestStoryPost.js
- components/modal/submit-modal/index.js
- components/modal/submit-modal/submit-modal-component.js
- layout/footer/footer-component.js
- layout/get-involved-detail/get-involved-detail-actions.js
- layout/get-involved/get-involved-component.js
- layout/get-involved/get-involved-default-state.js
- layout/static-content/static-content-component.js
- layout/topics/topics-component.js
- pages/app/About.js
- pages/app/ContactUs.js
- pages/app/Faqs.js
- pages/app/Home.js
- pages/app/PartnerDetail.js
- pages/app/Partners.js
Here are a bunch of updates to static pages to bring them in line with the our [final text](http://drive.google.com/drive/u/0/folders/1vOUKEkkPZm-yh70zWgQTtL6ZNtRLcd1-) and structure.
Other minor updates:
- Update routes for get-involved pages that changed when the titles/slugs were edited.
- Update footer links; remove FB (we've decided not to use the FB account but focus on Twitter)
- Update post-content banner for most pages
- Partner detail page now shows description and only shows datasets header if there are datasets
- Add success popup and topics to contact-us
Comments:
- Styles on About page could be improved
Visit pages and test links
NA
> Updates to static pages across site

- css/components/app/pages/splash_detail.scss
- pages/app/SplashDetail.js
This PR adds a grey background while the 360 images are loaded
> Splash coral: use grey as background on load

- layout/footer/footer-component.js
- layout/header/header-default-state.js
Remove the '-and-' from the header and footer links to the topic page.
> Remove 'and' from Food and Agriculture links in header and footer

- css/components/app/pages/splash_detail.scss
- pages/app/SplashDetail.js
Show on splash coral page an icon that indicates that you can perform a drag interaction. 
Same code as before with some small modifications. 
`/splash/coral`
https://www.pivotaltracker.com/story/show/156433743
> bring back drag helper on coral splash page

- css/components/app/pages/home.scss
- css/components/topics/topics-thumbnail-list.scss
- pages/app/Home.js
Addresses issues from this task: https://www.pivotaltracker.com/story/show/156273102
Update all cards in the home page that are fully clickable to use the box shadow and displacement hover effect, removing old hover effect. 
Update styles on the Stories section title and subtitle.
> clickable cards use standard hover styles

- components/ui/map/Map.js
- components/ui/map/MapPopup.js
- css/components/map/map-popup.scss
1. Add max width and min width for map info window to support long content & make data take up at-least 60% of the info window so thats the focus for the user. 
2. Remove any html tags passed as data to the info window, they are passed as strings not elements so simply remove them.
`/explore` and interact with any layer on the map, make sure to test long data content (a layer with description in the info window should work)
There should not be any html tags leaked as data to the info window, and the data should not overflow the info window
https://www.pivotaltracker.com/story/show/156152894
> Map info window UI updates

- layout/explore-detail/explore-detail-buttons/explore-detail-buttons-component.js
Change button styles to `-secondary` to add border around buttons in datasets for better visual alignments.
> border around dataset buttons

- css/components/explore-detail/explore-detail-actions.scss
- layout/explore-detail/explore-detail-buttons/explore-detail-buttons-component.js
- layout/explore-detail/explore-detail-reducers.js
- pages/app/explore-detail/index.js
On explore detail, if partner was present in the sidebar and you go back to explore, enter another dataset, the previous partner was present. 
- Go to explore
- Enter a dataset with a partner
- Go back to explore
- Enter another one without a partner bound to it, or another partner
Expected result: It should not show the previous partner in the sidebar. 
https://www.pivotaltracker.com/story/show/155626424
> FIX / partner state saved if entering another dataset

- components/datasets/list/component.js
- components/datasets/list/list-item/component.js
- css/components/app/common/partner_block.scss
- pages/app/PartnerDetail.js
- pages/app/Partners.js
- redactions/partnerDetail.js
- implement **WRISerializer** for partnerDetails, so we have the correct data format for the datasets.
- Add condition checks for widget, layer so the page does not break if `undefined` values are returned, this can happen on load
- Tall partner images overflowed their containers, added max height to prevent that
- Some linting while at it
`http://localhost:9000/about/partners/unep` for example, make sure you see the corresponding datasets
https://www.pivotaltracker.com/story/show/156482929
> FIX / issues with partner pages not showing their corresponding datasets

- components/modal/LayerInfoModal.js
- components/vis/globe-cesium/component.js
- layout/explore-detail/explore-detail-helpers.js
- layout/pulse/layer-card/component.js
- layout/pulse/layer-pill/actions.js
- layout/pulse/layer-pill/component.js
- services/LayersService.js
Fix general omit errors, and planet pulse cashed layers not disappearing when array of layers gets cashed.
weird planet pulse bug fixed, so when multiple contextual layers are present, something within cecium cashed the old layers, so when there is an array of *0* elements sent, it grabs the last cashed version, so added 1 condition in componentWillMount, that ensures we remove all of the layers. 
https://github.com/resource-watch/resource-watch/pull/708/files#diff-e60c893374bedcee91a4392b6b9215f3R160
What that line does, is that it forces the cache to reset and all contextual layers should be removed
https://www.pivotaltracker.com/story/show/156610810
https://www.pivotaltracker.com/n/projects/1374154/stories/155943003
> fix opbeat errors, planet pulse cashed layers stay visible

- components/blog/latest-posts/actions.js
- components/blog/latest-posts/component.js
- components/blog/latest-posts/default-state.js
- components/blog/latest-posts/index.js
- components/blog/latest-posts/reducers.js
- css/components/app/pages/home.scss
Update styles for homepage blog cards and pull separate featured "spotlight" posts vs regular posts. 
Posts aren't showing up on resourcewatch.org right now, and my development environment isn't set up to debug. If this PR doesn't work, the two style changes that are worth making regardless are:
css/components/app/pages/home.scss
```
-      background-color: rgba(0, 0, 0, .7);
+      background-image: linear-gradient(180deg, rgba(22, 22, 22, .5) 0%, rgba(22, 22, 22, .1) 50%);
```
components/blog/latest-posts/actions.js
```
-          image: media && media.media_details.sizes.medium.source_url,
+          image: media && media.media_details.sizes.large.source_url,
```
Load homepage
https://www.pivotaltracker.com/story/show/156642319
> Homepage recent posts (check before merging)

- components/app/common/CardStatic.js
- components/blog/latest-posts/component.js
This PR fixes the 404 due to the links in Next.js instead of regular anchors. If we link to the blog, we need to be sure that we use anchors
> Home: blog posts links

- components/modal/SubscribeToDatasetModal.js
This PR fixes the title shown in the subscription modal, it now shows the metadata title as the first option.
Go to `localhost:3000/data/pulse`, select a subscribable dataset such as Fires and click on the subscriptions button.
> Pulse: fix dataset title shown in the subscription modal

- components/widgets/list/WidgetActionsTooltip.js
- components/widgets/list/WidgetCard.js
This PR removes the "Add to dashboard" widget action.
> MyRW visualizations --> remove Add to dashboard widget action

- layout/explore-detail/explore-detail-buttons/explore-detail-buttons-component.js
This PR hides the "Open in map" button from the explore detail when being on a mobile device. 
Check any explore detail page on mobile for a dataset that has layers.
> Explore detail: hide "Open in map" button on mobile

- components/vis/globe-cesium/component.js
This PR removes the default 3D shape interaction since it had become redundant.
Check the volcanoes layer.
> Pulse --> remove default 3D shape interaction

- components/ui/map/Map.js
Explore map when changing size constraints, not updating correctly (showing black bars)
Go to explore page
1. Add a dataset to the map
2. Minimize the sidebar by clicking on the arrow button
3. A black space is shown as part of the map (this should not happen anymore)
https://www.pivotaltracker.com/story/show/157730395
> fix issue with map not rendering correctly

- components/datasets/search/search-component.js
This PR updates the Explore search drop down so that the type of search used by default is the graph filter instead of the text search - of course this only applies to the cases where concepts are found for the text entered by the user.
Go to the Explore page and search for any given value that will produce concept results.
> Switch order ot appearance of results on the Explore Search

- components/areas/AreasForm.js
- components/areas/UploadArea.js
- components/ui/map/Map.js
- css/components/areas/upload_area.scss
- css/components/form/field.scss
- css/index.scss
- layout/head/app.js
- services/AreasService.js
- services/UserService.js
__Note__: we cant have both the country selector and Upload/Draw values active. So added a new UX element if you select a country from the list. so its clear what action is needed from the user.  Screenshot below:
__Another note__: I thought it was a good idea to show the previous selection still in **blue** on the map. This is so you can compare against your previous geo settings while drawing. Screenshot below:
Full Feature with (country geo, drawing map, upload) components:
+ Moved the upload modal out and removed the logic for toggling the modal view. as the new mockups don't require a modal window. 
+ Cleaned up styles, and renamed as the upload component is not a modal anymore. 
1. Fix country selector returning null values in list
Before:
After:
2. When removing selected country …
> FEAT Subscriptions 

- components/admin/widgets/form/steps/Step1.js
- components/charts/widget-chart/index.js
- components/wysiwyg/widget-block/widget-block-component.js
- layout/explore-detail/explore-detail-widget-editor/explore-detail-widget-editor-component.js
- package.json
- pages/app/embed/EmbedDataset.js
- pages/app/embed/EmbedWidget.js
- yarn.lock
This PR upgrades the widget editor version to `1.3.6`.
It also fixes how the Vega theme was being imported across a set of different components.
> Widget editor upgrade

- components/datasets/search/search-component.js
- package.json
- yarn.lock
This PR improves the sorting of the concept filters found as hits for the string entered by the user in the Explore search.
> Improve explore search filter hits sorting

- components/areas/AreasForm.js
when trying to update  your area, your drawing does not get saved
So when trying to update geojson drawing in your area, geostore is always `true` so the new drawing you make is always being ignored.
cleaned up the logic so we dont have to struggle with this again!
> BUGFIX: fix conditions as geojson is always true for areas

- components/areas/AreasForm.js
- components/modal/SubscribeToDatasetModal.js
- components/modal/subscribe-to-dataset-modal/component.js
On planet pulse, we are trying to open the upload area modal that does not exist anymore by passing the parameter `openUploadAreaModal`. This, in the end, returns a `404`. Remove this parameter and just return the new area page. as the upload form now is embedded right there.
> remove areaModal as its deperecated and returns 404

- css/index.scss
- package.json
- yarn.lock
Part of https://github.com/resource-watch/wri-api-components/pull/33.
Removes `rc-tooltip` styles as we are already importing them from `wri-api-components`.
Also, removes duplicated `../node_modules/rc-slider/assets/index` import.
Updates `wri-api-components` to its latest version.
https://www.pivotaltracker.com/story/show/160817619
> Removes unnecessary rc-tooltip styles

- components/ui/map/popup/LayerPopup.js
Allow raster interactivity to be specified with dot notation. For instance:
```
"output": [
{
"column": "x.b1.mean",
"property": "Energy",
"type": "numeric",
"format": "0.00"
}
]
```
http://localhost:9000/data/explore?zoom=2&lat=-5.615985819155327&lng=0.17578125&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522cefd2836-3cc1-43dc-a9d1-bfecf79a6252%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%25220668f151-1116-4a27-bb16-761cf259d3aa%2522%257D%255D&page=1&sort=relevance&sortDirection=-1&search=vegetation
> Allow dot notation for raster interaction

- static/mails/alerts.html
Link to "manage your subscriptions" at the bottom of email changed. Currently it points to https://staging.resourcewatch.org/myrw/areas.
Open alerts.html file and click on "manage your subscriptions" at the bottom of the page (both logged in and logged out). It should redirect you to your areas of interest or log in page respectively.
https://www.pivotaltracker.com/story/show/159927273
---
> manage your suscrip in email pointing to staging/myrw/areas

- layout/footer/footer-default-state.js
- layout/header-admin/header-admin-user/header-admin-user-component.js
- layout/header/header-default-state.js
- layout/header/header-user/component.js
- layout/header/index.js
- routes.js
Fixes a bug when the user was switching sections in the backoffice, the `profile` link started to add the current path to its own path turning out the url something like `/myrw/myrw/myrw/profile`, making it unreachable.
Also, transforms some relative URLs to next routes format.
Also I added some eslinting.
Navigate between different sections in the backoffice.
---
> Fixes profile route

- components/dashboards/list/DashboardsList.js
- components/dashboards/table/DashboardsTable.js
- components/dashboards/thumbnail-list/dashboard-thumbnail-list-actions.js
- pages/app/Dashboards.js
- services/dashboard.js
Fixes dashboard listing in `http://localhost:9000/admin/dashboards`
Go to `http://localhost:9000/admin/dashboards`, you should see all dashboards listed without any filter.
---
> Fixes dahsboard listing

- components/modal/subscriptions-modal/actions.js
- components/modal/subscriptions-modal/dataset-manager/selectors.js
Uses metadata name instead of official name for datasets in subscriptions modal.
Open a subscriptions modal and check datasets name.
https://www.pivotaltracker.com/story/show/163725196
---
> Subscriptions: uses metadata name instead of name

- layout/explore-detail/explore-detail-buttons/explore-detail-buttons-component.js
- layout/explore-detail/explore-detail-buttons/index.js
Fixes a strange behaviour of the buttons depending on where you come from. More details: https://www.pivotaltracker.com/story/show/163713817.
Go to explore/detail/dataset and check `Open map`, `Downlaod`, etc.. buttons.
https://www.pivotaltracker.com/story/show/163713817
---
> Fixes strange behaviour in explore detail buttons

- layout/embed/map-swipe/component.js
- package.json
- yarn.lock
Fixes an issue where map-swipe wasn't showing the layer comparative
Test a couple of different layers like http://localhost:9000/embed/map-swipe?zoom=5&lat=20&lng=75&layers=aad32781-71f2-4ee2-99a8-0d06a7c7e27e,53353f6d-b11f-4ba7-b6cd-9fa441d761e4 and see how they change when the swipe is moved.
https://www.pivotaltracker.com/story/show/163767481
Blocked: https://github.com/Vizzuality/layer-manager/pull/48
**Edit**: blocked removed.
---
> map swipe fix: moves onReady callback to layer manager

- pages/app/explore/index.js
Ensures backward compatibility with most-visited deprecated sorting filter
Go to `http://localhost:9000/data/explore?zoom=5&lat=36.049098959065645&lng=-95.09765625000001&basemap=light&labels=light&layers=[{%22dataset%22:%22c9eadefd-4a06-4f3b-a2eb-3e3f45624c24%22,%22opacity%22:1,%22layer%22:%2282e75226-a316-4462-9d56-f89f596d0d7d%22},{%22dataset%22:%2263a7a997-695d-4629-b6e9-9b169f5c69bf%22,%22opacity%22:1,%22layer%22:%2277ba0a3b-3940-4525-90ad-f1c729bc8673%22},{%22dataset%22:%22a86d906d-9862-4783-9e30-cdb68cd808b8%22,%22opacity%22:1,%22layer%22:%22f0bb4a22-ac63-4cd0-8bea-1ced880add03%22}]&page=1&sort=most-visited&sortDirection=-1`. Everything should be OK.
https://www.pivotaltracker.com/story/show/164441901
---
> Ensures backward compatibility with most-visited deprecated filter

- CHANGELOG.md
- Dockerfile
Docker failed to install app dependencies when it tried to run `canvas` with `node-gyp`. Apparently, a couple of dependencies were missing. I've added them.
Enable Docker app and run `docker-compose -f docker-compose.yml up --build`
–
---
> Adds missing dependencies to Dockerfile

- package.json
- pages/_app.js
- yarn.lock
MyRW: Widget preview didn´t load in Firefox. finallyShim added to provide compatibility shims so that legacy JavaScript engines behave as closely as possible to ECMAScript 6.
Go to /data/widget/ef6ea89e-0a8c-466d-8197-e294985f3e43 (in Firefox)
https://www.pivotaltracker.com/story/show/164958831.
---
> finallyShim added

- layout/app/pulse/layer-pill/actions.js
fetchLayer import fixed in layout/app/pulse/layer-pill/actions.js.
http://localhost:9000/data/pulse (ex hazards -> fires -> population)
---
> fix fetch layer import

- constants/app.js
- pages/_app.js
Avoids fetching topics in `/embed/..` pages as we don't need them.
Go to some `/embed` page, you shouldn't see the fetch.
–
---
> Avoids fetching topics in embed pages

- layout/admin/data-detail/component.js
- layout/app/pulse/layer-pill/actions.js
- services/LayersService.js
- services/dataset.js
- services/widget.js
Fixes a regression where the layout always fetched a layer even when it was about datasets or widgets,  not showing the name of the resource in the header.
Also, adds `fetchWidget` method to new dataset service following the new format.
Finally, some improvement in error handling in fetches.
Go to http://localhost:9000/admin/data/datasets/e7b9efb2-3836-45ae-8b6a-f8391c7bcd2f/edit (in production environment). The header should display the name of the current dataset. Same for widgets and layers if you go to their tabs.
https://www.pivotaltracker.com/story/show/165406297/comments/201731174
@mluena if the PR is approved, please, tell Pablo P. or Tiago G. to deploy to `staging` and dollow the next deploys until `production` if everything works properly. This bug is already on `production` so …
> Fixes wrong fetch in admin data/detail

- components/ui/customtable/CustomTable.js
- components/ui/customtable/footer/TableFooter.js
Condition added to table footer, it doesn´t appear if there are no results.
Go to any of the options in admin (http://localhost:9000/admin/pages) and search until you get no results, table footer must disappear.
---
> Table footer in admin restricted

- components/admin/data/datasets/pages/show/component.js
- components/admin/data/layers/table/component.js
- components/admin/data/widgets/form/component.js
- components/admin/data/widgets/form/constants.js
- components/admin/data/widgets/form/index.js
- components/admin/data/widgets/pages/list/component.js
- components/admin/data/widgets/pages/new/component.js
- components/admin/data/widgets/pages/new/index.js
- components/admin/data/widgets/pages/show/component.js
- components/admin/data/widgets/pages/show/index.js
- components/admin/data/widgets/table/component.js
- components/admin/data/widgets/table/constants.js
- layout/admin/data-detail/component.js
- package.json
- yarn.lock
This PR includes 3 fixes regarding the BO:
- Fixes an issue where the ID of the dataset was wrong after updating a widget and triggered an error. Also, titles in the header updates correctly depending on where you are.
- Fixes filtering of widgets in dataset view.
- Fixes filtering of layers in dataset view.
- ID issue:
Go to any widget, update it. After that you will be redirected to the dataset detail page, click on `edit dataset`: it should load the info of the dataset, before it triggered an error. You can test the flow with https://staging.resourcewatch.org/admin/data/widgets/de877a28-8997-46c2-8e1f-ce6fcf125e5f/edit
- Fixes filtering of widgets in dataset view:
http://localhost:9000/admin/data/datasets/20cc5eca-8c63-4c41-8e8e-134dcf1e6d76/widgets should load only widgets associated …
> Small fixes in BO

- pages/_document.js
Fixes an issue with meta tag values producing content overflow in mobile versions.
NextJS provides a default viewport meta (https://nextjs.org/blog/next-8-0-4#default-viewport-meta-tag) that satisfies our needs so we don't need to add it explicitly unless we need anything else.
Go to https://resourcewatch.org on mobile to see the issue, you should notice the content overflow at first sight.
Run this branch in your mobile, overflow should be gone and content fit in the viewport again. (I've tested on Safari and Firefox in iOS 12.2)
–
---
> Removes default meta viewport

- components/wysiwyg/widget-block/styles.scss
- components/wysiwyg/widget-block/widget-block-component.js
- css/index.scss
Fixes an issue where the centre of the map in the `widgetBlock` component wasn't set properly.
Also, moved styles of the component to component level.
On production env, go to http://localhost:9000/data/dashboards/elise-test-mapathon
You will see this widget (with the wrong centre): 
The expected result is: 
As a reference: http://localhost:9000/embed/map/b93140d4-eef9-47d6-8aab-51ae66772987 is applying properly to the centre of the map.
https://www.pivotaltracker.com/story/show/165538206
---
> Fixes issue setting map center in widget-block

- components/blog/feed/component.js
- components/blog/feed/index.js
- constants/blog.js
- modules/blog/actions.js
This PR updates the request performed to the WP API so that `UNCATEGORIZED` posts are not returned.
Go to http://localhost:9000/ and check the blog posts shown there in the `Latest stories` section. There should be no posts categorized as `UNCATEGORIZED`.
> Prevent blog feed from loading "UNCATEGORIZED" blog posts

- css/index.scss
Moves styles due to `widget-editor` styles were overwriting `vizzuality-components` ones.
Everything should be as usual.
–
---
> Reorganizes styles to avoid override

- components/app/myrw/widgets/tabs/list/component.js
- components/collections-list/index.js
- components/ui/customtable/footer/TableFooter.js
This PR updates the MyRW section so that the pagination toolbar is only displayed when there two or more pages of data. The fix has been applied to the "Visualizations" and "Collections" tabs.
Go to `http://localhost:9000/myrw/widgets/my_widgets` and  `http://localhost:9000/myrw/collections` and make sure that you have less than two pages of results.
> MyRW fix: show pagination tool only when there is more than one page

- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-card-component.js
- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-component.js
- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/index.js
- layout/myrw/component.js
This PR removes a redundant "Explore datasets" button appearing in the Myrw --> Datasets section
Go to `http://localhost:9000/myrw/datasets/my_datasets`
---
> MyRW fix: redundant "Explore datasets" button removed from Datasets section

- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-component.js
- components/app/myrw/widgets/tabs/list/component.js
- components/dashboards/list/DashboardsList.js
This PR improves the messages displayed in several MyRW sections when performing a search that returns no results.
These sections include:
- Visualizations
- Datasets
- Dashboards
Go tp `http://localhost:9000/myrw/widgets/my_widgets`, `http://localhost:9000/myrw/datasets/my_datasets`, and `http://localhost:9000/myrw/dashboards` and search for values that return no hits.
> MyRW: Improvements to search results messages in MyRW

- constants/app.js
This PR fixes the issue that prevented user collections to appear in Explore in some cases.
Go to `http://localhost:9000/data/explore/` or any dataset detail page after logging in the app and verify that your user collections are being displayed in the collections tooltip.
> Fix user collections not being loaded in Explore

- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-component.js
- components/app/myrw/datasets/pages/my-rw-datasets/my-rw-datasets-component.js
- redactions/admin/datasets.js
This PR includes the following fixes and improvements:
- The component uses now the right service `services/dataset` instead of the old approach to handle datasets fetching and deletion as part of the MyRW --> datasets section
- WRISerializer is used now to convert the results from the requests to the appropriate JSON format
- Pagination toolbar is only shown when there are two or more pages of data
- Fix for a bug that prevented successfully loading the user datasets after one dataset had been removed 
Go to `http://localhost:9000/myrw/datasets/my_datasets`
> Improvements for MyRWDatasets and DatasetList components

- components/admin/data/layers/table/actions/delete/component.js
This PR fixes the current erroneous behavior that happens when clicking on any layer row "Remove" link.
Go to `http://localhost:9000/admin/data/layers` and click on the "Remove" link. It shouldn't redirect you to the layer detail page now.
> Fix issue when clicking on Remove layer in the back office

- components/admin/data/layers/form/steps/Step1.js
- components/admin/data/layers/pages/new/component.js
- components/admin/data/layers/pages/new/index.js
- components/admin/data/layers/table/component.js
- components/admin/data/widgets/form/steps/Step1.js
- components/admin/data/widgets/table/component.js
This PR selects by default the corresponding dataset in the dropdown selector both in the new widget and new layer forms.
Go to any dataset page from the back office and click on "New widget" and "New layer" in the respective "widgets" and "layers" tabs.
> Re-enable the pre-populating of the dataset name when creating widget and layers

- components/admin/data/layers/form/LayersForm.js
- components/admin/data/layers/pages/new/component.js
- components/admin/data/widgets/form/component.js
- components/admin/data/widgets/pages/new/component.js
- components/admin/data/widgets/pages/show/component.js
This PR fixes the navigation behavior when clicking “save” button after creating/editing both layers and widgets. Now the app stays on same page rather than navigating back to the list of layers or widgets.
Go to `http://localhost:9000/admin/data/layers/` and `http://localhost:9000/admin/data/widgets/` and create + edit layers and widgets.
> Fix back office navigation on save

- components/admin/data/layers/table/component.js
- components/admin/data/layers/table/td/name/component.js
- components/admin/data/widgets/table/component.js
- components/admin/data/widgets/table/td/title/component.js
This PR fixes the breadcrumbs behavior in the Dataset widgets and layers sections so that they lead to the corresponding dataset page instead of the general table including all datasets.
Go to any widget/layer page in the back office and click on the "Widgets"/"Layers" breadcrumb.
> Back office fix: clicking on widgets/layers breadcrumbs leads to the corresponding dataset page

- layout/app/home/component.js
This PR fixes the link from the "Suggest a story" button in the homepage get involved banner.
Go to `localhost:9000` and click on the "Suggest a story" button from the Get Involved banner
> Fix "Suggest a story" link from button in homepage banner

- components/app/myrw/widgets/tabs/list/helpers.js
This PR fixes the bug in MyRW that was preventing favorite widgets to be displayed in the favorites section.
Go to `http://localhost:9000/myrw/widgets/favourites` and verify that your favorite widgets are loaded and displayed accordingly.
> Fix for favorite widgets not loading in MyRW

- layout/head/admin.js
- layout/head/app/component.js
This PR updates the version of Leaflet CSS used and fixes an issue consisting of the grab pointer not appearing on maps when using Firefox.
Go for instance here http://localhost:9000/data/explore?zoom=3&lat=31.57853542647338&lng=13.0078125&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522815eaa09-d626-495e-91e2-523cb07de475%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522a0cf3282-976c-455c-9352-3cc559dc76c0%2522%257D%255D&page=1&sort=most-viewed&sortDirection=-1 and check that the grab pointer is appearing when using Firefox.
> Leaflet styles updated to 1.3.4

- components/modal/share-modal/share-modal-component.js
- components/ui/map/controls/ShareControl.js
- components/wysiwyg/widget-block/component.js
- layout/app/dashboard-detail/component.js
- layout/app/topics-detail/topics-detail-header/component.js
- layout/app/widget-detail/widget-detail-header/component.js
- layout/embed/dashboard/component.js
- layout/embed/widget/component.js
- layout/explore-detail/explore-detail-header/explore-detail-header-component.js
- layout/explore-detail/explore-detail-info/explore-detail-info-component.js
This PR adds a new button to the share modal that allows users to share by email by means of a `mailto` link.
_NOTE: the mailto params might not be final as they stand now_ 
Go for instance to http://localhost:9000/data/explore , click on the share button and then click on the email option.
> Share by email functionality added to all share modals

- components/modal/layer-info-modal/layer-info-modal-component.js
- components/modal/layer-info-modal/styles.scss
- css/index.scss
- layout/explore/explore-map/explore-map-component.js
This PR updates the "more info" button from the layer info pop-up to direct to `resourcewatch.org/data/explore/[slug]` instead of `resourcewatch.org/data/explore/[id]`
Add any dataset to the Explore page and open the layer info pop up. The "More info" button should link to the dataset detail page using the slug instead of the dataset id.
> Layer info pop-up "more info" button leads to `resourcewatch.org/data/explore/[slug]`

- components/app/myrw/widgets/tabs/list/helpers.js
This PR adds a missing parameter to the request that retrieves the widgets so that it filters out widgets from other apps.
Go to MyRW --> My visualizations and check if widgets from other apps are being loaded.
This PR is related to this comment: https://www.pivotaltracker.com/story/show/166645058/comments/204678608
> Prevent widgets from other apps to be loaded in MyRW

- layout/app/pulse/component.js
- layout/app/pulse/styles.scss
- layout/explore-detail/explore-detail-header/explore-detail-header-component.js
This PR hides the `Last Update Date` field from the Explore detail page when this field has no value.
It also includes a fix for a regression in Planet Pulse that affected the styles of the page.
Go to http://localhost:9000/data/explore/GINI-Index (there should be no last update value field in this case)
and http://localhost:9000/data/explore/VIIRS-Active-Fire-Global-1490086842549 (the last update date should surface in this case)
_To check the fix for the Planet Pulse styles simply go to_ http://localhost:9000/data/pulse
> Surface the Last update date in Explore detail only when this field has a value

- components/ui/map/map-thumbnail/helper.js
- layout/explore/explore-map/constants.js
- layout/explore/explore-map/explore-map-component.js
This PR modifies the style of the timeline when there are more than 5 steps to be displayed _(according to the request made for that specific threshold in the PT task)_
_An issue with layers having the url in the body property has also been fixed as part of this PR_
Before: 
After:
Check the *"National Population"* dataset on Explore http://localhost:9000/data/explore?zoom=3&lat=0&lng=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%25222a8ca4f7-7285-4aed-9ef5-ba1f9c4b653d%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%25221b47db11-8f4e-4e4b-a368-b918f099bffe%2522%257D%255D&page=1&sort=relevance&sortDirection=-1&search=national%20population
> Timeline appearance improved when there are many time steps

- layout/forgot-password/component.js
- services/user.js
Adds `origin=rw` as query param in `reset-password` endpoint.
---
> Adds origin param to reset password

- components/admin/data/widgets/form/steps/Step1.js
This PR fixes the issue that prevented the Widget Editor from being displayed unless the dataset was manually selected in the back office widget form.
1. As admin in production back office, click any dataset
1. Go to Widgets and click "New widget"
2. The widget creator should be displayed
> Fix for issue: Backoffice widget creator only appears when dataset manually selected

- components/modal/layer-info-modal/layer-info-modal-component.js
- components/modal/layer-info-modal/styles.scss
- css/components/explore-detail/explore-detail-info.scss
- layout/app/dashboard-detail/component.js
- layout/explore-detail/explore-detail-component.js
- layout/explore-detail/explore-detail-info/explore-detail-info-component.js
This PR includes the following markdown-related improvements:
1. All links included in markdown supported fields are opened in a new tab now.
2. Bullet lists support
3. Extend markdown support to all fields currently surfaced in the Explore Detail page
You can check this dataset on staging: http://localhost:9000/data/explore/VIIRS-Active-Fire-Global-1490086842549 _See the cautions field for an example of how bullet lists are rendered now_
Related to this one https://www.pivotaltracker.com/story/show/167444891 but also to the need to extend the markdown support to more fields and having the ability to display bullet lists.
> Explore detail: markdown related improvements

- layout/forgot-password/component.js
- services/user.js
Moves `forgottenPassword` method to `axios` and `logger`.
Try the forgotten password process as usual.
---
> forgotten password - moves to axios and logger

- css/components/ui/markdown.scss
This PR fixes an issue that prevented some links to appear correctly.
Go to http://localhost:9000/data/explore/soc_016-African-and-Asian-Conflict-and-Protest-Events and verify that links are in color blue and underlined.
> Fix for Markdown link styles

- components/admin/data/layers/form/LayersForm.js
This PR fixes a problem with the published checkbox in the Layer form. Prior to the fix the published checkbox was always displayed checked regardless of the `published` field value.
> Fix issue with Layer form (published checkbox was always checked)

- components/admin/data/widgets/form/component.js
- components/admin/data/widgets/form/index.js
This PR fixes an issue that prevented the creation of widgets when a user accessed the Widget creation form via a specific dataset.
Go the back office, select a dataset and then go to the widgets section and click "New". You should be able to create a widget now without having any issues.
> Fix "Dataset not found" error when saving widgets

- services/WidgetsService.js
This PR includes a fix for the issue that prevented users from saving widgets from the dataset detail page.
Go to any dataset detail page once you're logged in and try saving the widget shown by default.
> Fix for error saving widgets from dataset detail page

- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-card-component.js
- components/widgets/list/WidgetCard.js
This PR improves the links dataset cards are pointing to when visualizing the datasets included in a user collection in MyRW.
Go to `http://localhost:9000/myrw/collections`, create a collection that includes both datasets that you own and public ones. Check that the cards are pointing to the right pages according to the specification included in the PT tasks linked below.
_This feature should ideally be tested both by a `"normal"` user account and an `admin` account._
_PS: The `delete` button is only shown for normal users on purpose since it makes more sense for admins to manage contents directly from the back office_
> datasets from collections should link to different pages depending on user and ownership

- components/datasets/form/steps/Step1.js
This PR adds a read-only field to the dataset form in the back office showing the applications the dataset is currently associated to.
Check any dataset form in the back office.
> Applications read-only field added to dataset form in the back office

- services/WidgetService.js
This PR prevents the `env` property to have the value `production,preproduction` which was occurring prior to this fix.
Create a new widget in MyRW
> Fix issue with widget creation in MyRW

- components/admin/data/datasets/pages/new/component.js
- components/admin/data/datasets/pages/show/component.js
- components/datasets/form/DatasetsForm.js
- pages/app/explore-detail/index.js
This PR includes the following improvements:
1. Remove front-end 'wall' preventing unpublished datasets to be visible in Explore detail
2. The user should stay in the dataset form page after clicking on save/update
3. Fix for an issue that prevented some fields to appear in the dataset form page from the back office _(e.g. the published check box)_.
1. Try opening the dataset detail page for a dataset that has `published=false`, e.g. the following http://localhost:9000/data/explore/8d84f6c6-8e7d-410e-a408-cbfb2555b35d
2. Go to a dataset form in the back office and try updating/creating a dataset to verify that you're not redirected to the datasets table page.
- https://www.pivotaltracker.com/story/show/168309844
- https://www.pivotaltracker.com/story/show/168309771
> Various improvements for datasets

- services/user.js
This PR fixes the issue consisting of setting wrong `env` values when creating/updating a subscription.
Follow the instructions specified in the PT task mentioned below.
> Prevent wrong env values to be set when creating/updating subscriptions

- components/app/myrw/widgets/tabs/list/initial-state.js
This PR updates the way widgest are displayed so that the most recent are shown first.
Go to `http://localhost:9000/myrw/widgets/my_widgets` and verify that widgets are sorted by their modification date showing the most recent first.
> Myrw --> Vizualizations: show most recent widgets first

- components/areas/AreaCard.js
- components/modal/subscriptions-modal/actions.js
This PR fixes the issue that prevented subscriptions from being displayed in the area cards from the section `Areas of interest` in MyRW.
Go to `http://localhost:9000/myrw/areas` and try creating/updating a few area subscriptions
> Fix issue consisting of subscriptions not showing up in the AOI section

- components/datasets/form/DatasetsForm.js
This PR fixes the issue that prevented new datasets from being successfully created in the back office.
Follow the instructions included in the PT mentioned below. The issue shouldn't appear anymore and new datasets should be created successfully.
> Fix for dataset creation issue

- components/modal/subscriptions-modal/dataset/component.js
This PR fixes the dataset name used in the `Subscribe to alerts` modal from the Explore detail page.
E.g. go to http://localhost:9000/data/explore/VIIRS-Active-Fire-Global-1490086842549 and click on the button `Subscribe to alerts`
> Use metadata title in subscribe to alerts modal from explore detail

- layout/app/newsletter/component.js
This PR adds a checkbox to the Newsletter page according to the specification included in the PT task.
Go to http://localhost:9000/about/newsletter and verify that the new checkbox is displayed and the new field is sent as part of the request.
> Add checkbox to newsletter page

- redactions/user.js
This PR fixes the bug that prevented AOI to be displayed when the user didn't have any subscription set up in the app.
Go to MyRW --> AOI, make sure that you don't have any subscription created in RW and verify that your AOIs are displayed nonetheless.
> Show areas when there are no subscriptions

- components/modal/subscriptions-modal/dataset-manager/component.js
- services/subscriptions.js
1. Fixed warning in the browser console
> Encountered two children with the same key, `815eaa09-d626-495e-91e2-523cb07de475`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
2. Fixed Unhandled Rejection
> Cannot read property 'status' of undefined 
./services/subscriptions.js:33
1. Areas of Interest > Area Options > Edit subscriptions > select two the same Datasets.
2. Fired couple times. Now I can't reproduce.
https://www.pivotaltracker.com/n/projects/1374154/stories/168839729
> Fix couple minor errors in Areas of interest (Account)

- components/search-results/actions.js
Add Google Analytics event to track site-wide search
Type a term in the search box and check Network logs in DevTools.
https://www.pivotaltracker.com/n/projects/1374154/stories/169340835
> Log site search events with GA

- components/dashboards/form/steps/step-1/component.js
This PR adds a checkbox to the http://localhost:9000/admin/dashboards/dashboards/29/edit. Checkbox sets 'is-highlighted' parameter. Based on API docs https://resource-watch.github.io/doc-api/index-rw.html#what-is-a-dashboard i set 'is-highlighted' instead of is_highlighted.
Use staging API. Go to  /admin/dashboards page. Click edit/add dashboard. Check or uncheck Is Highlighted field. Click Save.
---
> Added is-highlighted parameter admin/dashboards/ (add/edit) page

- utils/layers/pulse_layers.js
This PR removes the layer with id `f4897107-5ae5-4685-8eee-cd1a5745a384` from the list of layers available in the Planet Pulse section.
Go to `localhost:9000/data/pulse`.
> Planet pulse: remove obsolete "Forest clearing" layer

- components/admin/data/layers/form/interactions/actions.js
This PR fixes the issue consisting of a wrong initialization of the columns interaction selector from the layer form in the back office.
Go to http://localhost:9000/admin/data/layers/dabcca67-037c-4d11-afc4-69559edec4dc/edit?dataset=de452a4c-a55c-464d-9037-8c3e9fe48365 and verify that all fields appear in the drop-down selector.
> Restore backoffice interaction to provide column names for selection

- layout/app/pulse/component.js
- layout/app/pulse/welcome-modal/component.js
- layout/app/pulse/welcome-modal/index.js
- layout/footer/constants.js
- layout/header/constants.js
This PR adds a welcome modal to the Planet Pulse page plus renames the links from the footer and header to "Near Real-Time Data".
Go to http://localhost:9000/data/pulse
> Changes to the Planet Pulse page

- components/dashboards/form/steps/step-1/component.js
This PR adds a checkbox to the http://localhost:9000/admin/dashboards/dashboards/29/edit. Checkbox sets 'is-featured' parameter. 
Use staging API. Go to /admin/dashboards page. Click edit/add dashboard. Check or uncheck Featured field. Click Save.
⚠️  **This PR is blocked until the following API task has been completed:** https://www.pivotaltracker.com/story/show/170311586
> Added is featured option to admin/dashboards new/edit page

- layout/app/home/component.js
- layout/app/home/index.js
- layout/app/home/styles.scss
- pages/app/home/index.js
This PR adds featured dashboards to the main page and remove topics section from the main page
Go to the homepage. Check "Featured dashboards" section
---
> Main page - topics section to featured dashboards

- layout/app/pulse/layer-menu-dropdown/styles.scss
This PR fixes CSS for dropdown menu on planet pulse page.  
Go to http://localhost:9000/data/pulse
Change browser window size < 780px. Hover data dropdowns.
---
> Planet pulse - css dropdown menu fix (for responsive desctop)

- utils/layers/pulse_layers.js
This PR includes a set of changes made to the `pulse_layers.js` file, which is used as the source to dynamically build the menus of the Near real-time section.
More specifically, dataset ids of datasets that have been unpublished have been replaced with new versions of the dataset.
Also the asylum requests dataset has been removed because we have archived that dataset. It is unpublished and will no longer be maintained.
Go to http://localhost:9000/data/pulse
> Some updates to layers displayed in Planet Pulse

- constants/blog.js
- modules/blog/actions.js
- yarn.lock
This PR changes the `SPOTLIGHT_CATEGORY` from `constants/blog.js` var so that both posts with category id `125` and `15` are retrieved. _This is necessary for the blog migration to a new implementation_
Go to the homepage and check that the `Latest stories` section is loading the expected set of blog stories.
> Minor updates to blog feed to load new Spotlight category

- css/components/ui/modal.scss
This PR fixes the problem when dialogs load dialog temporary load when the page loads first time.
Fixed for Modal element and WidgetModal element. Problem: looks like css sometimes loads with delay and we set modal CSS with transition. 
Since this problem happens in a few components (in widget-editor also), i realized a simple CSS fix that helps to resolve problem in both components and save all transitions and current component code.
This issue reproduces only when the build project is running. Use yarn build and yarn start commands.
Reload the main page a few times. The error is not reproduced. 
---
> Fix the problem when dialogs temporary load when the page loads first time

- components/dashboards/thumbnail-list/styles.scss
- css/components/dashboards/dashboards-subheader-block.scss
- layout/app/home/component.js
This PR fixes the text width for the subheader description block on main page. 
Go to main page. Check the width of subheader boxes.
---
> Added the same width for the main page subheader box.

- layout/explore-detail/explore-detail-buttons/explore-detail-buttons-component.js
This PR fixes the bug that prevented learn more and download buttons to appear in explore detail.
Go to https://localhost:9000/data/explore/wat005c-Access-to-an-Improved-Water-Source-Rural and verify that the `Learn more` and `Download` buttons are displayed.
> Fix explore detail buttons not appearing

- layout/explore/explore-actions.js
This PR replaces the use of `fetch` with calls to the corresponding `services` needed.
Open explore and interact with the page using the different features available in it.
> explore-actions refactored to use services methods instead of explicit calls to `fetch`

- css/components/datasets/list-item.scss
> Fix charts overflowing in explore cards

- components/dashboards/table/DashboardsTable.js
- components/dashboards/table/td/preview/component.js
This PR changes the preview URL for admin dashboards table
Go to http://localhost:9000/admin/dashboards check the dashboards preview links. Follow them.
---
> Changed preview url for admin dashboards

- index.js
This PR sets redirects in the server file so that _old_ topic requests are redirected to the new dashboard pages.
Verify that the following URLs `localhost:9000/topics` and `localhost:9000/topics/topic-slug` are properly redirected.
> Redirects to dashboard pages from old deprecated topic pages

- components/dashboards/template-selector/component.js
This PR temporarily removes the button to clone a topic page into a dashboard as part of the create dashboard form.
> Remove button to clone a topic when creating a dashboard

- components/dashboards/detail/component.js
This PR fixes content update on dashboard-detail page
Go to dashboard-detail page. Click on dashboard in menu. After loading click another dashboard in the menu. The content will be updated.
---
> Dashboad-detail force content update after changing page

- pages/_app.js
Overview
This PR adds additional check for calling featured dashboard and partners requests only once.
Run application. Open Network console. Check requests, that application sends when you change pages. partners and featured dashboards are not calling but you can see data on the website.
- https://www.pivotaltracker.com/n/projects/1374154/stories/171051982
- https://www.pivotaltracker.com/n/projects/1374154/stories/171051927
---
> Featured dashboard + partners requests run after strarting aplication only once

- components/admin/data/layers/form/layer-preview/actions.js
- components/map/selectors.js
- yarn.lock
This PR copies the value of the field `layerConfig --> layerType` to the first level of the layer object, _(this is needed for the `layer-manager` version `2.0.6`)_.
Check the Explore section.
> Mapbox migration: add `layerType` to first level of layer object

- layout/app/pulse/layer-pill/actions.js
- layout/explore/actions.js
- layout/explore/component.js
- layout/explore/explore-datasets/explore-datasets-actions/component.js
- layout/explore/explore-detail/actions.js
- layout/explore/explore-detail/component.js
- layout/explore/explore-detail/explore-detail-header/component.js
- layout/explore/explore-detail/explore-detail-header/index.js
- layout/explore/explore-detail/explore-detail-header/styles.scss
- layout/explore/explore-detail/index.js
- layout/explore/explore-detail/initial-state.js
- layout/explore/explore-detail/reducer.js
- layout/explore/explore-detail/styles.scss
- layout/explore/index.js
- layout/explore/initial-state.js
- layout/explore/reducers.js
This PR includes a first draft of the Explore detail component integrated into the sidebar. The header including the buttons has been included as well as the dataset title. The dataset info is loaded by means of a hook using `userReducer` and `useEffect`.
Go to `localhost:9000/data/explore` and verify that the sidebar shows the Explore detail component when clicking on one of the dataset cards `Details` button.
> Explore detail component plus header buttons

- components/app/myrw/datasets/pages/my-rw-datasets/dataset-list/dataset-list-card-component.js
- components/datasets/list/list-item/component.js
- components/modal/layer-info-modal/layer-info-modal-component.js
- components/subscriptions/SubscriptionCard.js
- components/widgets/card/component.js
- layout/app/pulse/layer-card/component.js
- layout/embed/dataset/component.js
- layout/embed/map/component.js
- layout/explore/explore-datasets/explore-datasets-actions/component.js
- layout/myrw/detail/component.js
- pages/app/explore/index.js
- routes.js
This PR updates the way we were handling routes for **_Explore detail_** and _**Explore**_.
The new approach consists of using the same route for both: `/data/explore` but adding the dataset slug as a parameter in the case of the new Explore detail: `/data/explore/?dataset_slug`.
You should be able now to:
- Navigate directly to a dataset detail page by using the URL:  `localhost:9000/data/explore/?dataset_slug`.
- Reload that page and verify that the Explore sidebar reacts accordingly
- Keep the rest of the Explore parameters that are used for the map as you navigate back and forth from Explore to the new "Explore detail sidebar"
> URL approach for Explore detail updated

- components/datasets/list/list-item/component.js
- layout/explore/explore-datasets-header/explore-datasets-sort/explore-datasets-sort-component.js
- layout/explore/explore-datasets/explore-datasets-tags/component.js
- layout/explore/explore-detail/component.js
- layout/explore/explore-detail/explore-detail-header/component.js
- layout/explore/explore-detail/explore-detail-header/styles.scss
- utils/tooltip.js
This PR implements the feature to "save" a dataset into a collection from the new Explore detail section.
_NOTE: It also creates a new file `utils/tooltip.js` to centralize code that was repeated in different components across the app._
Go to a dataset detail's page and click on the `SAVE` button.
> Explore detail: save button connected to collections tooltip

- layout/explore/explore-detail/further-information/component.js
- layout/explore/explore-detail/further-information/styles.scss
This PR adds the following fields to the metadata page:
- Geographic coverage
- Frequency of updates
- Published language
Open explore and select any given dataset.
> New explore metadata fields

- css/_settings.scss
- layout/explore/component.js
- layout/explore/explore-discover/component.js
- layout/explore/explore-discover/index.js
- layout/explore/explore-discover/styles.scss
This PR adds the main layout for the `Discover` section. We can't make more progress on this until it's decided how we are going to load (and if we can) for each of the suggested sub-sections.
Go to localhost:9000/data/explore?section=Discover
> Layout for Discover section

- layout/explore/explore-topics/component.js
- layout/explore/explore-topics/styles.scss
This PR fixes the styles for the topic cards included in the Topics section from Explore.
Go to http://localhost:9000/data/explore?section=Topics
> Fix topic cards styles

- layout/explore/actions.js
- layout/explore/component.js
- layout/explore/constants.js
- layout/explore/explore-collections/component.js
- layout/explore/explore-collections/index.js
- layout/explore/explore-collections/selectors.js
- layout/explore/explore-collections/styles.scss
- layout/explore/explore-login/component.js
- layout/explore/explore-login/index.js
- layout/explore/explore-login/styles.scss
- layout/explore/explore-menu/component.js
- layout/explore/explore-menu/index.js
- layout/explore/explore-menu/selectors.js
- layout/explore/explore-menu/styles.scss
- layout/explore/index.js
- layout/explore/initial-state.js
- layout/explore/reducers.js
- pages/app/explore/index.js
This PR adds the user collections feature to the Explore section.
Test the interface both logged in and logged out to see the two different visual states of the component.
_NOTE: Only datasets from the collection are shown, (no widgets, dashboards, ...)_
_Also we still need to decide what to do when the user selects a collection that has no dataset included in it_.
> Explore collections

- layout/explore/explore-discover/component.js
- layout/explore/explore-discover/index.js
- layout/explore/explore-discover/styles.scss
This PR adds the highlighted datasets to the `Discover` section.
Verify that 4 datasets are loading.
⚠️ Bear in mind that the `isHighlighted` filter has not been implemented yet in the API. Thus the datasets being currently returned are arbitrary.
> Explore discover: highlighted datasets

- components/collections-panel/collections-panel-component.js
- layout/explore/explore-collections/styles.scss
- layout/explore/explore-datasets/explore-datasets-actions/component.js
- layout/explore/explore-datasets/list/list-item/component.js
- layout/explore/explore-detail/explore-detail-tags/component.js
This PR includes minor style improvements for the collections view plus a fix for the click interaction with elements from dataset cards.
_UPDATE: It also fixes the behavior when clicking on tag pills from the dataset explore detail view_
Verify that collections' datasets are displayed accordingly and the user interaction flow with the collections tooltip works as expected.
> Explore: Collections styles improvements + interaction fixes

- components/admin/data/explore-form/component.js
- components/admin/data/explore-form/index.js
- components/datasets/form/DatasetsForm.js
- components/datasets/form/constants.js
- components/datasets/form/steps/component.js
- layout/explore/explore-discover/component.js
This PR adds the logic necessary to use the highlighted datasets feature.
This PR needs to be tested on the *staging* environment since the API endpoint has only been deployed to that environment. Please verify:
- Explore form: http://localhost:9000/admin/data/explore
- Explore discover section: http://localhost:9000/data/explore?section=Discover _verify here that the section `Trending datasets` load the right datasets_
- Dataset form: check that the `Highlighted` checkbox works as expected.
> Back office: explore form logic

- layout/explore/explore-discover/component.js
- services/config.js
This PR adds the logic to load the visual configuration for the Discover section from an external github file located [here](https://github.com/resource-watch/resource-watch/blob/develop/public/static/data/ExploreConfig.json)
Verify that the interface loads according to the content included in the config file.
> Explore Discover section: load configuration from external file

- layout/explore/component.js
- layout/explore/explore-collections/component.js
- layout/explore/explore-collections/index.js
- layout/explore/explore-collections/styles.scss
- layout/explore/explore-datasets/component.js
- layout/explore/explore-datasets/index.js
- layout/explore/explore-datasets/styles.scss
- layout/explore/explore-detail/styles.scss
- layout/explore/explore-discover/component.js
- layout/explore/explore-discover/index.js
- layout/explore/explore-discover/styles.scss
- layout/explore/explore-menu/component.js
- layout/explore/explore-menu/index.js
- layout/explore/explore-menu/styles.scss
- layout/explore/explore-near-real-time/component.js
- layout/explore/explore-near-real-time/index.js
- layout/explore/explore-near-real-time/styles.scss
This PR prevents data loading when going from Explore detail back to other sections such as Discover, All Data, or Near-Real-Time.
Try going back and forth from Explore detail to the rest of the Explore sections.
> Explore detail: prevent data loading when coming back from this section

- components/ui/map/map-thumbnail/index.js
- layout/explore/component.js
- layout/explore/explore-detail/explore-detail-buttons/component.js
- layout/explore/explore-detail/initial-state.js
This PR fixes the following issues:
1. When loading the explore detail section, the loader appears from the very beginning. Previously a message saying that data could not be loaded was momentarily displayed.
2. Fix issue consisting of the app breaking when a dataset didn't have the `subscribable` property initialized.
3. Fix issue with map previews in Explore not loading properly when the first page loaded was explore detail, (instead of navigating to this section from any other explore section). 
Steps to reproduce the issue number `3.` on the explore site:
1. Go to https://explore.resourcewatch.org/data/explore/Environmental-Democracy-Index-1490086842552?section=Discover&zoom=3&lat=0&lng=0&pitch=0&bearing=0&basemap=dark&labels=light&page=1&sort=most-viewed&sortDirection=-1
2. Click on …
> Some improvements related to some of the Explore user workflows

- layout/explore/component.js
- layout/explore/explore-sidebar/component.js
- layout/explore/explore-sidebar/index.js
This PR fixes the issues with the scroll position when changing between explore sections.
- Go to any of the sections, change the scroll position and then click on any of the menu elements to go to another section. Verify that the interfaces scrolls to the top of the new section.
- Click on links such as `SEE ALL`, `SEE ALL DATA` from the `Discover` section and verify that the section opened scrolls to the top.
- https://www.pivotaltracker.com/story/show/172012514
- https://www.pivotaltracker.com/story/show/172013630
> Explore: fix sidebar scroll behavior

- layout/explore/component.js
- layout/explore/explore-detail/related-content/component.js
- layout/explore/explore-detail/related-content/index.js
This PR includes the following two improvements for the related datasets section in the metadata page:
1. Loader and placeholder while the datasets are being fetched
2. Scroll to the top of the section when selecting one of them
Check the related content section of any given dataset.
> improve styles and scroll behavior for related content

- layout/explore/explore-detail/component.js
- layout/explore/explore-detail/index.js
- layout/explore/explore-map/component.js
This PR modifies the behavior when clicking on the layer info button from the map legend, now the explore detail section is opened and scrolled to the `Dataset layers` section instead of opening a modal. 
_NOTE: The modal is still opened when Explore is embedded_
Check the behavior when clicking on the info button both in Explore and an embedded instance of it.
> Explore map update: change behavior when clicking on info button

- layout/explore/explore-favorites/component.js
- layout/explore/explore-favorites/styles.scss
This PR adds a prompt to add favorites/collections if an user is logged in, but doesn't yet have any.
Make sure that you have no favorite datasets and go to the Explore _favorites_ section.
> Explore favorites: prompt when user has no favorite datasets

- layout/app/dashboard-detail/energy-country-explorer/power-generation-map/map-menu/component.js
- layout/app/dashboard-detail/energy-country-explorer/power-generation-map/map-menu/index.js
This PR adds the logic necessary to select the Global Power Plants dataset by default in the map section.
Go to http://localhost:9000/dashboards/energy?tab=country
> GEDC: select Global Power Plants dataset by default in map

- components/ui/gdpr-banner/styles.scss
This PR fixes the GDPR banner position.
Go to `localhost:9000/data/explore` after clearing the session storage and make sure the banner doesn't displace the interface to the bottom.
> Fix GDPR banner position

- components/vis/globe-cesium/component.js
This includes a very important correction to the default base map used in Pulse.
Verify that the base map looks the same but is corrected in Braddock Heights, Maryland.
NA
---
> Very important correction

- layout/explore/component.js
- layout/explore/explore-detail/index.js
This PR adds the right dataset description to the meta tags when users open a dataset detail page.
Load any dataset detail page and check that the right description is included in the `<head/>` metadata tags.
> Explore detail: dataset description meta tags

- layout/explore/explore-detail/component.js
This PR modifies the current behavior in Explore detail so that the widget editor is also shown when a raster datasets is selected.
Check any raster dataset in explore detail.
> Explore detail: show map visualization for raster datasets

- layout/explore/explore-map/styles.scss
**Before:**
**After: **
This PR fixes the styles issue shown above.
Check that the timeline legend is working fine [here](http://localhost:9000/data/explore/cli023-Standard-Precipitation-Index?section=All%20data&zoom=1.7732970661501868&lat=-13.436431891129605&lng=-77.52791432671418&pitch=0&bearing=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522c0c71e67-0088-4d69-b375-85297f79ee75%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522eb0574c3-50a8-4cd3-ba8d-4d13eb7b12ad%2522%257D%255D&page=1&sort=relevance&sortDirection=-1&search=spi)
> Explore: fix legend timeline mark styles

- layout/explore/explore-detail/further-information/component.js
This PR adds the following metadata fields to the `Further information` section of Explore detail:
- `Date of content`
- `License`
Check any given dataset that has values for these two fields.
> Explore detail: add license and date of content metadata fields

- layout/explore/explore-detail/explore-detail-footer/styles.scss
> Fix for "Explore metadata page map-widgets float over metadata navigation tabs"

- CHANGELOG.md
- package.json
Removes unused [colors](https://www.npmjs.com/package/colors) dev dependency.
run `rm -rf node_modules && yarn`. The app should start normally.
–
---
> removes colors dependency

- CHANGELOG.md
- components/app/myrw/widgets/tabs/new.js
- constants/widget-editor.js
- layout/explore/explore-detail/explore-detail-visualization/component.js
Disables default features `typography` and `end-user-filters` as they are not used in RW. Adding new disabled features was overriding the default ones.
- check any widget editor instance (for example in `/data/explore`) and check the default disabled features and the ones added later are not there.
https://www.pivotaltracker.com/story/show/174930015
---
> fixes override widget-editor default disabled features

- .eslintrc.json
- CHANGELOG.md
- components/admin/data/widgets/form/component.js
- components/admin/data/widgets/form/steps/component.jsx
- components/admin/data/widgets/form/steps/index.js
- components/app/myrw/widgets/WidgetsTab.js
- components/app/myrw/widgets/tabs/edit/component.jsx
- components/app/myrw/widgets/tabs/edit/index.js
- components/app/myrw/widgets/tabs/new/component.jsx
- components/app/myrw/widgets/tabs/new/index.js
- constants/widget-editor.js
- layout/explore/explore-detail/explore-detail-visualization/component.jsx
Modifies RW-adapter's `widget editor` to listen to app env variables and others.
Test with the API pointing to staging and production environments. `widget-editor` should point based on the environmental variables.
Related to: https://www.pivotaltracker.com/story/show/174996497
---
> widget-editor: RW adapter changes

- CHANGELOG.md
- components/wysiwyg/widget-block-edition/index.jsx
- utils/widget.js
Enforces `widgetConfig` attribute to be an object. This way widgets who don't fulfil the validations won't be displayed in the application. This validation has to be applied eventually across the app.
_Users are experiencing a soft 404 from the dashboard editing interface. When attempting to add a visualization (chart/widget): Within the "select visualization" menu, "My visualizations" and "My favorites" tabs display widgets as expected, but selecting the "all visualizations" tab triggers the soft 404._
https://www.pivotaltracker.com/story/show/174911795
---
> enforces widgetConfig attribute to be an object

- CHANGELOG.md
- package.json
- yarn.lock
- Moved `webpack` from `dependencies` to `devDependencies`.
- Removed unused `next-progressbar` and `webpackbar` dev dependencies.
`rm -rf node_modules && yarn`. Run the application as usual, no changes.
–
---
> dependencies cleanup

- CHANGELOG.md
- layout/explore/explore-detail/explore-detail-visualization/component.jsx
Fixes a widget-editor crash with map widgets. The `map` option in the visualization type selector wasn't there because we disabled the `map` feature preventing the WE to select the current or new types and crashing.
In data explore, click on a map widget and try to change the type. The widget-editor shouldn't crash anymore.
https://www.pivotaltracker.com/story/show/175165737
---
> fixes WE crash with map widgets

- public/static/data/CountryEnergyExplorer.json
Fixes dashboard widget currently showing total co2, but should show co2 per capita. See basecamp thread and Iker's helpful SQL for more info
---
> update GEDC dash co2 per cap query

- CHANGELOG.md
- layout/explore/explore-areas-of-interest/component.jsx
- layout/explore/explore-areas-of-interest/intro/component.jsx
- layout/explore/explore-areas-of-interest/intro/index.js
- layout/explore/explore-areas-of-interest/intro/styles.scss
Adds call action in areas of interest to go to all-data section.
Go to "Areas of Interest" in Explore.
–
---
> adds call action in areas of interest to go to all-data section

- public/static/data/CountryEnergyExplorer.json
Replace widget that had been deleted (API ID dcb73b1b-f744-4db3-ae44-c4552b04e457) with a new one entitled "Countries with the highest electricity consumption in 2017". This is a "world" widget in the "Power Generation and Consumption" section.
Replace broken widget with new one.
Ensure the new widget (API ID 64d7466b-4d33-44a4-9ecc-c437905137e5) entitled "Countries with the highest electricity consumption in 2017" shows up on the page. 
---
> Replace missing widget

- CHANGELOG.md
- index.js
- next.config.js
Removes `x-powered-by` headers following [best practices](http://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header).
`curl -I http://localhost:9000`. `x-powered-by` header should not appear.
–
---
> removes x-powered-by headers

- CHANGELOG.md
- components/dashboards/detail/component.js
- components/map/component.js
- components/wysiwyg/widget-block/component.js
- Reduces workload and impact of the page rendering elements when they are visible.
- Improves error handling when the bbox is wrong.
Check on `/dashboards/cities` or any other dashboard in prod API.
https://www.pivotaltracker.com/story/show/175408544
---
> dashboards: render while scrolling

- CHANGELOG.md
- components/wysiwyg/widget-block/styles.scss
- css/components/app/pages/embed/embed_widget.scss
- layout/embed/map/component.jsx
Adds widget links to map-type widget embed.
Go to `http://localhost:9000/embed/map/f14e47f1-fefb-412a-aa40-05a566a13667` (production API) and click on (i) button to display the modal info.
https://www.pivotaltracker.com/story/show/175408294
---
> adds widget links to map-type widget embed

- CHANGELOG.md
- components/map/popup/component.js
Fixes app crash when data in map tooltip is undefined.
Go to `http://localhost:9000/data/explore/foo055b-Gridded-Livestock-Version-3?section=All%20data&zoom=3&lat=0&lng=0&pitch=0&bearing=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%25226b523d76-ca2d-4059-b0a6-d90a6b8ba5a6%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%252210587041-b4c5-493d-ac9e-cf75bc2d58b7%2522%257D%255D&page=1&sort=most-viewed&sortDirection=-1&topics=%255B%2522livestock%2522%255D` and click on any point of the layer. Previosuly, the app would crash.
https://www.pivotaltracker.com/story/show/175888099
---
> fixes app crash when data in map tooltip is undefined

- CHANGELOG.md
- components/admin/data/widgets/form/component.js
Fixes an error where the metadata of the widget was being overridden by the `widget-editor` output, as we didn't pass the whole metadata object.
Go to the admin zone and modify a `widgetLink` (in metadata tab), then save from widget-editor. The widget must contain the widgetLinks.
https://www.pivotaltracker.com/story/show/175408294
---
> fixes widget metadata override

- CHANGELOG.md
- layout/explore/explore-menu/component.jsx
Fixed an issue with the explore search when the user wasn't able to get results the first time it entered a search term.
Go to `/data/explore` and try to search for a term. The expected result is seeing the results (if any) displayed.
https://www.pivotaltracker.com/story/show/176263572
---
> fixes explore search not working first time

- CHANGELOG.md
- Jenkinsfile
- components/areas/card/tooltip/component.jsx
- layout/embed/map/component.jsx
- layout/explore/explore-map/component.jsx
- next.config.js
- services/areas.js
Removes `RW_FEATURE_FLAG_AREAS_V2` feature flag.
Remove `RW_FEATURE_FLAG_AREAS_V2` from `.env`. The application should work as if the env var were there.
–
---
> removes RW_FEATURE_FLAG_AREAS_V2 feature flag

- layout/embed/map/component.jsx
fixes the url path constructed for the href element of embed widget titles in map-type widgets
---
> patch map embed title href

- CHANGELOG.md
- package.json
- yarn.lock
Removes bcrypt dependency.
`rm -rf node_modules && yarn`
–
---
> removes bcrypt dependency

- CHANGELOG.md
- package.json
- yarn.lock
Moves `@babel/core` dependency to devDependencies.
`rm -rf node_modules && yarn`
–
---
> moves @babel/core dependency to devDependencies

- CHANGELOG.md
- package.json
- yarn.lock
Replaces deprecated `better-npm-run` with [cross-env](https://github.com/kentcdodds/cross-env).
`yarn` and test any script in the `package.json`
–
---
> replaces better-npm-run

- CHANGELOG.md
- README.md
- next.config.js
- package.json
- yarn.lock
Replaces `webpack-bundle-analyzer` dependency with `@next/bundle-analyzer`.
- `rm -rf node_modules && yarn`
- `yarn analyze`
–
---
> adds @next/bundle-analyzer

- .gitignore
- CHANGELOG.md
- layout/app/dashboard-detail/component.jsx
- pages/app/dashboards-detail/index.jsx
Fixes issue populating open graph tags in dashboards pages. 
Moved dashboard load to the server to help with SEO.
–
https://www.pivotaltracker.com/story/show/177007206
---
> fixes issue populating open graph tags in dashboards pages

- CHANGELOG.md
- layout/embed/dataset/component.jsx
- layout/embed/embed/component.jsx
- layout/embed/map/component.jsx
- layout/embed/table/component.jsx
- layout/embed/text/component.jsx
- layout/embed/widget/component.jsx
- pages/app/embed/dataset/index.jsx
- pages/app/embed/text/index.jsx
- pages/app/embed/widget/index.jsx
- redactions/common.js
- utils/embed.js
Fixes an issue where the "Powered by Resource Watch" sentence wasn't displaying on external sites. Now we use `document.referrer` instead of `window.location.href` as inside of an iframe, the URL is Resource Watch's one instead of the URL of the external site.
–
---
> fixes embed powered by in external sites

- Jenkinsfile
Skips tests in Jenkins temporary. To revert ASAP.
–
–
---
> Jenkins: skips tests temporary

- CHANGELOG.md
- redactions/admin/pages.js
- services/pages.js
Removes `authorization` header from GET `/static_page` endpoints.
–
https://vizzuality.atlassian.net/browse/RW-19?focusedCommentId=10534
---
> removes authorization header from GET `/static_pages` endpoint

- CHANGELOG.md
- components/app/myrw/datasets/pages/index.js
- components/app/myrw/widgets/tabs/list/constants.js
- components/app/myrw/widgets/tabs/list/helpers.js
- components/collections-panel/collections-panel-constants.js
- components/wysiwyg/widget-block-edition/component.js
- components/wysiwyg/widget-block-edition/index.jsx
- cypress/integration/components/share-modal.spec.js
- hooks/favorite/fetch-favorites.js
- redactions/admin/datasets.js
- redactions/widget.js
- services/favourites.js
Updated the spelling of `favourite` in the following places:
- MyRW dashboards (creation/edition): add new block → visualization → “My favorites”
- MyRW datasets (collections aside).
- MyRW widgets (collections aside).
Also URLs:
`/myrw/widgets/favourites` → `/myrw/widgets/favorites`
`/myrw/datasets/favourites` → `/myrw/datasets/favorites`
Go to `/myrw/widgets/favorites` and check the spelling is correct in the collection list aside. Also, clicking on "Favorites" should load the user's favorites widgets.
For datasets, follow the same instructions as for widgets but go to `/myrw/datasets/favorites`.
For dashboards, go to dashboard creation/edition, click on a new block, select type `Visualization`, the second tab should be spelt `My favorites` and should load the user's favorites widgets. …
> RW-35 favorite spelling

- CHANGELOG.md
- layout/explore/explore-detail/explore-detail-header/component.jsx
- layout/explore/explore-detail/explore-detail-header/index.js
Fixes visual bug with dataset navigation bar in Explore when a dataset is selected and the sidebar is closed.
- Go to `/data/explore` and click on any dataset.
- Close the sidebar.
- The navigation bar should hide along with the sidebar content.
https://vizzuality.atlassian.net/browse/RW-37
---
> fixes visual bug with dataset navigation bar in explore

- CHANGELOG.md
- components/admin/partners/form/constants.js
- components/admin/partners/form/steps/Step1.js
- layout/admin/partners-detail/component.jsx
Adds new types of partners for Ocean Watch.
Go to `/admin/partners/partners/new` and click on "Partner Type". The list should display the new options available.
https://vizzuality.atlassian.net/browse/OW-56
---
> OW-56 – ocean watch: adds new type of partners

- components/dashboards/detail/component.js
- components/error-fallback/component.jsx
- components/error-fallback/index.js
- components/error-fallback/styles.scss
- components/mini-explore/styles.scss
- components/wysiwyg/mini-explore/component.jsx
- components/wysiwyg/mini-explore/index.js
- package.json
- pages/dashboards/[slug].jsx
- yarn.lock
This PR implements the needed code to read and render the mini Explore following the WYSIWYG flow.
This PR **does not** add the MiniExplore component to Coral Reef dashboard. The configuration needs to be read via API.
–
https://vizzuality.atlassian.net/browse/RW-59
---
> implements mini-explore in WYSIWYG flow

- CHANGELOG.md
- README.md
- package.json
- yarn.lock
Upgrades `react-redux` allowing the use of hooks.
Updates README reflecting change.
- Install dependencies via `yarn`.
- Run application (`yarn dev`). Applications should behave as usual.
https://vizzuality.atlassian.net/browse/RW-47
---
> react-redux@7.2.4

- CHANGELOG.md
- components/areas/card/component.jsx
- layout/embed/map/component.jsx
- layout/explore/explore-map/component.jsx
Fixes areas of interest load in Explore and other places removing Axios' cancel Token.
Go to Explore and turn on one of your areas of interest. It should appear in the map.
https://vizzuality.atlassian.net/browse/RW-67
---
> removes Axios' cancel token

- css/components/datasets/list-item.scss
- css/components/datasets/search.scss
- css/components/form/field.scss
- css/components/form/toggle-search.scss
- css/components/map/map.scss
- css/components/ui/related-content.scss
- css/components/ui/search-input.scss
- css/components/ui/switch-options.scss
- css/components/ui/table_tooltip.scss
- css/components/ui/tooltip-global.scss
- css/components/widgets/widget-tooltip-list.scss
- css/index.scss
- css/layouts/_container.scss
- yarn.lock
- replaces importing sass files and uses `css`files. This skips `sass` compilation of files coming from libraries with `css` alternatives ready to use.
- replaces deprecated `/` for division, uses `math.div` instead.
- updates browserlist.
Run the application, styles should not be affected. Warnings in the console should be reduced considerably.
None.
---
> replaces import `sass` files with `css`

- CHANGELOG.md
- utils/layers/index.js
Fixes a condition where opacity `0` was treated as falsy value and not applied.
Apply opacity 0 to any layer inside the `layerParams` object in the widget configuration.
https://vizzuality.atlassian.net/browse/OW-94
---
> fixes opacity 0

- CHANGELOG.md
- package.json
- yarn.lock
In WYSIWG, removes "mini-explore" button from toolbar.
https://vizzuality.atlassian.net/browse/RW-74
---
> wysiwyg: removes mini-explore from toolbar

- CHANGELOG.md
- layout/layout/ocean-watch/storytelling/component.jsx
- layout/layout/ocean-watch/storytelling/story-step/component.jsx
- layout/layout/ocean-watch/storytelling/story-step/index.jsx
- pages/dashboards/ocean-watch/index.jsx
Adds a worldwide geostore as widget param to all widgets inside the storytelling.
–
–
–
–
> storytelling: worldwide geostore

- components/admin/data/layers/table/component.js
- components/admin/data/widgets/table/component.js
- components/admin/pages/table/PagesTable.js
- components/admin/partners/table/component.js
- components/admin/tools/table/ToolsTable.js
- components/dashboards/table/DashboardsTable.js
- components/datasets/table/component.js
This PR adds a new `env` column to all the tables from the back office.
Check all different entity sections in the back office.
https://vizzuality.atlassian.net/browse/RER-42
> Add env columns to back office tables

- public/static/data/ocean-watch.json
Duplicates data structure under `production` key. Replaces https://github.com/resource-watch/resource-watch/pull/1756
–
–
–
> ocean watch: duplicates data structure to production

- CHANGELOG.md
- pages/data/explore/[[...dataset]].jsx
Fixes a wrong update from the router when the explore page tried to update its state to be reflected in the URL.
https://vizzuality.atlassian.net/browse/RW-82
–
–
> fixes explore route on update

- components/admin/data/layers/form/steps/Step1.js
- components/admin/data/widgets/form/steps/component.jsx
- components/admin/pages/form/steps/Step1.js
- components/admin/partners/form/steps/Step1.js
- components/admin/tools/form/steps/Step1.js
- components/dashboards/form/steps/step-1/component.jsx
- components/datasets/form/steps/component.js
This PR adds environment selectors to those forms where they are missing.
Verify that all entities from the back office have a working environment selector (dataset, widget, layer, dashboard, partner, tool, page...)
https://vizzuality.atlassian.net/browse/RER-44
> Add missing env selects

- components/card-indicator-set/numeric-card-indicator/index.jsx
- layout/layout/ocean-watch/storytelling/component.jsx
- layout/layout/ocean-watch/storytelling/story-step/component.jsx
- layout/layout/ocean-watch/storytelling/story-step/index.jsx
- public/static/data/ocean-watch.json
Indicator queries, format, and units changed for `land-sea-interface` and Card queries, format, and units changed for `OECD-FAO-agricultural_outlook`
Resolves #XXX
> Testing indicator and card values

- public/static/data/ocean-watch.json
Updated queries, formats, and units for the indicator values to appear next to the chart widgets. Additionally a test for the horizontal row of boxes for `FAO-fish-food-supply`
Resolves #XXX
> Updated `why-is-the-ocean-so-valuable` indicator values in production

- public/static/data/ocean-watch.json
Query removed for `intro` page (should display no value, just text). Query updated on `country` page (should display share of emissions from marine shipping as %)
Resolves #XXX
> Updated query for `blue-economy`

- public/static/data/ocean-watch.json
New query for `fisheries-subsidies` indicator. Previous d3 formatting with `s` was showing 'G' instead 'B' for billions. All formatting was moved inside the query.
Resolves #XXX
> Reformatted `fisheries-subsidies` indicator

- CHANGELOG.md
- components/widgets/types/map-swipe/index.jsx
- components/widgets/types/map/index.jsx
- utils/layers/index.js
Enforces activeness of layers inside map/swipe map widgets to avoid dependency of their configuration in certain cases.
–
–
> enforces layer activeness regardless configuration

- public/static/data/ocean-watch.json
The table name has been updated for the dataset behind the `blue-food` indicator. I have adjusted the query to reflect that change
> Update table for `blue-food` indicator query

- CHANGELOG.md
- components/mini-explore/map/index.jsx
Fixes layer interactivity that allows displaying the tooltip with layer data.
–
https://vizzuality.atlassian.net/browse/OW-185
> mini-explore: fixes layer interactivity

- CHANGELOG.md
- components/map/controls/basemap/component.jsx
- components/map/layer-manager/component.js
- components/mini-explore/component.jsx
- components/mini-explore/component.stories.jsx
- components/mini-explore/map/component.jsx
- components/mini-explore/map/index.jsx
- components/widgets/types/map-swipe/component.jsx
- components/widgets/types/map/component.jsx
- layout/layout/ocean-watch/hero/component.jsx
- layout/layout/ocean-watch/map/component.jsx
- pages/dashboards/ocean-watch/country/index.jsx
Set of changes in maps to compliant UN requirements:
- removes boundaries of slide maps.
- allows hiding boundaries controls.
- removes boundaries in map selector located in Ocean Watch homepage.
–
https://vizzuality.atlassian.net/browse/OW-192
> UN compliant changes

- CHANGELOG.md
- components/mini-explore/reducer.js
Fixes swapping layers in mini-explore.
https://vizzuality.atlassian.net/browse/OW-159
> fixes swapping layers in mini-explore

- CHANGELOG.md
- css/mapbox.scss
Fixes tooltip overlap blocking clicking on map.
https://vizzuality.atlassian.net/browse/OW-175
> fixes tooltip overlap on map click

- CHANGELOG.md
- components/ui/map/map-thumbnail/helper.js
- components/ui/map/map-thumbnail/index.js
Fixes query concatenation to build background CSS rule.
https://vizzuality.atlassian.net/browse/RW-108
> map thumbnail: fixes string concatenation

- CHANGELOG.md
- components/app/myrw/areas/tabs/index/component.jsx
- components/areas/card/component.jsx
- components/map/component.tsx
- components/map/constants.ts
- components/map/utils.js
- components/mini-explore-widgets/component.jsx
- components/mini-explore-widgets/map/index.jsx
- components/widgets/types/map/index.jsx
- pages/layer-manager.tsx
- public/static/data/ocean-watch.json
- types/layer.d.ts
- utils/layers/index.js
- Updates `area of interest (AoI)` templates to achieve LMv4 compatibility. This affects: Explore AoI,  user AoIs (`/myrw/areas`) and Ocean Watch predefined AoIs.
- map component: makes `onMapViewportChange` function optional.
https://vizzuality.atlassian.net/browse/RW-99
https://vizzuality.atlassian.net/browse/RW-97
https://vizzuality.atlassian.net/browse/RW-102
> Layer Manager v4 - Ocean Watch-related changes

- CHANGELOG.md
- components/map/constants.ts
- layout/explore/explore-map/component.jsx
Fixes an error handling Area of Interest layers. The filtering criteria was based on the previous layer spec. Updating it solved the issue.
https://vizzuality.atlassian.net/browse/RW-120
> explore: fixes aoi layer handling

- CHANGELOG.md
- package.json
- yarn.lock
- removes `react-input-autosize`.
–
> removes react-input-autosize

- CHANGELOG.md
- components/datasets/list/selectors.js
- components/datasets/search/search-component.js
- layout/app/pulse/layer-card/selectors.js
- layout/explore/actions.js
- layout/explore/explore-datasets/component.jsx
- layout/explore/explore-datasets/list/list-item/component.js
- layout/explore/explore-datasets/list/list-item/index.js
- layout/explore/explore-datasets/list/selectors.js
- layout/explore/explore-datasets/selectors.js
- layout/explore/explore-detail/explore-detail-header/component.jsx
- layout/explore/explore-menu/component.jsx
- layout/explore/reducers.js
- pages/data/explore/[[...dataset]].jsx
- redactions/common.js
Fixes navigation when a user searches for datasets. Before, after clicking on the "All Datasets" button, the page lost the search parametrization displaying the list of datasets without the user's filters. Now, the page keeps this parameterization allowing the user to keep looking at his/her search.
https://vizzuality.atlassian.net/browse/RW-87
> explore: fixes navigation with search

- CHANGELOG.md
- components/admin/data/layers/form/steps/Step1.js
Fixes typo with published layer checkbox.
https://vizzuality.atlassian.net/browse/RW-146
> fixes typo in published layer checkbox

- CHANGELOG.md
- components/map/constants.ts
- components/widgets/types/map/component.tsx
- types/widget.d.ts
Now `/embed/map/{widget_id}` and `/data/widget/{widget_id}` routes take into account map paramesitration (`lat`, `lng` and `zoom` attributes) coming from widget configuration.
https://gfw.atlassian.net/browse/RW-3
> takes into account map widget config for embed routes

- CHANGELOG.md
- constants/app.ts
- layout/app/newsletter/component.tsx
- layout/app/newsletter/constants.ts
- layout/app/newsletter/types.d.ts
- layout/explore/explore-my-data/coming-soon/component.tsx
As per [requested by Pardot](https://help.salesforce.com/s/articleView?id=000364239&type=1), Resource Watch stops using default _go.pardot.com_ URLs and uses a custom one provided by WRI.
https://gfw.atlassian.net/browse/RW-8
> updates default Pardot URL
